#!/usr/bin/env python3
"""Generate or check the sealed C26 static tooling artifacts."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import p03_c26_contracts as contracts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--apply", action="store_true", help="write the five generated JSON artifacts")
    mode.add_argument("--check", action="store_true", help="check generated bytes without writing")
    mode.add_argument("--dump-json", action="store_true", help="print generated artifact paths and digests")
    args = parser.parse_args()

    rendered = contracts.all_outputs(ROOT)
    failures: list[str] = []
    for relative, raw in rendered.items():
        path = ROOT / relative
        if args.apply:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(raw)
        elif args.check and (not path.is_file() or path.read_bytes() != raw):
            failures.append(relative)
        elif args.dump_json:
            print(f"{relative}\t{len(raw)}\t{contracts.sha256_bytes(raw)}")
    if args.apply:
        print(f"applied {len(rendered)} C26 artifacts")
        return 0
    if failures:
        for relative in failures:
            print(f"stale or missing: {relative}", file=sys.stderr)
        return 1
    if args.check:
        print(f"C26 generator check PASS ({len(rendered)} artifacts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
