from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];COORD=Path(r"C:\AssetRounds-v23-coordination")
CARD="V23-P04-C24";BASE="3a338afa490daa214c07e7e80264769436d4383e";BTREE="1e5d88c62f195555d5ec16cdced0f7998c9d61b2";HEAD="b15a8ae6036320779b70e94413c92fe0539b1477";CTREE="6cec7818ac4a8726c6c8d602da57d5789e618f18";CONTEXT="63099024f9d96a29b583c78517fd6df1fe40523d729fd1bdeddbcbe34585ad4c";FENCE="01365caf67feece268f928349f2f9c1c811da94b5bcd5b92be4dc0cd42177018";ALLOCATION="7981c07137b503d65020cc6b55d994e92b8d422b3f0a35996bd2f943b96bb8ac";PREREQ="fe0f69588164da772917365961871ccd771e6febc7cd184e995918e749b7a468";SEQ=485;FINAL_HASHES_SEALED=True
SCHEMA="Scripts/v23/dictation-location-proposal.schema.json";CONTRACT="docs/design/v23/tooling/V23P04C24DictationLocationProposalContractV1.json";EVIDENCE="docs/design/v23/tooling/V23P04C24DictationLocationProposalEvidenceReceiptV1.json";BRAND="docs/design/v23/tooling/V23P04C24BrandImpactManifestV1.json";MANIFEST="docs/design/v23/tooling/V23-P04-C24-tooling-manifest.json";SCRIPTS=("Scripts/v23/p04_c24_contracts.py","Scripts/v23/generate_p04_c24_contracts.py","Scripts/v23/verify_p04_c24_contracts.py");OWNED=set((*SCRIPTS,SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST))
SELECTORS=("testV23P04C24G01EnabledOnDeviceDictationEditAcceptAndOneShotLocationReview","testV23P04C24A01IndependentPermissionDenialsAndCompleteManualFallbacks","testV23P04C24H01UnsupportedLocalePoorAccuracyStaleTargetAndNoServer","testV23P04C24I01AudioInterruptionLocationTimeoutAndScratchCleanup","testV23P04C24R01AcceptedReceiptRestoreNoEphemeralOrphanAndAccessibility");FLAGS={x:False for x in("physicalDevice","native","hosted","activation","adoption","acceptance","publication","release")}
def pretty(x):return(json.dumps(x,sort_keys=True,indent=2)+"\n").encode()
def sha(x):return hashlib.sha256(x).hexdigest()
def git(*x,cwd=ROOT):return subprocess.run(["git",*x],cwd=cwd,check=True,capture_output=True,text=True).stdout.strip()
def authority():
 p=COORD/"contexts/V23-P04-C24-attempt-1";c=json.loads((p/"BootstrapCardContextV1.json").read_bytes());f=json.loads((p/"BootstrapPathFenceV1.json").read_bytes());q=f["priorFenceProof"]
 if (git("rev-parse","HEAD",cwd=COORD),git("rev-parse","HEAD^{tree}",cwd=COORD))!=(HEAD,CTREE):raise ValueError("C24 coordination differs")
 if (c["contextDigest"],f["fenceDigest"],c["ownerAuthorizedPathAllocationDigest"],c["provisionalPrerequisiteDigest"])!=(CONTEXT,FENCE,ALLOCATION,PREREQ):raise ValueError("C24 authority differs")
 if (len(c["existingPaths"]),len(c["newPaths"]),len(f["allowedCreateOrReplacePaths"]),q["fenceCount"],q["priorOwnedPathCount"],q["authorizedOverlapCount"],q["unauthorizedOverlapCount"],q["s10ReservedOverlapCount"])!=(26,14,40,4,304,59,0,0):raise ValueError("C24 fence proof differs")
 return c,f
def sources():_,f=authority();return tuple(p for p in f["allowedCreateOrReplacePaths"] if p not in OWNED)
def rows():
 r=[{"path":p,"status":"SOURCE_PRESENT" if(ROOT/p).is_file()else"SOURCE_MISSING","sha256":sha((ROOT/p).read_bytes())if(ROOT/p).is_file()else None}for p in sources()];return r,all(x["status"]=="SOURCE_PRESENT"for x in r)
def counts():
 _,f=authority();own=set(f["allowedCreateOrReplacePaths"]);z=lambda t:{x.replace("\\","/")for x in t.splitlines()if x};x=z(git("diff","--name-only",BASE,"HEAD"))|z(git("diff","--name-only","HEAD"))|z(git("diff","--cached","--name-only"))|z(git("ls-files","--others","--exclude-standard"))|OWNED;return{"changedPathCount":len(x&own),"missingPathCount":sum(not(ROOT/p).is_file()for p in own-OWNED),"unownedChangedPathCount":len(x-own),"s10ReservationOverlapCount":len(own&set(f["activeS10ReservedPaths"]))}
def semantics(ready):
 if not ready:return
 b={p:(ROOT/p).read_text(encoding="utf-8",errors="replace")for p in sources()};registry=ROOT/"FieldEvidenceApp/Infrastructure/Persistence/PersistentSchemas.swift"
 if not registry.is_file():raise ValueError("C24 persistent schema registry unavailable")
 t="\n".join((*b.values(),registry.read_text(encoding="utf-8",errors="replace")));test=b.get("FieldEvidenceAppTests/V9_87DictationLocationProposalTests.swift","");ui=b.get("FieldEvidenceAppUITests/V23_P04_C24DictationLocationProposalUITests.swift","")
 need=("DictationLocationProposal","PREPARED_DISABLED","dictation","location","transcript","locale","coordinate","horizontalAccuracy","manualFallback","scratch","accepted","search","report","PersistentSchemaV53","AssistanceAcceptanceReceiptRow")
 if any(x not in t for x in need):raise ValueError("C24 source semantics missing")
 if any(x not in test for x in SELECTORS)or ui.count("XCTSkip")!=5:raise ValueError("C24 selectors/UI skip mismatch")
 core=b["FieldEvidenceApp/Domain/Assistance/DictationLocationProposalContractsV1.swift"];coord=b["FieldEvidenceApp/Application/Assistance/DictationLocationProposalCoordinatorV1.swift"];life=b["FieldEvidenceApp/Infrastructure/Assistance/DictationLocationProposalLifecycleAdapterV1.swift"]
 exact_core=("permitsOnDeviceDictation","permitsOneShotForegroundLocation","recognitionRequestRevision","transcriptRevision","audioRevision == request.scratchSource.revision","maximumTranscriptUTF8Bytes==policy.maximumTranscriptUTF8Bytes","horizontalAccuracyMillimeters<=maximumHorizontalAccuracyMillimeters","verticalAccuracyMillimeters","source:OneShotLocationSourceV1")
 exact_coord=("requireDictationProposalContentAccess","requireOneShotLocationProposalContentAccess","manualDictation(DictationManualFallbackV1.allCases)","manualLocation(LocationManualFallbackV1.allCases)","receipt.validate(dictation:dictation,review:review", "receipt.validate(location:location,review:review")
 exact_life=("requestMicrophonePermission","requestSpeechRecognitionPermission","dictateOnDevice", "requestWhenInUsePermission", "requestOneShotForegroundLocation")
 if any(x not in core for x in exact_core)or any(x not in coord for x in exact_coord)or any(x not in life for x in exact_life):raise ValueError("C24 permit/revision/location/receipt guard missing")
 review=("enum DictationLocationReviewedAcceptanceV1","static func validate(dictation:OnDeviceDictationProposalV1","static func validate(location:OneShotLocationProposalV1","review.validate(originalProposalID:original.proposalID")
 preflight=("try DictationLocationReviewedAcceptanceV1.validate(dictation:","try DictationLocationReviewedAcceptanceV1.validate(location:","try await assistance.accept(proposalID:acceptedProposal.proposalID")
 transfer=("replaceForReview(","scratchTransferCount, 1","scratchTerminalCount, 0","scratchTerminalCount, 1","rejectionLifecycle.scratchTerminalCount, 1")
 if any(x not in core for x in review)or any(x not in coord for x in preflight)or any(x not in test for x in transfer):raise ValueError("C24 review prevalidation/scratch transfer guard missing")
 if any(x in t for x in("URLSession","http://","https://","backgroundAudio","autoWrite","serverUpload")):raise ValueError("C24 prohibited behavior")
def documents():
 _,f=authority();r,ready=rows();n=counts();a={"cardID":CARD,"appBaseHead":BASE,"appBaseTree":BTREE,"coordinationHead":HEAD,"coordinationTree":CTREE,"sequence":SEQ,"contextDigest":CONTEXT,"pathFenceDigest":FENCE,"allocationDigest":ALLOCATION,"prerequisiteDigest":PREREQ,"finalHashesSealed":FINAL_HASHES_SEALED,"fencePathCount":40,"existingPathCount":26,"newPathCount":14,"priorFenceCount":4,"priorOwnedPathCount":304,"authorizedOverlapCount":59,"s10OverlapCount":0};s={"persistentSchema":"V53","activeModelCount":168,"newDurableRecordCount":0,"newDurableFamilies":[],"reusedReceipt":"AssistanceAcceptanceReceiptRow","availability":"PREPARED_DISABLED","statusFlags":FLAGS};p={"sourceReady":ready,"sourceRows":r,"counts":n,"selectors":list(SELECTORS)};co={"schema":"V23P04C24DictationLocationProposalContractV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":s,"sourceProjection":p,"testSelectors":list(SELECTORS),"statusFlags":FLAGS};ev={"schema":"V23P04C24DictationLocationProposalEvidenceReceiptV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"sourceProjection":p,"contractDigest":sha(pretty(co)),"statusFlags":FLAGS};br={"schema":"V23P04C24BrandImpactManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":s,"sourceProjection":p,"uiAdoptionSkipped":True,"uiAcceptanceCredit":False,"statusFlags":FLAGS};m={"schema":"V23P04C24ToolingManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"finalHashesSealed":FINAL_HASHES_SEALED,"authority":a,"pathFence":f["allowedCreateOrReplacePaths"],"files":[{"path":k,"sha256":sha(pretty(v))}for k,v in((CONTRACT,co),(EVIDENCE,ev),(BRAND,br))],"sources":r,"counts":n,"toolingPaths":[*SCRIPTS,SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST],"statusFlags":FLAGS};return{CONTRACT:co,EVIDENCE:ev,BRAND:br,MANIFEST:m}
