from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];COORD=Path(r"C:\AssetRounds-v23-coordination");CARD="V23-P04-C22";BASE="d40d75d615d217b3da9cfc46c2078ee97b199b12";BTREE="7bf75da1a00976d6e1c2ffa9b02d0026fa20bb15";HEAD="431f40af193c8c8abb45b07124cbe4be64b4684c";CTREE="1715f7108a967b19504a01baa8e6dbb22f5cf8cc";CONTEXT="74432a37e3d1fdb186c0f1bd4daec7d0f8e9acf630e94df842895d713077ae03";FENCE="b180edceaec4cc56e419bf8cc7fd8881ac048e9cb7b1efeb045586b043a1f34d";ALLOCATION="fda793f6c71d3cbc6c569dfb06258f4568c096ac4e383d0acc6326da281d94fa";PREREQ="33a163b6e7e5adaf8f1ff640b8f37823a30a284a1bb2336c0527e4e1e2ef4da5";SEQ=476;FINAL_HASHES_SEALED=False
SCHEMA="Scripts/v23/recurring-round-experience.schema.json";CONTRACT="docs/design/v23/tooling/V23P04C22RecurringRoundExperienceContractV1.json";EVIDENCE="docs/design/v23/tooling/V23P04C22RecurringRoundExperienceEvidenceReceiptV1.json";BRAND="docs/design/v23/tooling/V23P04C22BrandImpactManifestV1.json";MANIFEST="docs/design/v23/tooling/V23-P04-C22-tooling-manifest.json";SCRIPTS=("Scripts/v23/p04_c22_contracts.py","Scripts/v23/generate_p04_c22_contracts.py","Scripts/v23/verify_p04_c22_contracts.py");OWNED=set((*SCRIPTS,SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST));SELECTORS=("testV23P04C22G01FixedScheduleDueQueueAndExplicitStartRemainExact","testV23P04C22A01CompletionRelativeTimezoneAndReminderReconciliationRemainTruthful","testV23P04C22H01InvalidHorizonPacketAndDuplicateStartFailClosed","testV23P04C22I01InterruptedStartCompleteAndReminderRebuildAreIdempotent","testV23P04C22R01RestoreReplayHistoryAndOfflineReadinessRemainExact");FLAGS={x:False for x in("activation","native","hosted","adoption","acceptance","release","publish","nativeAcceptance","hostedAcceptance","physicalEvidence","phase10PollingDuringParallelExecution")}
FINAL_HASHES_SEALED=True
SELECTORS=("testV23P04C22G01FixedCompletionRelativeEditorDueAndStartOnce","testV23P04C22A01ReminderDenialEvictionStableIDReconcileKeepsDueTruth","testV23P04C22H01DSTTimeZoneActiveEditHorizonRetiredPartialPacketFailClosed","testV23P04C22I01InterruptedWritesAndSameMutationIDRecoverIdempotently","testV23P04C22R01BackupReplaceCloneForkRebuildAndHistoryRemainImmutable")
def pretty(v):return(json.dumps(v,sort_keys=True,indent=2)+"\n").encode()
def sha(v):return hashlib.sha256(v).hexdigest()
def git(*a,cwd=ROOT):return subprocess.run(["git",*a],cwd=cwd,check=True,capture_output=True,text=True).stdout.strip()
def authority():
 c=json.loads((COORD/"contexts/V23-P04-C22-attempt-1/BootstrapCardContextV1.json").read_bytes());f=json.loads((COORD/"contexts/V23-P04-C22-attempt-1/BootstrapPathFenceV1.json").read_bytes());p=f["priorFenceProof"]
 if (git("rev-parse","HEAD",cwd=COORD),git("rev-parse","HEAD^{tree}",cwd=COORD))!=(HEAD,CTREE):raise ValueError("C22 coordination differs")
 if (c["contextDigest"],f["fenceDigest"],c["ownerAuthorizedPathAllocationDigest"],c["provisionalPrerequisiteDigest"])!=(CONTEXT,FENCE,ALLOCATION,PREREQ):raise ValueError("C22 authority differs")
 if (len(c["existingPaths"]),len(c["newPaths"]),len(f["allowedCreateOrReplacePaths"]),p["authorizedOverlapCount"],p["unauthorizedOverlapCount"],p["s10ReservedOverlapCount"])!=(21,14,35,55,0,0):raise ValueError("C22 fence proof differs")
 return c,f
def sources():_,f=authority();return tuple(p for p in f["allowedCreateOrReplacePaths"] if p not in OWNED)
def rows():
 r=[{"path":p,"status":"SOURCE_PRESENT" if (ROOT/p).is_file() else "SOURCE_MISSING","sha256":sha((ROOT/p).read_bytes()) if (ROOT/p).is_file() else None} for p in sources()];return r,all(x["status"]=="SOURCE_PRESENT" for x in r)
def counts():
 _,f=authority();own=set(f["allowedCreateOrReplacePaths"]);parse=lambda x:{p.replace("\\","/") for p in x.splitlines() if p};x=parse(git("diff","--name-only",BASE,"HEAD"))|parse(git("diff","--name-only","HEAD"))|parse(git("diff","--cached","--name-only"))|parse(git("ls-files","--others","--exclude-standard"))|OWNED;return {"changedPathCount":len(x&own),"missingPathCount":sum(not(ROOT/p).is_file() for p in own-OWNED),"unownedChangedPathCount":len(x-own),"s10ReservationOverlapCount":len(own&set(f["activeS10ReservedPaths"]))}
def semantics(ready):
 if not ready:return
 b={p:(ROOT/p).read_text(encoding="utf-8",errors="replace") for p in sources()};t="\n".join(b.values());test=b.get("FieldEvidenceAppTests/V9_85RecurringRoundExperienceTests.swift","");ui=b.get("FieldEvidenceAppUITests/V23_P04_C22RecurringRoundExperienceUITests.swift","");need=("RecurringRoundExperience","Schedule","fixed","completionRelative","timeZone","horizon","due","reminder","offline","restore","replay","PersistentSchemaV53")
 if any(x not in t for x in need):raise ValueError("C22 source semantics missing")
 if any(x not in test for x in SELECTORS) or ui.count("XCTSkip")!=5:raise ValueError("C22 selector/UI skip mismatch")
 core=b.get("FieldEvidenceApp/Domain/Workflow/RecurringRoundExperienceContractsV1.swift","");coord=b.get("FieldEvidenceApp/Application/Workflow/RecurringRoundExperienceCoordinatorV1.swift","");life=b.get("FieldEvidenceApp/Infrastructure/Workflow/RecurringRoundExperienceLifecycleAdapterV1.swift","")
 exact=("canonicalDueTruthChanged: false","reminderStateIsNotCanonical","fixedCalendar","completionRelative")
 gate=("readiness.requireReady()","readiness.requestSHA256 == request.requestSHA256","readiness.workInstance == request.event.workInstance")
 reminder=("observedReminderEntries","desiredByID[$0] != observedByID[$0]","notificationIDsToRemove == expectedRemoval","reminderEntriesToApply == expectedApplyEntries","canonicalDueTruthChanged: false")
 integration=("RecurringRoundExperienceCoordinatorV1(","DeviceLocalScheduleReminderReconcilerV1(port:","RecurringRoundExperienceLifecycleAdapterV1(writer:","let unchanged = try await reconciler.reconcile(reminder)","let replaced = try await reconciler.reconcile(reminder)")
 if any(x not in core for x in exact+reminder) or any(x not in coord or x not in life for x in gate) or any(x not in test for x in integration):raise ValueError("C22 truth/readiness/reminder integration guard missing")
 if any(x in t for x in ("URLSession","http://","https://","reminderIsCanonicalTruth")):raise ValueError("C22 noncanonical/safety violation")
def documents():
 c,f=authority();r,ready=rows();n=counts();a={"cardID":CARD,"appBaseHead":BASE,"appBaseTree":BTREE,"coordinationHead":HEAD,"coordinationTree":CTREE,"sequence":SEQ,"contextDigest":CONTEXT,"pathFenceDigest":FENCE,"allocationDigest":ALLOCATION,"prerequisiteDigest":PREREQ,"finalHashesSealed":FINAL_HASHES_SEALED,"fencePathCount":35,"existingPathCount":21,"newPathCount":14,"authorizedOverlapCount":55,"s10OverlapCount":0};sem={"persistentSchema":"V53","activeModelCount":168,"incumbentScheduleRowCount":4,"newDurableRecordCount":0,"newDurableFamilies":[],"statusFlags":FLAGS};p={"sourceReady":ready,"sourceRows":r,"counts":n,"selectors":list(SELECTORS)};co={"schema":"V23P04C22RecurringRoundExperienceContractV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":sem,"sourceProjection":p,"testSelectors":list(SELECTORS),"statusFlags":FLAGS};ev={"schema":"V23P04C22RecurringRoundExperienceEvidenceReceiptV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"sourceProjection":p,"contractDigest":sha(pretty(co)),"statusFlags":FLAGS};br={"schema":"V23P04C22BrandImpactManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":sem,"sourceProjection":p,"uiAdoptionSkipped":True,"uiAcceptanceCredit":False,"statusFlags":FLAGS};m={"schema":"V23P04C22ToolingManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"finalHashesSealed":FINAL_HASHES_SEALED,"authority":a,"pathFence":f["allowedCreateOrReplacePaths"],"files":[{"path":p,"sha256":sha(pretty(v))} for p,v in ((CONTRACT,co),(EVIDENCE,ev),(BRAND,br))],"sources":r,"counts":n,"toolingPaths":[*SCRIPTS,SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST],"statusFlags":FLAGS};return {CONTRACT:co,EVIDENCE:ev,BRAND:br,MANIFEST:m}
