#!/usr/bin/env python3
"""Deterministic provisional V23-P04-C45 structured voice capture tooling."""
from __future__ import annotations
import hashlib,json,os,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];CARD="V23-P04-C45";ORDINAL=133;BASE="3ca602516919e0cac714c8bcc955efb1750d71d2";BASE_TREE="dcb3ab0903dee0e6f3615aef69135867213bb6fc";COORDINATION_HEAD="da8c218d6fbced6c3b52b8eb3393b477e3ef039b";COORDINATION_TREE="7d89015133a0a61cb9bf503537f5939aa9bd725b";SEQUENCE=580
ALLOCATION="48903c96743befdea2a67f0769a5ffe39eadff2d1d85cf5c1a29a42c0bce8114";PREREQ="fc5a6db5fa29bfe5d2311a7bb3a5166176bf85c5f02ccbd16080a5db402a3adf";CONTEXT="822a835e2a96f493cc9b9f2f179c4a1955b8978780c9e3f920e23a1afcf8aa39";FENCE="c6692ecaa2cdaab228039682390dc3777e2e35182aba3d5afc8edbedc942dd3b";TRANSITION="2c10eb943ed74267e0f30acd12ddf80a4136e2c989ab699e727bad0c87525fc9";LEDGER="4b82cb5b75fb8d6a0f8a66416acb8a6696233bbce3f5141fe6e672a18e9361a3";PROJECTION="f6316162513ee5e6e8eecec09b637c0b88f6dc09355bcb88e5ba93e1b6768ced"
EXISTING_PATHS=("FieldEvidenceApp/Info.plist",);NEW_PRODUCT_PATHS=("FieldEvidenceApp/Domain/VoiceCapture/StructuredVoiceCaptureContractsV1.swift","FieldEvidenceApp/Application/VoiceCapture/VoicePushToTalkCoordinatorV1.swift","FieldEvidenceApp/Infrastructure/VoiceCapture/OnDevicePushToTalkVoiceCaptureAdapterV1.swift","FieldEvidenceApp/Features/VoiceCapture/VoicePushToTalkCaptureView.swift","FieldEvidenceAppTests/V9_108StructuredVoiceCaptureTests.swift","FieldEvidenceAppTests/Fixtures/V23/VoiceCapture/V23P04C45StructuredVoiceCaptureCorpusV1.json","FieldEvidenceAppUITests/V23_P04_C45StructuredVoiceCaptureUITests.swift")
SCRIPTS=("Scripts/v23/p04_c45_contracts.py","Scripts/v23/generate_p04_c45_contracts.py","Scripts/v23/verify_p04_c45_contracts.py");SCHEMA="Scripts/v23/structured-voice-capture.schema.json";CONTRACT="docs/design/v23/tooling/V23P04C45StructuredVoiceCaptureContractV1.json";EVIDENCE="docs/design/v23/tooling/V23P04C45StructuredVoiceCaptureEvidenceReceiptV1.json";BRAND="docs/design/v23/tooling/V23P04C45BrandImpactManifestV1.json";MANIFEST="docs/design/v23/tooling/V23-P04-C45-tooling-manifest.json";TOOLING_PATHS=(*SCRIPTS,SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST);PATH_FENCE=(*EXISTING_PATHS,*NEW_PRODUCT_PATHS,*TOOLING_PATHS);FLAGS={k:False for k in("native","hosted","physicalDevice","adoption","acceptance","publication","release","nativeAcceptance","hostedAcceptance","adoptionEvidence","acceptanceCredit","releaseReadiness")};SELECTORS=("V23-P04-C45-G01","V23-P04-C45-A01","V23-P04-C45-H01","V23-P04-C45-I01","V23-P04-C45-R01")
POLICY={"concreteOnDevicePushToTalkAdapter":True,"captureAudioTranscriptConfidenceSessionCallbackState":"NONPERSISTENT","automaticWrite":False,"continuousListening":False,"wakeWord":False,"cloudOrNetworkFallback":False,"recordingArchive":False,"newMigration":False,"newModel":False,"newRoot":False,"newSchema":False,"newStore":False,"newWriter":False,"rootOrNetworkOrTelemetry":False,"recordWorkViewAdoption":False,"infoPlistSpeechRecognitionUsageDescriptionRequired":True,"acceptedOrEditedC56ReviewOnlyMayReachExistingUniversalDraftCheckpointAuthority":True,"contractOwners":["StructuredVoiceCaptureContextV1","VoiceScratchDispositionV1"]}
def pretty(v):return (json.dumps(v,sort_keys=True,indent=2)+"\n").encode()
def sha(v):return hashlib.sha256(v).hexdigest()
def git(*a,cwd=ROOT):return subprocess.run(["git",*a],cwd=cwd,check=True,capture_output=True,text=True).stdout.strip()
def read_json(p):
 p=Path(p);p=p if p.is_absolute() else ROOT/p
 return json.loads(p.read_text(encoding='utf-8'))
def authority():
 r=Path(os.environ.get("V23_P04_C45_COORDINATION_ROOT",ROOT.parent/"AssetRounds-v23-coordination"))
 if git("rev-parse","HEAD",cwd=r)!=COORDINATION_HEAD or git("show","-s","--format=%T",COORDINATION_HEAD,cwd=r)!=COORDINATION_TREE:raise ValueError("coordination pin drift")
 x=read_json(r/f"contexts/{CARD}-attempt-1/BootstrapCardContextV1.json");f=read_json(r/f"contexts/{CARD}-attempt-1/BootstrapPathFenceV1.json");a=read_json(r/f"receipts/{CARD}-owner-authorized-path-allocation-v1.json")
 if x.get("contextDigest")!=CONTEXT or x.get("provisionalPrerequisiteDigest")!=PREREQ or f.get("fenceDigest")!=FENCE or a.get("allocationDigest")!=ALLOCATION or tuple(f.get("allowedCreateOrReplacePaths",()))!=PATH_FENCE or tuple(a.get("exactOrderedPaths",()))!=PATH_FENCE or x.get("persistenceDecision")!=POLICY:raise ValueError("authority drift")
 return {"cardID":CARD,"ordinal":ORDINAL,"coordinationHead":COORDINATION_HEAD,"coordinationTree":COORDINATION_TREE,"appBaseHead":BASE,"appBaseTree":BASE_TREE,"sequence":SEQUENCE,"allocationDigest":ALLOCATION,"prerequisiteDigest":PREREQ,"contextDigest":CONTEXT,"fenceDigest":FENCE,"transitionDigest":TRANSITION,"ledgerDigest":LEDGER,"projectionDigest":PROJECTION,"pathFence":list(PATH_FENCE)}
def rows():
 ps=(*EXISTING_PATHS,*NEW_PRODUCT_PATHS);return ([{"path":p,"status":"SOURCE_PRESENT" if (ROOT/p).is_file() else "SOURCE_MISSING","sha256":sha((ROOT/p).read_bytes()) if (ROOT/p).is_file() else None} for p in ps],all((ROOT/p).is_file() for p in ps))
def documents():
 au=authority();rs,ready=rows();common={"schema":"V23P04C45StructuredVoiceCaptureToolingV1","cardID":CARD,"ordinal":ORDINAL,"authority":au,"sourceRows":rs,"sourceReady":ready,"flags":FLAGS,"finalHashesSealed":False,"policy":POLICY};sc=[{"id":x[-3:],"evidenceID":x} for x in SELECTORS]
 schema={"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","required":["schema","cardID","authority","flags","finalHashesSealed"],"properties":{"schema":{"const":"V23P04C45StructuredVoiceCaptureToolingV1"},"cardID":{"const":CARD},"flags":{"type":"object","additionalProperties":{"const":False}},"finalHashesSealed":{"const":False}},"additionalProperties":True}
 contract={**common,"contract":"StructuredVoiceCaptureContractV1","contractRefs":["StructuredVoiceCaptureContextV1","VoiceScratchDispositionV1"],"scenarioEvidenceIDs":list(SELECTORS),"requirements":{"pushToTalkExplicit":True,"maximumCaptureSeconds":60,"onDeviceNoNetwork":True,"transcriptSpansInformationalConfidence":True,"perFieldAcceptEditReject":True,"manualFallbackComplete":True,"callbackTargetRevisionLifecycleFences":True,"scratchCleanup":True,"nonpersistent":True,"c56ReviewOnlyDraftCheckpoint":True,"noNewPersistenceFamilies":True,"uiAdoptionDeferred":True},"scenarios":sc}
 evidence={**common,"receipt":"StructuredVoiceCaptureEvidenceReceiptV1","acceptanceCredit":False,"scenarios":sc};brand={**common,"manifest":"BrandImpactManifestV1","requiresAcceptedS10_6Reconciliation":True,"uiAdoptionSkipped":True,"uiAcceptanceCredit":False};manifest={**common,"manifest":"V23-P04-C45-tooling-manifest","pathFence":list(PATH_FENCE),"counts":{"fencePathCount":16,"existingPathCount":1,"newPathCount":15,"toolingPathCount":8,"s10ReservationOverlapCount":0,"missingPathCount":0,"unownedChangedPathCount":0}}
 return {SCHEMA:schema,CONTRACT:contract,EVIDENCE:evidence,BRAND:brand,MANIFEST:manifest}
