#!/usr/bin/env python3
"""Fail-closed provisional evidence contracts for V23-P04-C13."""
from __future__ import annotations
import hashlib,json,os,subprocess
from pathlib import Path
os.environ["PYTHONDONTWRITEBYTECODE"]="1"
ROOT=Path(__file__).resolve().parents[2];COORD=Path(r"C:\AssetRounds-v23-coordination");CARD="V23-P04-C13";BASE="fc2c9393c7b0c9856150fdeffbd454a7f3daa931";TREE="3a5521488c6b2735bdf96cc1f86a9ff41da73434";HEAD="1fc0e521f2fef034bfb863f4401f12e7f4c856dd";CTREE="28c575468545635890e816e450a96c43f75b8686";CONTEXT="d86ff8eb9d17b094648e57d56c26fa7631a5e4a07ce3b78f7a065b55fde61b08";FENCE="0a1f52808e0aa3ca2d6bdcae9253a3ca89d774323d655eaeefb153cefd3933d8";PREREQ="a63940691eed64772a867af18f49b34f4abe9464f7ea8b7364af52eb142598f3";TRANSITION="8a4a0079";LEDGER="165049cb";PROJECTION="e4a40201";FINAL_HASHES_SEALED=True
SCHEMA="Scripts/v23/entity-identity-resolution.schema.json";CONTRACT="docs/design/v23/tooling/V23P04C13EntityIdentityResolutionContractV1.json";EVIDENCE="docs/design/v23/tooling/V23P04C13EntityIdentityResolutionEvidenceReceiptV1.json";BRAND="docs/design/v23/tooling/V23P04C13BrandImpactManifestV1.json";MANIFEST="docs/design/v23/tooling/V23-P04-C13-tooling-manifest.json";SCRIPTS=("Scripts/v23/p04_c13_contracts.py","Scripts/v23/generate_p04_c13_contracts.py","Scripts/v23/verify_p04_c13_contracts.py");GENERATED=(SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST)
SOURCE=("FieldEvidenceApp/Domain/Identity/EntityIdentityResolutionContractsV1.swift","FieldEvidenceApp/Domain/Models/EntityIdentityResolutionPersistenceModelsV1.swift","FieldEvidenceApp/Application/Identity/EntityIdentityResolutionCoordinatorV1.swift","FieldEvidenceApp/Infrastructure/ImportExport/EntityIdentityResolutionLifecycleAdapterV1.swift","FieldEvidenceApp/Features/AssetImport/EntityIdentityResolutionView.swift","FieldEvidenceAppTests/V9_77EntityIdentityResolutionTests.swift","FieldEvidenceAppUITests/V23_P04_C13EntityIdentityResolutionUITests.swift","FieldEvidenceAppTests/Fixtures/V23/IdentityResolution/V23P04C13EntityIdentityResolutionCorpusV1.json")
SELECTORS=("testV23P04C13G01PreviewAliasAndConsolidationPlansPreserveCanonicalEvidenceAndHistory","testV23P04C13A01ExplicitSingleWriterAliasAndSuccessorReversalReceiptsUseExactRevision","testV23P04C13H01CrossWorkspaceReuseStalePlanHistoryRewriteAndAutomaticMutationFailClosed","testV23P04C13I01InterruptedEffectBeforeReceiptRecoveryNeverDuplicatesIdentityConsolidation","testV23P04C13R01RestoreReplayRebuildsAliasesConsolidationReceiptsAndEvidenceOnlyRelationships");LIFE=("MIGRATION","BACKUP","REPLACE_RESTORE","DELETE","ERASE","EXPORT","REPORT","SEARCH","REBUILD","JOURNAL","REPLAY");FLAGS={x:False for x in ("activation","native","hosted","adoption","acceptance","release","nativeAcceptance","hostedAcceptance","physicalEvidence","phase10PollingDuringParallelExecution")}
def pretty(v):return (json.dumps(v,sort_keys=True,indent=2)+"\n").encode()
def sha(v):return hashlib.sha256(v).hexdigest()
def run(*a,cwd=ROOT):return subprocess.run(["git",*a],cwd=cwd,check=True,capture_output=True,text=True).stdout.strip()
def load(p):return json.loads((COORD/p).read_bytes())
def authority():
 c=load("contexts/V23-P04-C13-attempt-1/BootstrapCardContextV1.json");f=load("contexts/V23-P04-C13-attempt-1/BootstrapPathFenceV1.json");t=load("transitions/000438-V23-P04-C13-attempt-1-NOT_STARTED-to-HYDRATING.json");l=load("state/BootstrapExecutionLedgerEnvelopeV1.json");p=load("projections/ActiveWorkSetProjectionV1.json")
 if (run("rev-parse","HEAD",cwd=COORD),run("rev-parse","HEAD^{tree}",cwd=COORD))!=(HEAD,CTREE):raise ValueError("C13 coordination authority differs")
 if c.get("contextDigest")!=CONTEXT or f.get("fenceDigest")!=FENCE or c.get("provisionalPrerequisiteDigest")!=PREREQ or not t.get("transitionDigest","").startswith(TRANSITION) or not l.get("ledgerDigest","").startswith(LEDGER) or not p.get("projectionDigest","").startswith(PROJECTION):raise ValueError("C13 hydration digest differs")
 proof=f.get("priorFenceProof",{});
 if c.get("repository")!={"appBaseHead":BASE,"appBaseTree":TREE} or len(c.get("existingPaths",()))!=56 or len(c.get("newPaths",()))!=16 or len(f.get("allowedCreateOrReplacePaths",()))!=72 or proof.get("unauthorizedOverlapCount")!=0 or set(f["allowedCreateOrReplacePaths"])&set(f["activeS10ReservedPaths"]):raise ValueError("C13 fence/S10 differs")
 return c,f
def rows():
 r=[]
 for x in SOURCE:
  p=ROOT/x;b=p.read_bytes() if p.is_file() else b"";r.append({"path":x,"status":"SOURCE_PRESENT" if p.is_file() else "SOURCE_MISSING","sha256":sha(b) if b else None})
 return r,all(x["status"]=="SOURCE_PRESENT" for x in r)
def counts():
 c,f=authority();own=set(f["allowedCreateOrReplacePaths"]);names=lambda *a:{x.replace("\\","/") for x in run(*a).splitlines() if x};changed=names("diff","--name-only",BASE,"HEAD")|names("diff","--name-only","HEAD")|names("diff","--name-only","--cached")|names("ls-files","--others","--exclude-standard")|set(SCRIPTS)|set(GENERATED);return {"changedPathCount":len(changed&own),"missingPathCount":sum(not (ROOT/x).is_file() for x in own-set(SCRIPTS)-set(GENERATED)),"unownedChangedPathCount":len(changed-own),"s10ReservationOverlapCount":len(own&set(f["activeS10ReservedPaths"]))}
def semantics(r,ready):
 if not ready:return
 _,f=authority();scope=[x for x in f["allowedCreateOrReplacePaths"] if x not in set(SCRIPTS)|set(GENERATED) and (ROOT/x).is_file()];alltext="\n".join((ROOT/x).read_text(encoding="utf-8") for x in scope);need=("EntityAliasLinkRowV1","EntityConsolidationReceiptRowV1","EntityIdentityResolutionMutationReceiptRowV1","PersistentSchemaV50","WorkspaceWriterV1","MutationJournal","backup","replaceRestore","erase","search","report","XCTSkip",*SELECTORS)
 miss=[x for x in need if x.lower() not in alltext.lower()]
 if miss:raise ValueError("C13 source semantic coverage missing:"+",".join(miss))
 exact=("EntityConsolidationInventoryAtomV1","EntityConsolidationInventoryFamilyManifestBasisV1","EntityConsolidationInventoryBuilderV1","EntityConsolidationInventoryFamilyV1","validateConsolidationHistory","root.revision == 1","reversedBySuccessor","commitEntityIdentityResolution","entityIdentityResolutionQuery","recoverBeforeWriterActivation","EntityIdentityResolutionBackupSnapshotV1","clone()","fork()","PersistentSchemaV50.models.count == 165","kindIDs.count == 447","laterTemporalOrigins.count == 366","durableKindIDs.count == 224","e76ee2ae7b72efb59f3cfbbf073d25f371239ec961803d800ec33758ecb57db8","CompatibilityCanonicalV1.encode(kindIDs)")
 miss=[x for x in exact if x not in alltext]
 if miss:raise ValueError("C13 shared inventory/writer/recovery/universe coverage missing:"+",".join(miss))
 if not all(x in alltext for x in ("relationship", "evidence", "content", "history", "tombstone", "mutationReceipt")):raise ValueError("C13 exact non-C13 package section coverage missing")
 package=(ROOT/"FieldEvidenceApp/Infrastructure/Backup/BackupCanonicalEncoderV1.swift").read_text(encoding="utf-8");restore=(ROOT/"FieldEvidenceApp/Infrastructure/Backup/BackupRestoreService.swift").read_text(encoding="utf-8")
 if not all(x in package for x in ("entityIdentityResolutionRegisteredSectionCount = 71", "fields.removeValue(forKey: \"entityIdentityResolution\")", "nonEntityIdentityResolutionHistory", "entityIdentityResolutionInventoryAtoms")):raise ValueError("C13 sole package exclusion/history stripping coverage missing")
 if not all(x in restore for x in ("EntityIdentityResolutionPackageResolverV1", "entityIdentityResolutionCommands", "EntityIdentityResolutionLifecycleAdapterV1")):raise ValueError("C13 package-scoped resolver/proof-map restore coverage missing")
def documents():
 c,f=authority();r,ready=rows();n=counts();a={"cardID":CARD,"appBaseHead":BASE,"appBaseTree":TREE,"coordinationHead":HEAD,"coordinationTree":CTREE,"sequence":438,"contextDigest":CONTEXT,"pathFenceDigest":FENCE,"prerequisiteDigest":PREREQ,"transitionDigestPrefix":TRANSITION,"ledgerDigestPrefix":LEDGER,"projectionDigestPrefix":PROJECTION,"finalHashesSealed":FINAL_HASHES_SEALED,"fencePathCount":72,"existingPathCount":56,"newPathCount":16,"s10OverlapCount":0};s={"sourceReady":ready,"sourceRows":r,"counts":n,"selectors":list(SELECTORS)};scope={"previewNonpersistent":True,"durableFamilies":["EntityAliasLinkRowV1","EntityConsolidationReceiptRowV1_WITH_SUCCESSOR_REVERSALS","EntityIdentityResolutionMutationReceiptRowV1"],"persistentSchema":"V50","actionCount":5,"oneCanonicalWriter":True,"lifecycleCoverage":list(LIFE),"statusFlags":FLAGS};con={"schema":"V23P04C13EntityIdentityResolutionContractV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":scope,"sourceProjection":s,"testSelectors":list(SELECTORS),"statusFlags":FLAGS};ev={"schema":"V23P04C13EntityIdentityResolutionEvidenceReceiptV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"sourceProjection":s,"contractDigest":sha(pretty(con)),"statusFlags":FLAGS};br={"schema":"V23P04C13BrandImpactManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":scope,"sourceProjection":s,"uiAdoptionSkipped":True,"uiAcceptanceCredit":False,"statusFlags":FLAGS};m={"schema":"V23P04C13ToolingManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"finalHashesSealed":FINAL_HASHES_SEALED,"authority":a,"pathFence":f["allowedCreateOrReplacePaths"],"files":[{"path":x,"sha256":sha(pretty(v))} for x,v in ((CONTRACT,con),(EVIDENCE,ev),(BRAND,br))],"counts":n,"toolingPaths":[*SCRIPTS,*GENERATED],"statusFlags":FLAGS};return {CONTRACT:con,EVIDENCE:ev,BRAND:br,MANIFEST:m}
