import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];CARD='V23-P06-C07';BASE='a3ab088f7b8a86fe952f3f1bc9064360fb1ac38e';TREE='dd3e1940d459c7c869b9dec5b617f523052f595a';OWNED=('Scripts/v23/p06_c07_contracts.py','Scripts/v23/generate_p06_c07_contracts.py','Scripts/v23/verify_p06_c07_contracts.py','Scripts/v23/advanced-scheduling-static-protocol.schema.json','FieldEvidenceAppTests/Fixtures/V23/P06/AdvancedScheduling/V23P06C07AdvancedSchedulingStaticCorpusV1.json','docs/design/v23/tooling/V23P06C07AdvancedSchedulingStaticPreparationContractV1.json','docs/design/v23/tooling/V23P06C07AdvancedSchedulingStaticPreparationEvidenceReceiptV1.json','docs/design/v23/tooling/V23P06C07BrandImpactManifestV1.json','docs/design/v23/tooling/V23-P06-C07-tooling-manifest.json');SC,CP,CT,EV,BR,MF=OWNED[3:];IDS=tuple('V23-P06-C07-'+x for x in('G01','A01','H01-DST','H01-TIMEZONE','H01-BLACKOUT','I01','R01'));FLAGS={x:False for x in('native','hosted','physical','implementation','acceptance','selector','release','phase','main','merge','adoption')}
def pretty(v):return(json.dumps(v,sort_keys=True,indent=2)+'\n').encode()
def sha(v):return hashlib.sha256(v).hexdigest()
def protocol():return {'schema':'V23P06C07AdvancedSchedulingStaticProtocolV1','cardID':CARD,'disposition':'PROVISIONAL_STATIC_PREPARATION_ONLY','notificationsScheduled':0,'calendarInvoked':False,'network':False,'canonicalWrites':0,'unboundedHorizon':False,'historyMutation':False,'assignmentInvoked':False,'scope':{'syntheticOnly':True,'externalActions':'NONE','customerData':False,'manualOfflineFallback':True},'evidenceIDs':list(IDS),'flags':FLAGS}
def corpus():return {'schema':'V23P06C07AdvancedSchedulingStaticCorpusV1','cardID':CARD,'disposition':'PROVISIONAL_STATIC_PREPARATION_ONLY','syntheticOnly':True,'realTerminalValidationResult':False,'cases':[{'id':IDS[0],'kind':'golden','expected':'STATIC_PROTOCOL_ONLY'},{'id':IDS[1],'kind':'accessibility','expected':'STATIC_PROTOCOL_ONLY'},{'id':IDS[2],'kind':'hostile','input':'DST gap or fold','expected':'REJECT_DECLARATIVE_ONLY'},{'id':IDS[3],'kind':'hostile','input':'timezone ambiguity','expected':'REJECT_DECLARATIVE_ONLY'},{'id':IDS[4],'kind':'hostile','input':'blackout or assignment mutation','expected':'REJECT_DECLARATIVE_ONLY'},{'id':IDS[5],'kind':'interruption','expected':'NO_RUNTIME_CLAIM'},{'id':IDS[6],'kind':'recovery','expected':'RECONCILE_OR_DISCARD'}]}
def schema():return {'$schema':'https://json-schema.org/draft/2020-12/schema','type':'object','additionalProperties':False,'required':['schema','cardID','disposition','notificationsScheduled','calendarInvoked','network','canonicalWrites','unboundedHorizon','historyMutation','assignmentInvoked','scope','evidenceIDs','flags'],'properties':{'schema':{'const':'V23P06C07AdvancedSchedulingStaticProtocolV1'},'cardID':{'const':CARD},'disposition':{'const':'PROVISIONAL_STATIC_PREPARATION_ONLY'},'notificationsScheduled':{'const':0},'calendarInvoked':{'const':False},'network':{'const':False},'canonicalWrites':{'const':0},'unboundedHorizon':{'const':False},'historyMutation':{'const':False},'assignmentInvoked':{'const':False}}}
def verify():
 if subprocess.run(['git','merge-base','--is-ancestor',BASE,'HEAD'],cwd=ROOT).returncode:raise ValueError('base not ancestor')
 if subprocess.check_output(['git','rev-parse',BASE+'^{tree}'],cwd=ROOT,text=True).strip()!=TREE:raise ValueError('base tree')
 v=json.loads((ROOT/'docs/design/v23/authority/OwnerParallelImplementationOverrideV5.json').read_bytes());r=json.loads((ROOT/'docs/design/v23/foundation/ActiveS10OwnershipReservationV1.json').read_bytes())
 if CARD not in v['provisionalStaticPreparationPlane']['eligibleCardsInCanonicalOrder'] or set(OWNED)&set(r['reservedPaths']):raise ValueError('authority/reservation')
def docs():
 verify();p=protocol();c=corpus();b={'schema':'V23P06C07StaticPreparationToolingV1','cardID':CARD,'appBaseHead':BASE,'appBaseTree':TREE,'disposition':'PROVISIONAL_STATIC_PREPARATION_ONLY','flags':FLAGS,'noProductionPath':True,'noRealStudy':True};d={SC:schema(),CP:c,CT:{**b,'contract':'AdvancedSchedulingStaticPreparationContractV1','protocol':p,'corpusPath':CP},EV:{**b,'receipt':'AdvancedSchedulingStaticPreparationEvidenceReceiptV1','result':'PASS_STATIC_PROVISIONAL','protocolSHA256':sha(pretty(p))},BR:{**b,'manifest':'AdvancedSchedulingBrandImpactManifestV1','impact':'NONE_SHIPPING'}};d[MF]={**b,'manifest':'V23P06C07ToolingManifestV1','pathFence':list(OWNED),'generatedFiles':[{'path':k,'sha256':sha(pretty(x))}for k,x in d.items()]};return d
def counts():
 s={x for x in subprocess.check_output(['git','diff','--name-only',BASE,'HEAD'],cwd=ROOT,text=True).splitlines()if x}
 for row in subprocess.check_output(['git','status','--porcelain=v1'],cwd=ROOT,text=True).splitlines():
  p=row[3:];t=ROOT/p
  if t.is_dir():s.update(x.relative_to(ROOT).as_posix()for x in t.rglob('*')if x.is_file())
  elif p:s.add(p)
 return {'changedPathCount':len(s&set(OWNED)),'missingOwnedPathCount':sum(not(ROOT/x).is_file()for x in OWNED),'unownedChangedPathCount':len(s-set(OWNED)),'s10ReservationOverlapCount':0,'fencePathCount':9}
