from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];COORD=Path(r"C:\AssetRounds-v23-coordination")
CARD="V23-P04-C21";BASE="e82534cd6894138bf15085e2dc08e736aefb2531";BTREE="a2265654e81a74be07557546c8edfdddb437e6f3";HEAD="1e0da68c4a9b59426d6aac7cd826e3a41be212d5";CTREE="316cd1cac446a99ea92fd4455d87b25a1f6baa4c";CONTEXT="cc589ec0eeeb0ff03dfd2ea66fae8e1d00d2f31c34534ac265f3d3660fa014c9";FENCE="8df3b5997616bd07730a61f86ef56674e92f48bd5bbfc2feb5e4f1bf162a7f11";ALLOCATION="e8edd9c02713566e0165c22899b00571da355bf9eb2a2ea3d375667fedc3fffd";PREREQ="43535f134b3a1e922466598452fc399aa4d7ca4dc5599962d365eaa7eda8326e";SEQ=472;FINAL_HASHES_SEALED=True
SCHEMA="Scripts/v23/scan-to-work.schema.json";CONTRACT="docs/design/v23/tooling/V23P04C21ScanToWorkContractV1.json";EVIDENCE="docs/design/v23/tooling/V23P04C21ScanToWorkEvidenceReceiptV1.json";BRAND="docs/design/v23/tooling/V23P04C21BrandImpactManifestV1.json";MANIFEST="docs/design/v23/tooling/V23-P04-C21-tooling-manifest.json";SCRIPTS=("Scripts/v23/p04_c21_contracts.py","Scripts/v23/generate_p04_c21_contracts.py","Scripts/v23/verify_p04_c21_contracts.py");OWNED=set((*SCRIPTS,SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST));SELECTORS=("testV23P04C21G01ScanResolutionAndExplicitStartPreserveTruth","testV23P04C21A01ManualLookupAndNextAssetParityRemainExplicit","testV23P04C21H01DamagedAmbiguousForeignAndStaleCodesFailClosed","testV23P04C21I01InterruptedCompleteAndNextRecoversIdempotently","testV23P04C21R01RestoreReplaySearchAndBatchSelectionPreserveRoutes");FLAGS={x:False for x in("activation","native","hosted","adoption","acceptance","release","publish","nativeAcceptance","hostedAcceptance","physicalEvidence","phase10PollingDuringParallelExecution")}
SELECTORS=("testV23P04C21G01ScanManualSearchResolveIdenticallyAndExplicitStartIsSoleMutationBoundary","testV23P04C21A01PermissionAndCameraDenialKeepCompleteManualFallbackAndBatchBounds","testV23P04C21H01AllClosedOutcomesAndHostilePreviewChangesFailClosed","testV23P04C21I01NextActionsPersistBeforeNavigationAndCanonicalStateReopens","testV23P04C21R01ProjectionPoseAccessibilityAndNonsemanticSetupRemainExact")
def pretty(v):return(json.dumps(v,sort_keys=True,indent=2)+"\n").encode()
def sha(b):return hashlib.sha256(b).hexdigest()
def git(*a,cwd=ROOT):return subprocess.run(["git",*a],cwd=cwd,check=True,capture_output=True,text=True).stdout.strip()
def authority():
 c=json.loads((COORD/"contexts/V23-P04-C21-attempt-1/BootstrapCardContextV1.json").read_bytes());f=json.loads((COORD/"contexts/V23-P04-C21-attempt-1/BootstrapPathFenceV1.json").read_bytes());p=f["priorFenceProof"]
 if (git("rev-parse","HEAD",cwd=COORD),git("rev-parse","HEAD^{tree}",cwd=COORD))!=(HEAD,CTREE):raise ValueError("C21 coordination differs")
 if (c["contextDigest"],f["fenceDigest"],c["ownerAuthorizedPathAllocationDigest"],c["provisionalPrerequisiteDigest"])!=(CONTEXT,FENCE,ALLOCATION,PREREQ):raise ValueError("C21 authority differs")
 if (len(c["existingPaths"]),len(c["newPaths"]),len(f["allowedCreateOrReplacePaths"]),p["authorizedOverlapCount"],p["unauthorizedOverlapCount"],p["s10ReservedOverlapCount"])!=(27,14,41,38,0,0):raise ValueError("C21 fence proof differs")
 return c,f
def sources():_,f=authority();return tuple(p for p in f["allowedCreateOrReplacePaths"] if p not in OWNED)
def rows():
 r=[{"path":p,"status":"SOURCE_PRESENT" if (ROOT/p).is_file() else "SOURCE_MISSING","sha256":sha((ROOT/p).read_bytes()) if (ROOT/p).is_file() else None} for p in sources()];return r,all(x["status"]=="SOURCE_PRESENT" for x in r)
def counts():
 _,f=authority();own=set(f["allowedCreateOrReplacePaths"]);parse=lambda x:{p.replace("\\","/") for p in x.splitlines() if p};x=parse(git("diff","--name-only",BASE,"HEAD"))|parse(git("diff","--name-only","HEAD"))|parse(git("diff","--cached","--name-only"))|parse(git("ls-files","--others","--exclude-standard"))|OWNED;return {"changedPathCount":len(x&own),"missingPathCount":sum(not(ROOT/p).is_file() for p in own-OWNED),"unownedChangedPathCount":len(x-own),"s10ReservationOverlapCount":len(own&set(f["activeS10ReservedPaths"]))}
def semantics(ready):
 if not ready:return
 b={p:(ROOT/p).read_text(encoding="utf-8",errors="replace") for p in sources()};t="\n".join(b.values());test=b.get("FieldEvidenceAppTests/V9_84ScanToWorkTests.swift","");ui=b.get("FieldEvidenceAppUITests/V23_P04_C21ScanToWorkUITests.swift","");need=("ScanToWorkFlowV1","AssetPreviewStateV1","NextAssetProjectionV1","InstallationScanEntryReceiptV1","ManualLookupFallbackV1","camera","READY","DUPLICATE_IN_SELECTION","ALREADY_IN_ROUND","AMBIGUOUS","FOREIGN","RETIRED_OR_REPLACED","NOT_FOUND","NOT_OFFLINE_READY","STALE")
 if any(x not in t for x in need):raise ValueError("C21 source semantics missing")
 if any(x not in test for x in SELECTORS):raise ValueError("C21 selectors missing")
 contract=b.get("FieldEvidenceApp/Domain/Workflow/ScanToWorkContractsV1.swift","");corpus=b.get("FieldEvidenceAppTests/Fixtures/V23/Rounds/V23P04C21ScanToWorkCorpusV1.json","")
 exact=("validateCurrent(binding: ScanToWorkAssetBindingV1, policy: ScanToWorkStartPolicyV1) async throws","RepetitiveCaptureRoundSemanticV1.matches","Set(readyAssetIDs).count == readyAssetIDs.count","nonsemantic device configuration identifiers")
 if any(x not in contract for x in exact) or "ScanToWorkResolutionOutcomeV1.allCases" not in test or corpus.count('"outcome"')!=9:raise ValueError("C21 exact start/batch/outcome corpus contract missing")
 if ui.count("XCTSkip")!=5:raise ValueError("C21 UI skip count differs")
 if any(x in t for x in ("URLSession","http://","https://","scanAutoStart","scanAutoWrite","secondWriter")):raise ValueError("C21 safety prohibition violated")
def documents():
 c,f=authority();r,ready=rows();n=counts();a={"cardID":CARD,"appBaseHead":BASE,"appBaseTree":BTREE,"coordinationHead":HEAD,"coordinationTree":CTREE,"sequence":SEQ,"contextDigest":CONTEXT,"pathFenceDigest":FENCE,"allocationDigest":ALLOCATION,"prerequisiteDigest":PREREQ,"finalHashesSealed":FINAL_HASHES_SEALED,"fencePathCount":41,"existingPathCount":27,"newPathCount":14,"authorizedOverlapCount":38,"s10OverlapCount":0};sem={"persistentSchema":"V53","activeModelCount":168,"newDurableRecordCount":0,"newDurableFamilies":[],"derivedStates":["ScanToWorkFlowV1","AssetPreviewStateV1","NextAssetProjectionV1"],"statusFlags":FLAGS};pr={"sourceReady":ready,"sourceRows":r,"counts":n,"selectors":list(SELECTORS)};co={"schema":"V23P04C21ScanToWorkContractV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":sem,"sourceProjection":pr,"testSelectors":list(SELECTORS),"statusFlags":FLAGS};ev={"schema":"V23P04C21ScanToWorkEvidenceReceiptV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"sourceProjection":pr,"contractDigest":sha(pretty(co)),"statusFlags":FLAGS};br={"schema":"V23P04C21BrandImpactManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":sem,"sourceProjection":pr,"uiAdoptionSkipped":True,"uiAcceptanceCredit":False,"statusFlags":FLAGS};m={"schema":"V23P04C21ToolingManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"finalHashesSealed":FINAL_HASHES_SEALED,"authority":a,"pathFence":f["allowedCreateOrReplacePaths"],"files":[{"path":p,"sha256":sha(pretty(v))} for p,v in ((CONTRACT,co),(EVIDENCE,ev),(BRAND,br))],"sources":r,"counts":n,"toolingPaths":[*SCRIPTS,SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST],"statusFlags":FLAGS};return {CONTRACT:co,EVIDENCE:ev,BRAND:br,MANIFEST:m}
