#!/usr/bin/env python3
"""Render the deterministic V23-P01-C03 JSON contract set."""
from __future__ import annotations

import argparse
from pathlib import Path

from p01_c03_contracts import MANIFEST, manifest, outputs, pretty


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="repository root (defaults to the parent of Scripts/v23)",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--apply",
        action="store_true",
        help="write generated artifacts (the default)",
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help="verify generated bytes without writing",
    )
    args = parser.parse_args()
    root = args.root.resolve()

    for relative, value in outputs(root).items():
        path = root / relative
        data = pretty(value)
        if args.check:
            if not path.is_file() or path.read_bytes() != data:
                print(f"FAIL differs: {relative}")
                return 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)

    value = manifest(root)
    path = root / MANIFEST
    data = pretty(value)
    if args.check:
        if not path.is_file() or path.read_bytes() != data:
            print(f"FAIL differs: {MANIFEST}")
            return 1
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    print(f"PASS V23-P01-C03 generated=5 check={args.check}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
