from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];COORD=Path(r'C:\AssetRounds-v23-coordination');CARD='V23-P04-C25';BASE='e65c2b807fe6242b383c24947d454c099c0f8265';BTREE='206747a8ff6df2c7d80a24f58e2152619c1d75f3';HEAD='ca9ae5ca93ffef22fec6fd826cbe77e2e388a184';CTREE='799c5a59ab77c1d9de2e36483b0df17fb45a1555';CONTEXT='bc29003d4579ed299a7ad9e33ba117b4a1ec6a97096f1beee66cf1d4b534d530';FENCE='c9a284d729f286c7e29ac7ab44c85fb8807e73b66271d5c35ab4bd82258ab5f2';ALLOCATION='96fcee5ae389b2340b007f005829555f208731ef494987c761dc7012826dd155';PREREQ='bbadd9802cf66f26eed3f34fc70687bd9565da976e4b43c311fa5f541df90e8b';SEQ=489;FINAL_HASHES_SEALED=True
SCHEMA='Scripts/v23/temporal-evidence-capture.schema.json';CONTRACT='docs/design/v23/tooling/V23P04C25TemporalEvidenceCaptureContractV1.json';EVIDENCE='docs/design/v23/tooling/V23P04C25TemporalEvidenceCaptureEvidenceReceiptV1.json';BRAND='docs/design/v23/tooling/V23P04C25BrandImpactManifestV1.json';MANIFEST='docs/design/v23/tooling/V23-P04-C25-tooling-manifest.json';SCRIPTS=('Scripts/v23/p04_c25_contracts.py','Scripts/v23/generate_p04_c25_contracts.py','Scripts/v23/verify_p04_c25_contracts.py');OWNED=set((*SCRIPTS,SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST));SELECTORS=('testV23P04C25G01BoundedOfflineAudioVideoCaptureReviewAndUse','testV23P04C25A01IndependentPermissionsBoundsDiskAndManualFallback','testV23P04C25H01HostileCodecResolutionDurationSizeCountAndProhibitedProcessing','testV23P04C25I01InterruptionRetakeDeleteAndScratchCleanupRecovery','testV23P04C25R01ReportPosterMetadataLinkAndLifecycleRecovery');FLAGS={x:False for x in('physicalDevice','native','hosted','activation','adoption','acceptance','publication','release')}
def pretty(v):return(json.dumps(v,sort_keys=True,indent=2)+'\n').encode()
def sha(v):return hashlib.sha256(v).hexdigest()
def git(*x,cwd=ROOT):return subprocess.run(['git',*x],cwd=cwd,check=True,capture_output=True,text=True).stdout.strip()
def authority():
 p=COORD/'contexts/V23-P04-C25-attempt-1';c=json.loads((p/'BootstrapCardContextV1.json').read_bytes());f=json.loads((p/'BootstrapPathFenceV1.json').read_bytes());q=f['priorFenceProof']
 if(git('rev-parse','HEAD',cwd=COORD),git('rev-parse','HEAD^{tree}',cwd=COORD))!=(HEAD,CTREE):raise ValueError('C25 coordination differs')
 if(c['contextDigest'],f['fenceDigest'],c['ownerAuthorizedPathAllocationDigest'],c['provisionalPrerequisiteDigest'])!=(CONTEXT,FENCE,ALLOCATION,PREREQ):raise ValueError('C25 authority differs')
 if(len(c['existingPaths']),len(c['newPaths']),len(f['allowedCreateOrReplacePaths']),q['fenceCount'],q['priorOwnedPathCount'],q['authorizedOverlapCount'],q['unauthorizedOverlapCount'],q['s10ReservedOverlapCount'])!=(14,14,28,4,369,34,0,0):raise ValueError('C25 fence proof differs')
 return c,f
def sources():_,f=authority();return tuple(x for x in f['allowedCreateOrReplacePaths']if x not in OWNED)
def rows():
 r=[{'path':x,'status':'SOURCE_PRESENT'if(ROOT/x).is_file()else'SOURCE_MISSING','sha256':sha((ROOT/x).read_bytes())if(ROOT/x).is_file()else None}for x in sources()];return r,all(x['status']=='SOURCE_PRESENT'for x in r)
def counts():
 _,f=authority();o=set(f['allowedCreateOrReplacePaths']);q=lambda x:{a.replace('\\','/')for a in x.splitlines()if a};x=q(git('diff','--name-only',BASE,'HEAD'))|q(git('diff','--name-only','HEAD'))|q(git('diff','--cached','--name-only'))|q(git('ls-files','--others','--exclude-standard'))|OWNED;return{'changedPathCount':len(x&o),'missingPathCount':sum(not(ROOT/x).is_file()for x in o-OWNED),'unownedChangedPathCount':len(x-o),'s10ReservationOverlapCount':len(o&set(f['activeS10ReservedPaths']))}
def semantics(ready):
 if not ready:return
 b={x:(ROOT/x).read_text(encoding='utf-8',errors='replace')for x in sources()};registry=ROOT/'FieldEvidenceApp/Infrastructure/Persistence/PersistentSchemas.swift'
 if not registry.is_file():raise ValueError('C25 persistent schema registry unavailable')
 t='\n'.join((*b.values(),registry.read_text(encoding='utf-8',errors='replace')));test=b.get('FieldEvidenceAppTests/V9_88TemporalEvidenceCaptureTests.swift','');ui=b.get('FieldEvidenceAppUITests/V23_P04_C25TemporalEvidenceCaptureUITests.swift','')
 need=('TemporalEvidenceCapture','AppAccess','foreground','permission','review','anchor','derivative','report','V53','audio','video','scratch','recovery','Use')
 if any(x not in t for x in need):raise ValueError('C25 source semantics missing')
 if any(x not in test for x in SELECTORS)or ui.count('XCTSkip')!=5:raise ValueError('C25 selectors/UI skip mismatch')
 core=b['FieldEvidenceApp/Domain/Content/TemporalEvidenceCaptureContractsV1.swift'];coordinator=b['FieldEvidenceApp/Application/Content/TemporalEvidenceCaptureCoordinatorV1.swift'];lifecycle=b['FieldEvidenceApp/Infrastructure/Media/TemporalEvidenceCaptureLifecycleAdapterV1.swift']
 if any(x not in core for x in('static let persistentRowsAdded = 0','static let ownsWriter = false','static let foregroundOnly = true','static let networkAllowed = false')):raise ValueError('C25 nonpersistent/offline declaration missing')
 if any(x not in coordinator for x in('requireTemporalAudioCaptureAccess()','requireTemporalVideoCaptureAccess()','TemporalEvidenceCaptureAppAccessBoundaryV1.validateAudio(permit)','TemporalEvidenceCaptureAppAccessBoundaryV1.validateVideo(permit)','return try await canonical.use(acceptance)')):raise ValueError('C25 access or explicit Use boundary missing')
 if any(x not in coordinator for x in('CapabilityScratchLeaseRequestV1(','result.bytes, named: relativeName, lease: lease','scratch.readPendingReview(','lease: reviewState.scratchBinding.lease','scratch.recoverPendingReview(')):raise ValueError('C25 lease-bound scratch write/read/recovery missing')
 if any(x not in lifecycle for x in('InjectedTemporalEvidenceCaptureRuntimeV1','guard await isForeground()','guard await protectedDataAvailable()','static let shippingUIInstalled = false')):raise ValueError('C25 lifecycle safety boundary missing')
 if any(x not in b['FieldEvidenceApp/Info.plist'] for x in('NSCameraUsageDescription','NSMicrophoneUsageDescription')) or any(x not in b['FieldEvidenceApp/InfoPlist.xcstrings'] for x in('NSCameraUsageDescription','NSMicrophoneUsageDescription')):raise ValueError('C25 camera/microphone privacy declaration missing')
 # Only executable C25 capture sources are forbidden-API scanned.  Plist XML
 # declarations legitimately contain W3C URLs and must not be treated as network use.
 if any(x in '\n'.join((core,coordinator,lifecycle)) for x in('URLSession','http://','https://','backgroundUpload','parallelStore')):raise ValueError('C25 prohibited capture behavior')
def documents():
 _,f=authority();r,ready=rows();n=counts();a={'cardID':CARD,'appBaseHead':BASE,'appBaseTree':BTREE,'coordinationHead':HEAD,'coordinationTree':CTREE,'sequence':SEQ,'contextDigest':CONTEXT,'pathFenceDigest':FENCE,'allocationDigest':ALLOCATION,'prerequisiteDigest':PREREQ,'finalHashesSealed':FINAL_HASHES_SEALED,'fencePathCount':28,'existingPathCount':14,'newPathCount':14,'priorFenceCount':4,'priorOwnedPathCount':369,'authorizedOverlapCount':34,'s10OverlapCount':0,'featurePolicySHA256':'98a205edc22421ec4a4f2a5494628f4f40be7117a95cdd3cc94e2d6eab7c98ef'};s={'persistentSchema':'V53','activeModelCount':168,'newDurableRecordCount':0,'newDurableFamilies':[],'reusedTemporalFamilies':2,'statusFlags':FLAGS};p={'sourceReady':ready,'sourceRows':r,'counts':n,'selectors':list(SELECTORS)};co={'schema':'V23P04C25TemporalEvidenceCaptureContractV1','schemaVersion':1,'cardID':CARD,'provisional':True,'authority':a,'semantics':s,'sourceProjection':p,'testSelectors':list(SELECTORS),'statusFlags':FLAGS};ev={'schema':'V23P04C25TemporalEvidenceCaptureEvidenceReceiptV1','schemaVersion':1,'cardID':CARD,'provisional':True,'authority':a,'sourceProjection':p,'contractDigest':sha(pretty(co)),'statusFlags':FLAGS};br={'schema':'V23P04C25BrandImpactManifestV1','schemaVersion':1,'cardID':CARD,'provisional':True,'authority':a,'semantics':s,'sourceProjection':p,'uiAdoptionSkipped':True,'uiAcceptanceCredit':False,'statusFlags':FLAGS};m={'schema':'V23P04C25ToolingManifestV1','schemaVersion':1,'cardID':CARD,'provisional':True,'finalHashesSealed':FINAL_HASHES_SEALED,'authority':a,'pathFence':f['allowedCreateOrReplacePaths'],'files':[{'path':k,'sha256':sha(pretty(v))}for k,v in((CONTRACT,co),(EVIDENCE,ev),(BRAND,br))],'sources':r,'counts':n,'toolingPaths':[ *SCRIPTS,SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST],'statusFlags':FLAGS};return{CONTRACT:co,EVIDENCE:ev,BRAND:br,MANIFEST:m}
