#!/usr/bin/env python3
"""Fail-closed provisional static contracts for V23-P04-C15."""
from __future__ import annotations
import hashlib,json,os,subprocess
from pathlib import Path
os.environ["PYTHONDONTWRITEBYTECODE"]="1";ROOT=Path(__file__).resolve().parents[2];COORD=Path(r"C:\AssetRounds-v23-coordination");CARD="V23-P04-C15";BASE="1a5d77d1452eb18c5d2a2a8b053c9be94963ee3f";TREE="235ed3880c9d0616d608727dbd4a363c6f6c3782";HEAD="b8207934334b3f0dd576281661eb4d6a64e6ead6";CTREE="3879b78d32ad2f11a7d852eb3f2bf6b2a623dfdc";ALLOCATION="6564c548106ef9b93413143550ba127faed1c8a2456f61253d55b34a05481293";PREREQ="805d21169a0542ae5cbadd1eeaa488832e09b05cbb12e50afc81c539f645aa8e";CONTEXT="8c91ab54613fdb048eb004a0c1bb986ea205c40b61d2b9cbc2092ef383acf089";FENCE="0bab4884aaee9d5653a6beb4f5ef9ec41ded105a7f77677a64e57eb542f0be0b";TRANSITION="e26208f597f1043ef0483181ea5af2ce0411fee37ab20c0f11b594c7cd226bc0";LEDGER="77f98e1a787bfc9509f6ddf257d90780fe868a5d8e286b10d7cc6ccb538cae58";PROJECTION="cb251ffab26f2787f59e705ca5411aeec32a9646b4b8c0127d3b81766bafe623";FINAL_HASHES_SEALED=True
SCHEMA="Scripts/v23/discovery-truth-catalog.schema.json";CONTRACT="docs/design/v23/tooling/V23P04C15DiscoveryTruthContractV1.json";EVIDENCE="docs/design/v23/tooling/V23P04C15DiscoveryTruthEvidenceReceiptV1.json";BRAND="docs/design/v23/tooling/V23P04C15BrandImpactManifestV1.json";MANIFEST="docs/design/v23/tooling/V23-P04-C15-tooling-manifest.json";SCRIPTS=("Scripts/v23/p04_c15_contracts.py","Scripts/v23/generate_p04_c15_contracts.py","Scripts/v23/verify_p04_c15_contracts.py");GENERATED=(SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST)
SOURCE=("docs/product/discovery/DiscoveryTruthCatalogV1.json","docs/product/discovery/V23P04C15BrandedStaticProofManifestV1.json","docs/product/discovery/V23P04C15SyntheticSampleManifestV1.json","docs/product/discovery/V23P04C15AggregateAcquisitionEvidenceV1.json","docs/accessibility/V23P04C15StaticProofAccessibilityManifestV1.json","docs/privacy/V23P01C02OwnedFilePrivacyInventoryV1.json","FieldEvidenceAppTests/Fixtures/V21/DiscoveryTruth/V23P04C15DiscoveryTruthCorpusV1.json")
PREFLIGHT="Scripts/release-preflight.sh";TEST="FieldEvidenceAppTests/S9_1ReleasePreflightTests.swift";SELECTORS=("testV23P04C15G01DiscoveryTruthCatalogValidatesLocalizedLimitsAndClosedArtifactSet","testV23P04C15A01CategoriesAndAppTagsRemainSeparateTypedSets","testV23P04C15H01HostileOpaqueStaleRealDataAndDraftPublishedInputsFailClosed","testV23P04C15I01InterruptedDeclarationGenerationLeavesZeroPartialOrCompleteArtifactSet","testV23P04C15R01DeletingAndRebuildingDeclarationArtifactsLeavesProductAndPublicStateUnchanged");FLAGS={x:False for x in("activation","native","hosted","adoption","acceptance","release","publish","nativeAcceptance","hostedAcceptance","physicalEvidence","phase10PollingDuringParallelExecution")}
def pretty(v):return(json.dumps(v,sort_keys=True,indent=2)+"\n").encode()
def sha(v):return hashlib.sha256(v).hexdigest()
def run(*a,cwd=ROOT):return subprocess.run(["git",*a],cwd=cwd,check=True,capture_output=True,text=True).stdout.strip()
def load(x):return json.loads((COORD/x).read_bytes())
def authority():
 c=load("contexts/V23-P04-C15-attempt-1/BootstrapCardContextV1.json");f=load("contexts/V23-P04-C15-attempt-1/BootstrapPathFenceV1.json");a=load("receipts/V23-P04-C15-owner-authorized-path-allocation-v1.json");t=load("transitions/000448-V23-P04-C15-attempt-1-NOT_STARTED-to-HYDRATING.json");l=load("state/BootstrapExecutionLedgerEnvelopeV1.json");p=load("projections/ActiveWorkSetProjectionV1.json");proof=f["priorFenceProof"]
 if(run("rev-parse","HEAD",cwd=COORD),run("rev-parse","HEAD^{tree}",cwd=COORD))!=(HEAD,CTREE):raise ValueError("C15 coordination authority differs")
 if c.get("contextDigest")!=CONTEXT or f.get("fenceDigest")!=FENCE or a.get("allocationDigest")!=ALLOCATION or t.get("transitionDigest")!=TRANSITION or l.get("ledgerDigest")!=LEDGER or p.get("projectionDigest")!=PROJECTION or c.get("provisionalPrerequisiteDigest")!=PREREQ or c.get("repository")!={"appBaseHead":BASE,"appBaseTree":TREE}:raise ValueError("C15 hydration authority differs")
 if len(c["existingPaths"])!=3 or len(c["newPaths"])!=14 or len(f["allowedCreateOrReplacePaths"])!=17 or proof["fenceCount"]!=4 or proof["priorOwnedPathCount"]!=179 or proof["authorizedOverlapCount"]!=1 or proof["unauthorizedOverlapCount"]!=0 or set(f["allowedCreateOrReplacePaths"])&set(f["activeS10ReservedPaths"]):raise ValueError("C15 fence proof differs")
 return c,f
def rows():
 r=[]
 for x in SOURCE:
  p=ROOT/x;b=p.read_bytes()if p.is_file()else b"";r.append({"path":x,"status":"SOURCE_PRESENT"if b else"SOURCE_MISSING","sha256":sha(b)if b else None})
 return r,all(x["status"]=="SOURCE_PRESENT"for x in r)
def counts():
 _,f=authority();own=set(f["allowedCreateOrReplacePaths"]);n=lambda *a:{x.replace("\\","/")for x in run(*a).splitlines()if x};changed=n("diff","--name-only",BASE,"HEAD")|n("diff","--name-only","HEAD")|n("ls-files","--others","--exclude-standard")|set(SCRIPTS)|set(GENERATED);return{"changedPathCount":len(changed&own),"missingPathCount":sum(not(ROOT/x).is_file()for x in own-set(SCRIPTS)-set(GENERATED)),"unownedChangedPathCount":len(changed-own),"s10ReservationOverlapCount":len(own&set(f["activeS10ReservedPaths"]))}
def semantics(rows,ready):
 if not ready:return
 values=[json.loads((ROOT/x).read_bytes())for x in SOURCE];text="\n".join(json.dumps(v,sort_keys=True)for v in values);need=("DISCOVERY_TRUTH_CATALOG_V1","DECLARATION_ONLY","DISABLED_OR_DEFERRED","capability","evidence","brand","candidate","approval","expiry","supersession","locale","category","tag","watermark")
 miss=[x for x in need if x.lower()not in text.lower()]
 if miss:raise ValueError("C15 catalog semantics missing:"+",".join(miss))
 if any(x.lower()in text.lower()for x in("real customer data","network provider","deployment receipt","publish approved")):raise ValueError("C15 public/provider/real-data prohibition violated")
 fixture=values[-1];catalog=fixture.get("catalog",{});sem=fixture.get("semantics",{});acq=fixture.get("acquisition",{});publication=fixture.get("publication",{});watermark="SYNTHETIC EXAMPLE — NO CUSTOMER DATA"
 expected_selectors=list(SELECTORS);observed=[x.get("selector")for x in fixture.get("selectors",[]) if isinstance(x,dict)]
 if fixture.get("schema")!="V23P04C15DiscoveryTruthCorpusV1" or fixture.get("cardID")!=CARD or fixture.get("testOnly")is not True or fixture.get("synthetic")is not True or fixture.get("containsCustomerData")is not False or fixture.get("containsSecrets")is not False:raise ValueError("C15 corpus identity/synthetic boundary differs")
 if sem!={"persistentContractMode":"DECLARATION_ONLY","persistentContractSchema":"DISCOVERY_TRUTH_CATALOG_V1","publicationEligible":False,"sixProofKinds":["CAPABILITY","EVIDENCE","BRAND","CANDIDATE","APPROVAL","EXPIRY_SUPERSESSION"],"aggregateNoJoinKey":True,"aggregateNoRealData":True,"uiAdoption":"POST_S10_6_SKIP_NO_CREDIT"}:raise ValueError("C15 declaration-only semantics differ")
 if observed!=expected_selectors or len(set(observed))!=5:raise ValueError("C15 selector fixture differs")
 locales=catalog.get("locales",[])
 if [x.get("locale")for x in locales] != ["en-US","fr-FR"] or any(not isinstance(x,dict)or not x.get("name")or not x.get("subtitle")or len(x.get("name",""))>30 or len(x.get("subtitle",""))>30 or len(x.get("keywords","").encode())>100 or len(x.get("promotionalText",""))>170 or len(x.get("description",""))>4000 for x in locales):raise ValueError("C15 locale limits differ")
 if catalog.get("categories")!=["BUSINESS","PRODUCTIVITY"] or catalog.get("appTags")!=["EVIDENCE","FIELD_WORK"] or not set(catalog["categories"]).isdisjoint(catalog["appTags"]):raise ValueError("C15 category/tag separation differs")
 if any(x.get("status")!="DRAFT_ONLY"or x.get("publishable")is not False or x.get("containsCustomerData")is not False or watermark not in x.get("watermarks",[]) for x in fixture.get("artifacts",[]))or len(fixture.get("artifacts",[]))!=6:raise ValueError("C15 artifact draft/watermark boundary differs")
 if acq.get("provider")!="NONE"or acq.get("networkAccess")is not False or acq.get("containsRealData")is not False or any(acq.get(x)!=[]for x in("stableJoinKeys","personIdentifiers","deviceIdentifiers","workspaceIdentifiers","entityIdentifiers"))or acq.get("watermark")!=watermark:raise ValueError("C15 aggregate no-join/no-real-data boundary differs")
 if publication!={"status":"DRAFT_ONLY","publishable":False,"upload":False,"signing":False,"deployment":False,"networkAccess":False,"provider":"NONE"}:raise ValueError("C15 publication boundary differs")
 if any(v!=0 for v in fixture.get("productState",{}).values())or any(v!=0 for v in fixture.get("publicState",{}).values())or any(v is not False for v in fixture.get("statusFlags",{}).values())or fixture.get("uiAdoptionSkipped")is not True:raise ValueError("C15 zero-state/activation boundary differs")
 preflight=(ROOT/PREFLIGHT).read_text(encoding="utf-8");tests=(ROOT/TEST).read_text(encoding="utf-8")
 if any(x not in preflight or x not in tests for x in expected_selectors)or "V23P04C15DiscoveryTruthCorpusV1.json"not in preflight or "stableJoinKeys"not in preflight or "provider"not in preflight or "validateC15"not in tests:raise ValueError("C15 release-preflight/test coverage differs")
 validate_source_contracts()
def _closed(value,keys,label):
 if not isinstance(value,dict)or set(value)!=set(keys):raise ValueError("C15 closed declaration mismatch:"+label)
def _false(value,keys,label):
 _closed(value,keys,label)
 if any(value[x]is not False for x in keys):raise ValueError("C15 forbidden activation state:"+label)
def validate_source_contracts(values=None):
 """Strict, reusable validation of C15's five declaration documents and corpus."""
 values={x:json.loads((ROOT/x).read_bytes())for x in SOURCE}if values is None else values;catalog=values[SOURCE[0]];brand=values[SOURCE[1]];synthetic=values[SOURCE[2]];aggregate=values[SOURCE[3]];accessibility=values[SOURCE[4]];privacy=values[SOURCE[5]];fixture=values[SOURCE[6]];flags=set(FLAGS)
 catalog_keys={"acceptanceCredit","adoptionEnabled","aggregateAcquisitionEvidence","appStoreCategories","brandBaselineReference","brandRevisionReference","brandedStaticProof","candidateReference","cardID","claims","curatedAppTags","deploymentEnabled","evidenceBindings","locales","metadataLimits","networkProviderEnabled","optionalOwnerApprovalReference","persistentContractMode","persistentContractSchema","provisional","publicationEligible","publish","releaseCredit","schema","schemaVersion","screenshots","signingEnabled","status","statusFlags","syntheticSamples","upload"};_closed(catalog,catalog_keys,"catalog")
 if (catalog["schema"],catalog["schemaVersion"],catalog["cardID"],catalog["persistentContractMode"],catalog["persistentContractSchema"],catalog["status"],catalog["provisional"],catalog["publicationEligible"]) != ("DiscoveryTruthCatalogV1",1,CARD,"DECLARATION_ONLY","DISCOVERY_TRUTH_CATALOG_V1","DISABLED_OR_DEFERRED",True,False):raise ValueError("C15 catalog identity/enum differs")
 _false({x:catalog[x] for x in ("acceptanceCredit","adoptionEnabled","deploymentEnabled","networkProviderEnabled","publish","releaseCredit","signingEnabled","upload")},("acceptanceCredit","adoptionEnabled","deploymentEnabled","networkProviderEnabled","publish","releaseCredit","signingEnabled","upload"),"catalog")
 if catalog["optionalOwnerApprovalReference"]is not None or catalog["statusFlags"]!={x:False for x in flags}:raise ValueError("C15 catalog approval/flags differ")
 candidate=catalog["candidateReference"];_closed(candidate,("acceptedS10Candidate","head","status","tree"),"candidate");
 if candidate!={"acceptedS10Candidate":False,"head":BASE,"status":"PROVISIONAL_NONCANDIDATE","tree":TREE}:raise ValueError("C15 candidate binding differs")
 baseline=catalog["brandBaselineReference"];revision=catalog["brandRevisionReference"]
 _closed(baseline,("authorityPath","authoritySHA256","disposition"),"baseline reference");_closed(revision,("authorityPath","authoritySHA256","disposition","ownerApprovalReference"),"revision reference")
 if baseline!=brand["brandBaselineReference"]or revision!=brand["brandRevisionReference"]or baseline.get("disposition")!="INHERITED_BASELINE_REFERENCE_ONLY"or revision.get("disposition")!="DISABLED_OR_DEFERRED"or revision.get("ownerApprovalReference")is not None:raise ValueError("C15 exact baseline/deferred brand binding differs")
 refs=(("brandedStaticProof",SOURCE[1]),("syntheticSamples",SOURCE[2]),("aggregateAcquisitionEvidence",SOURCE[3]))
 for key,path in refs:
  ref=catalog[key];_closed(ref,("path","sha256"),"catalog."+key)
  if ref["path"]!=path or ref["sha256"]!=sha((ROOT/path).read_bytes()):raise ValueError("C15 declaration hash binding differs:"+key)
 _closed(brand["accessibilityManifest"],("path","sha256"),"accessibility reference");_closed(brand["syntheticSampleManifest"],("path","sha256"),"synthetic reference")
 if brand["accessibilityManifest"].get("path")!=SOURCE[4]or brand["accessibilityManifest"].get("sha256")!=sha((ROOT/SOURCE[4]).read_bytes())or brand["syntheticSampleManifest"]!=catalog["syntheticSamples"]:raise ValueError("C15 accessibility/synthetic binding differs")
 _closed(catalog["metadataLimits"],("descriptionMaximumCharacters","keywordsMaximumUTF8Bytes","nameMaximumCharacters","promotionalTextMaximumCharacters","subtitleMaximumCharacters"),"metadata limits")
 if catalog["metadataLimits"]!={"descriptionMaximumCharacters":4000,"keywordsMaximumUTF8Bytes":100,"nameMaximumCharacters":30,"promotionalTextMaximumCharacters":170,"subtitleMaximumCharacters":30}:raise ValueError("C15 metadata limits differ")
 _closed(catalog["appStoreCategories"],("primary","schema","secondary","status"),"categories");_closed(catalog["curatedAppTags"],("schema","status","tags"),"tags")
 if catalog["appStoreCategories"]!={"primary":"BUSINESS","schema":"AppStoreCategorySetV1","secondary":"PRODUCTIVITY","status":"DISABLED_OR_DEFERRED"}or catalog["curatedAppTags"]!={"schema":"CuratedAppTagSetV1","status":"DISABLED_OR_DEFERRED","tags":["EVIDENCE","FIELD_WORK"]}:raise ValueError("C15 typed category/tag differs")
 for locale in catalog["locales"]:
  _closed(locale,("description","keywords","locale","name","promotionalText","publishEligibility","status","subtitle"),"catalog locale")
  if locale["locale"]not in("en-US","fr-FR")or locale["status"]!="DISABLED_OR_DEFERRED"or locale["publishEligibility"]is not False:raise ValueError("C15 catalog locale boundary differs")
 for shot in catalog["screenshots"]:_closed(shot,("proofID","proofKind","referenceType"),"catalog screenshot")
 proof_kinds=["ACCESSIBILITY","HOME","PRIVACY","SAMPLE_REPORT","SUPPORT","USE_CASE"];samples=synthetic.get("samples")or[];proofs=brand.get("proofs")or[];shots=catalog.get("screenshots")or[]
 if len(samples)!=6 or len(proofs)!=6 or [x.get("proofKind")for x in samples]!=proof_kinds or [x.get("proofKind")for x in proofs]!=proof_kinds or [x.get("proofKind")for x in shots]!=proof_kinds:raise ValueError("C15 exact six noncandidate proof parity differs")
 watermark="SYNTHETIC EXAMPLE — NO CUSTOMER DATA";practice="PRACTICE — NOT FOR FIELD USE"
 for sample in samples:
  _closed(sample,("containsCustomerData","contentSHA256","displayWatermarks","practiceWorkspace","proofKind","sampleID"),"synthetic sample")
  if sample["containsCustomerData"]is not False or watermark not in sample["displayWatermarks"] or (sample["practiceWorkspace"]and practice not in sample["displayWatermarks"]):raise ValueError("C15 synthetic watermark/data boundary differs")
 for proof in proofs:
  _closed(proof,("finalScreenshot","proofID","proofKind","shotListReference","syntheticSampleID","uploadReady","wireframeOnly"),"brand proof")
  if proof["finalScreenshot"]is not False or proof["uploadReady"]is not False or proof["wireframeOnly"]is not True:raise ValueError("C15 noncandidate proof state differs")
 claim=catalog["claims"]
 if len(claim)!=1:raise ValueError("C15 claim count differs")
 claim=claim[0];_closed(claim,("brandSHA256","capabilitySHA256","claimEvidenceSHA256","claimID","expiresAt","optionalOwnerApprovalReference","privacySHA256","publishEligibility","receiptSHA256","status","supersededByClaimDigest","supersedesClaimDigest","syntheticSHA256"),"claim")
 constants={"capabilitySHA256":"98a205edc22421ec4a4f2a5494628f4f40be7117a95cdd3cc94e2d6eab7c98ef","receiptSHA256":"a2be42fc9708cb3e6c648750ff4eeef66150451393ba660aed1f186ae50b88fc","privacySHA256":sha((ROOT/SOURCE[5]).read_bytes())}
 if any(claim[k]!=v for k,v in constants.items())or claim["brandSHA256"]!=catalog["brandedStaticProof"]["sha256"]or claim["claimEvidenceSHA256"]!=catalog["aggregateAcquisitionEvidence"]["sha256"]or claim["syntheticSHA256"]!=catalog["syntheticSamples"]["sha256"]or claim["status"]!="DISABLED_OR_DEFERRED"or claim["publishEligibility"]is not False or any(claim[k]is not None for k in("expiresAt","optionalOwnerApprovalReference","supersededByClaimDigest","supersedesClaimDigest")):raise ValueError("C15 claim receipt/privacy/approval/expiry binding differs")
 bindings=catalog["evidenceBindings"];kinds=["CAPABILITY","EVIDENCE","BRAND","CANDIDATE","APPROVAL","EXPIRY_SUPERSESSION"]
 if len(bindings)!=6 or [x.get("kind")for x in bindings]!=kinds:raise ValueError("C15 evidence binding kinds differ")
 for index,row in enumerate(bindings):
  _closed(row,("kind","sha256"),"evidence binding")if index<4 else _closed(row,("disposition","kind","sha256"),"deferred evidence binding")
 candidate_digest="47ec42f675c92b994e301bf4218a53223a91b8ad49a0a0b4fa9478e0ab1dc8e3"
 if bindings[0]["sha256"]!=constants["capabilitySHA256"] or bindings[1]["sha256"]!=catalog["aggregateAcquisitionEvidence"]["sha256"] or bindings[2]["sha256"]!=catalog["brandedStaticProof"]["sha256"] or bindings[3]["sha256"]!=candidate_digest or any(x["sha256"]is not None or x["disposition"]!="DISABLED_OR_DEFERRED" for x in bindings[4:]):raise ValueError("C15 six proof binding/approval/candidate parity differs")
 for value,name,identity in ((brand,"brand","V23P04C15BrandedStaticProofManifestV1"),(synthetic,"synthetic","V23P04C15SyntheticSampleManifestV1"),(aggregate,"aggregate","V23P04C15AggregateAcquisitionEvidenceV1"),(accessibility,"accessibility","V23P04C15StaticProofAccessibilityManifestV1")):
  if value.get("schema")!=identity or value.get("schemaVersion")!=1 or value.get("cardID")!=CARD or value.get("publicationEligible")is not False or value.get("publish")is not False or value.get("releaseCredit")is not False or value.get("upload")is not False:raise ValueError("C15 declaration identity/publication differs:"+name)
 _closed(brand,{"accessibilityManifest","acceptanceCredit","adoptionEnabled","brandBaselineReference","brandRevisionReference","candidateReference","cardID","finalScreenshotBytes","networkProviderEnabled","proofs","provisional","publicationEligible","publish","releaseCredit","schema","schemaVersion","status","statusFlags","syntheticSampleManifest","upload"},"brand root")
 _closed(synthetic,{"acceptanceCredit","adoptionEnabled","cardID","containsCustomerData","containsRealUserData","defaultWatermark","networkProviderEnabled","practiceWatermark","provisional","publicationEligible","publish","releaseCredit","samples","schema","schemaVersion","status","statusFlags","upload"},"synthetic root")
 _closed(aggregate,{"acceptanceCredit","acquisitionEvidence","adoptionEnabled","analyticsEnabled","attributionEnabled","cardID","containsClaimsOfAcquisitionPerformance","containsCustomerData","containsDeviceJoinKey","containsEntityJoinKey","containsFabricatedEvidence","containsPersonJoinKey","containsRatings","containsReviews","containsUserClaims","containsUserRecords","containsWorkspaceJoinKey","deviceJoinKeyEnabled","externalProviderEnabled","networkAccessEnabled","paidAcquisitionEnabled","provisional","publicationEligible","publish","releaseCredit","schema","schemaVersion","sessionReplayEnabled","stableJoinKeyEnabled","status","statusFlags","upload"},"aggregate root")
 _closed(accessibility,{"acceptanceCredit","accessibilityCoverage","adoptionEnabled","approvals","artifactKinds","cardID","containsRealCustomerData","containsStableJoinKeys","hiddenClaims","networkProviderAnalyticsAttributionOrSessionReplay","optionalApprovalsEnabled","publicationEligible","publish","releaseCredit","sampleAndPracticeWatermarksRequired","schema","schemaVersion","status","upload"},"accessibility root")
 if brand["candidateReference"]!=candidate or brand["statusFlags"]!={x:False for x in flags} or any(brand[k]is not False for k in("acceptanceCredit","adoptionEnabled","finalScreenshotBytes","networkProviderEnabled","publish","releaseCredit","upload")) or any(synthetic[k]is not False for k in("acceptanceCredit","adoptionEnabled","containsCustomerData","containsRealUserData","networkProviderEnabled","publish","releaseCredit","upload")) or synthetic["statusFlags"]!={x:False for x in flags}:raise ValueError("C15 brand/synthetic root state differs")
 _closed(aggregate["acquisitionEvidence"],("aggregateOnly","observedArtifactCount","observedLocaleCount","observedProofKindCount","source"),"acquisition evidence")
 if aggregate.get("acquisitionEvidence",{}).get("aggregateOnly")is not True or any(aggregate.get(k)is not False for k in("analyticsEnabled","attributionEnabled","externalProviderEnabled","networkAccessEnabled","stableJoinKeyEnabled","containsCustomerData","containsPersonJoinKey","containsDeviceJoinKey","containsWorkspaceJoinKey","containsEntityJoinKey")) or accessibility.get("containsStableJoinKeys")is not False or accessibility.get("containsRealCustomerData")is not False or accessibility.get("networkProviderAnalyticsAttributionOrSessionReplay")is not False:raise ValueError("C15 aggregate/accessibility identifier/network boundary differs")
 policy=privacy.get("c15DeclarationOnlyPolicy",{});_closed(policy,("backup","canonicalPersistence","containsRealCustomerContactLocationNoteOrEvidenceData","delete","export","hasStablePersonDeviceWorkspaceOrEntityJoinKeys","networkOrProviderAccess","productOrReleaseCredit","report","retention","telemetryAnalyticsAttributionOrSessionReplay"),"privacy C15 policy")
 _closed(privacy,{"acceptanceCredit","acceptanceEnabled","adoptionEnabled","appProtectionAttributeClaimForExternalDestination","artifactDigest","authority","cardID","c15DeclarationOnlyArtifacts","c15DeclarationOnlyPolicy","diagnosticsAllowlist","externalExportSource","externalProviderHandoff","forbiddenSecretSurfaces","handlingClassDeclarations","hostedDispatchRan","keychainUsage","lifecycle","nativeCompileRan","ownedPathMatrix","phase10PollingDuringParallelExecution","physicalEvidenceComplete","physicalLockedState","releaseCredit","releaseReady","reportRecoverySource","requiresAcceptedS10_6Reconciliation","schema","schemaVersion","secretInventory","sourceBindingDigest","systemDiscoveryProjection"},"privacy root")
 if privacy.get("schema")!="V23P01C02OwnedFilePrivacyInventoryV1"or privacy.get("schemaVersion")!=1 or privacy.get("cardID")!="V23-P01-C02" or any(policy[k]is not False for k in("canonicalPersistence","containsRealCustomerContactLocationNoteOrEvidenceData","hasStablePersonDeviceWorkspaceOrEntityJoinKeys","networkOrProviderAccess","productOrReleaseCredit","telemetryAnalyticsAttributionOrSessionReplay")):raise ValueError("C15 bound privacy inventory declaration-only boundary differs")
 privacy_paths={x.get("path")for x in privacy.get("c15DeclarationOnlyArtifacts",[])if isinstance(x,dict)}
 for row in privacy.get("c15DeclarationOnlyArtifacts",[]):_closed(row,("classification","id","path"),"privacy artifact row")
 expected_privacy_paths=set(SOURCE[:5]+(SOURCE[6],)+SCRIPTS+GENERATED)
 if privacy_paths!=expected_privacy_paths or len(privacy.get("c15DeclarationOnlyArtifacts",[]))!=14:raise ValueError("C15 privacy inventory artifact binding differs")
 if fixture.get("semantics",{}).get("sixProofKinds")!=["CAPABILITY","EVIDENCE","BRAND","CANDIDATE","APPROVAL","EXPIRY_SUPERSESSION"] or fixture.get("acquisition",{}).get("provider")!="NONE" or fixture.get("publication",{}).get("provider")!="NONE":raise ValueError("C15 fixture declaration parity differs")
 return {"sourceReady":True,"sourceCount":7,"proofCount":6,"sourceDigests":{p:sha((ROOT/p).read_bytes()) for p in SOURCE}}
def source_contracts_self_test():
 import copy
 original={x:json.loads((ROOT/x).read_bytes())for x in SOURCE};tests=(
  ("brand-root-opaque",lambda v:v[SOURCE[1]].__setitem__("opaque",True)),
  ("synthetic-sample-opaque",lambda v:v[SOURCE[2]]["samples"][0].__setitem__("opaque",True)),
  ("aggregate-evidence-opaque",lambda v:v[SOURCE[3]]["acquisitionEvidence"].__setitem__("opaque",True)),
  ("accessibility-root-opaque",lambda v:v[SOURCE[4]].__setitem__("opaque",True)),
  ("privacy-artifact-opaque",lambda v:v[SOURCE[5]]["c15DeclarationOnlyArtifacts"][0].__setitem__("opaque",True)),
  ("catalog-ref-opaque",lambda v:v[SOURCE[0]]["brandedStaticProof"].__setitem__("opaque",True)),
  ("candidate-digest-wrong",lambda v:v[SOURCE[0]]["evidenceBindings"][3].__setitem__("sha256","0"*64)),
  ("approval-extra-key",lambda v:v[SOURCE[0]]["evidenceBindings"][4].__setitem__("opaque",True)),
 )
 rejected=[]
 for name,mutate in tests:
  value=copy.deepcopy(original);mutate(value)
  try:validate_source_contracts(value)
  except ValueError:rejected.append(name)
  else:raise ValueError("C15 hostile source mutation accepted:"+name)
 return {"sourceContractsSelfTest":"PASS","rejected":rejected,"count":len(rejected)}
def documents():
 c,f=authority();r,ready=rows();
 if ready:validate_source_contracts()
 n=counts();hostile=source_contracts_self_test();interruption={"protocol":"MANIFEST_LAST_ATOMIC_REPLACE","noWorktreeMutation":True,"rows":[{"boundary":"BEFORE_ACCEPTED_ARTIFACT_WRITE","acceptedSetCount":1},{"boundary":"AFTER_ARTIFACT_WRITE_BEFORE_RECEIPT","acceptedSetCount":0},{"boundary":"AFTER_RECEIPT_BEFORE_RETURN","acceptedSetCount":1}]};a={"cardID":CARD,"appBaseHead":BASE,"appBaseTree":TREE,"coordinationHead":HEAD,"coordinationTree":CTREE,"sequence":448,"allocationDigest":ALLOCATION,"prerequisiteDigest":PREREQ,"contextDigest":CONTEXT,"pathFenceDigest":FENCE,"transitionDigest":TRANSITION,"ledgerDigest":LEDGER,"projectionDigest":PROJECTION,"finalHashesSealed":FINAL_HASHES_SEALED,"fencePathCount":17,"existingPathCount":3,"newPathCount":14,"priorFenceCount":4,"priorOwnedPathCount":179,"authorizedOverlapCount":1,"s10OverlapCount":0};s={"sourceReady":ready,"sourceRows":r,"counts":n,"selectors":list(SELECTORS)};scope={"persistentContractMode":"DECLARATION_ONLY","persistentContractSchema":"DISCOVERY_TRUTH_CATALOG_V1","publicationEligible":False,"sixProofKinds":["CAPABILITY","EVIDENCE","BRAND","CANDIDATE","APPROVAL","EXPIRY_SUPERSESSION"],"aggregateNoJoinKey":True,"aggregateNoRealData":True,"uiAdoption":"POST_S10_6_SKIP_NO_CREDIT","statusFlags":FLAGS};co={"schema":"V23P04C15DiscoveryTruthContractV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":scope,"sourceProjection":s,"testSelectors":list(SELECTORS),"statusFlags":FLAGS};ev={"schema":"V23P04C15DiscoveryTruthEvidenceReceiptV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"sourceProjection":s,"contractDigest":sha(pretty(co)),"sourceContractsHostileSelfTest":hostile,"interruptionAcceptanceEvidence":interruption,"statusFlags":FLAGS};br={"schema":"V23P04C15BrandImpactManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":scope,"sourceProjection":s,"uiAdoptionSkipped":True,"uiAcceptanceCredit":False,"statusFlags":FLAGS};m={"schema":"V23P04C15ToolingManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"finalHashesSealed":FINAL_HASHES_SEALED,"authority":a,"pathFence":f["allowedCreateOrReplacePaths"],"files":[{"path":x,"sha256":sha(pretty(v))}for x,v in((CONTRACT,co),(EVIDENCE,ev),(BRAND,br))],"sources":r,"counts":n,"toolingPaths":[*SCRIPTS,*GENERATED],"statusFlags":FLAGS};return{CONTRACT:co,EVIDENCE:ev,BRAND:br,MANIFEST:m}
def validate_documents(d):
 roots={CONTRACT:{"schema","schemaVersion","cardID","provisional","authority","semantics","sourceProjection","testSelectors","statusFlags"},EVIDENCE:{"schema","schemaVersion","cardID","provisional","authority","sourceProjection","contractDigest","sourceContractsHostileSelfTest","interruptionAcceptanceEvidence","statusFlags"},BRAND:{"schema","schemaVersion","cardID","provisional","authority","semantics","sourceProjection","uiAdoptionSkipped","uiAcceptanceCredit","statusFlags"},MANIFEST:{"schema","schemaVersion","cardID","provisional","finalHashesSealed","authority","pathFence","files","sources","counts","toolingPaths","statusFlags"}}
 schemas={CONTRACT:"V23P04C15DiscoveryTruthContractV1",EVIDENCE:"V23P04C15DiscoveryTruthEvidenceReceiptV1",BRAND:"V23P04C15BrandImpactManifestV1",MANIFEST:"V23P04C15ToolingManifestV1"}
 for path,value in d.items():
  if set(value)!=roots[path]or value.get("schema")!=schemas[path]or value.get("schemaVersion")!=1 or value.get("cardID")!=CARD or value.get("provisional")is not True or value.get("statusFlags")!=FLAGS:raise ValueError("C15 generated closed schema mismatch:"+path)
  a=value["authority"]
  if a.get("finalHashesSealed")is not True or a.get("fencePathCount")!=17 or a.get("existingPathCount")!=3 or a.get("newPathCount")!=14 or a.get("priorFenceCount")!=4 or a.get("priorOwnedPathCount")!=179 or a.get("authorizedOverlapCount")!=1 or a.get("s10OverlapCount")!=0:raise ValueError("C15 generated authority schema mismatch:"+path)
  projection=value.get("sourceProjection",value)
  if projection.get("selectors",list(SELECTORS))!=list(SELECTORS)or projection.get("counts",{}).get("unownedChangedPathCount")!=0:raise ValueError("C15 generated source schema mismatch:"+path)
 if d[CONTRACT]["testSelectors"]!=list(SELECTORS)or d[EVIDENCE]["contractDigest"]!=sha(pretty(d[CONTRACT]))or d[EVIDENCE]["sourceContractsHostileSelfTest"]!={"sourceContractsSelfTest":"PASS","rejected":["brand-root-opaque","synthetic-sample-opaque","aggregate-evidence-opaque","accessibility-root-opaque","privacy-artifact-opaque","catalog-ref-opaque","candidate-digest-wrong","approval-extra-key"],"count":8}or d[EVIDENCE]["interruptionAcceptanceEvidence"]!={"protocol":"MANIFEST_LAST_ATOMIC_REPLACE","noWorktreeMutation":True,"rows":[{"boundary":"BEFORE_ACCEPTED_ARTIFACT_WRITE","acceptedSetCount":1},{"boundary":"AFTER_ARTIFACT_WRITE_BEFORE_RECEIPT","acceptedSetCount":0},{"boundary":"AFTER_RECEIPT_BEFORE_RETURN","acceptedSetCount":1}]}or d[BRAND]["uiAdoptionSkipped"]is not True or d[BRAND]["uiAcceptanceCredit"]is not False or d[MANIFEST]["finalHashesSealed"]is not True or len(d[MANIFEST]["pathFence"])!=17 or len(d[MANIFEST]["files"])!=3 or len(d[MANIFEST]["sources"])!=7 or len(d[MANIFEST]["toolingPaths"])!=8:raise ValueError("C15 generated artifact schema mismatch")
