#!/usr/bin/env python3
"""Generate or check C42's deterministic schema and evidence artifacts."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))

import p04_c42_contracts as contracts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--apply", action="store_true", help="write the five generated JSON artifacts")
    group.add_argument("--check", action="store_true", help="check generated bytes without writing")
    args = parser.parse_args()
    try:
        outputs = contracts.documents()
    except Exception as error:
        print(f"C42 generator FAIL_STATIC_AUTHORITY {error}")
        return 1
    stale: list[str] = []
    for relative, document in outputs.items():
        target = ROOT / relative
        expected = contracts.pretty(document)
        if args.apply:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(expected)
        elif not target.is_file() or target.read_bytes() != expected:
            stale.append(relative)
    if stale:
        print("C42 generator check FAIL_STATIC_STALE " + ",".join(stale))
        return 1
    mode = "apply" if args.apply else "check"
    print(f"C42 generator {mode} PASS_STATIC_PROVISIONAL generated={len(outputs)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
