#!/usr/bin/env python3
"""Deterministic static contract, corpus, and evidence builders for V23-P03-C23.

This module records the sealed hydration facts for version-bound offline field
reference packs and work-session bindings. It is deliberately static:
native, hosted, adoption, acceptance, release, network, cloud, provider,
account, and Phase 10 claims remain false.
"""

from __future__ import annotations

import base64
import hashlib
import json
import subprocess
import zlib
from pathlib import Path
from typing import Any


CARD = "V23-P03-C23"
SCHEMA_VERSION = 1
REGISTER_ORDINAL = 60
TITLE = "Version-bound offline field reference packs and work-session bindings"
BASE_HEAD = "d0485977644a71e49b8d4b898bb527e0353bd81e"
BASE_TREE = "2fc990ee64f9da6e84b07fddc2abed036f679630"
COORDINATION_HEAD = "ee142f506d73e1bc4eef867d7011ce01716508d3"
COORDINATION_TREE = "acd2843eb5b64c153ae0f0e73c08aa8691ab6637"
COORDINATION_LEDGER_DIGEST = "ded15a341e7be79b2912b3deb58e58b4b6e9092a02c746acff1b5da074ba3efb"
COORDINATION_PROJECTION_DIGEST = "6acbc941bc3cda1488563a1b797624c5045c7b1b998aa3de2d2f450c517fd63c"
COORDINATION_CAS_SEQUENCE = 254
HYDRATION_TRANSITION_SEQUENCE = 254
HYDRATION_TRANSITION_DIGEST = "9b312d501adbfeaead1228df1e5baddb0344425c470247b2699a842a0dfe64d4"
CONTEXT_DIGEST = "3d67e08191ae9959f6d0f75b41c5c392163379fc790ff33780119b0be7c452ad"
FENCE_DIGEST = "b7b755e156b364560a6945a190d6035f3e711192cc89fd1424d7e8221d9a73bb"
PREREQUISITE_DIGEST = "973aa767d3a4149394faeb4c5125b061c10d42657f6853723ec3519f13d4b263"
FROZEN_S10_RESERVATION_DIGEST = "274b8e3d9eff11805f5abfec7e1b8a702b91751056f0952e432388c35fe6657a"

REGISTER_SECTION_SHA256 = "3047a8c7f8baeca754bdf635811796eacc6400f91521f40c6294343c66f702d5"
REGISTER_SECTION_UTF8_LENGTH = 44217
REGISTER_ROW_SHA256 = "de392c84fead7b39794ddab044b69ce1b53295dcdb18d4703ce481d8431ed641"
REGISTER_ROW_UTF8_LENGTH = 266
DOSSIER_SHA256 = "6f68f10d6c142de595031c7bade878c3b2d4b3a70893967e71bc6f1c1f0c59cd"
DOSSIER_UTF8_LENGTH = 7097
INHERITED_V21_BLOCK_SHA256 = "571ed6c59abd0a1f3fcad898df9d0b1b73ced87327e2dbc8af6ec65179e76e8b"
INHERITED_V21_BLOCK_UTF8_LENGTH = 8138

SCHEMA_PATH = "Scripts/v23/field-reference-pack.schema.json"
CONTRACT_PATH = "docs/design/v23/tooling/V23P03C23FieldReferencePackContractV1.json"
EVIDENCE_PATH = "docs/design/v23/tooling/V23P03C23FieldReferencePackEvidenceReceiptV1.json"
BRAND_PATH = "docs/design/v23/tooling/V23P03C23BrandImpactManifestV1.json"
MANIFEST_PATH = "docs/design/v23/tooling/V23-P03-C23-tooling-manifest.json"
SCRIPT_PATHS = (
    "Scripts/v23/p03_c23_contracts.py",
    "Scripts/v23/generate_p03_c23_contracts.py",
    "Scripts/v23/verify_p03_c23_contracts.py",
)
GENERATED_PATHS = (SCHEMA_PATH, CONTRACT_PATH, EVIDENCE_PATH, BRAND_PATH, MANIFEST_PATH)
TOOL_PATHS = SCRIPT_PATHS + GENERATED_PATHS


# Exact order is copied from corrected C23 BootstrapPathFenceV1.
EXISTING_PATHS = tuple(["FieldEvidenceApp/Domain/Packs/InspectionPackageContractsV2.swift","FieldEvidenceApp/Domain/Packs/InspectionPackageRegistryV2.swift","FieldEvidenceApp/Domain/Content/ContentReferenceContractsV1.swift","FieldEvidenceApp/Domain/Content/ContentLocatorManifestContractsV1.swift","FieldEvidenceApp/Domain/Content/ContentProvenanceContractsV1.swift","FieldEvidenceApp/Domain/Content/PrivacyTransformContractsV1.swift","FieldEvidenceApp/Domain/Workflow/WorkflowContracts.swift","FieldEvidenceApp/Domain/Workflow/WorkRule.swift","FieldEvidenceApp/Domain/Workflow/ReportSnapshotV1.swift","FieldEvidenceApp/Domain/Workflow/DeletionIntentV1.swift","FieldEvidenceApp/Domain/Workflow/EraseIntentV1.swift","FieldEvidenceApp/Domain/Workflow/WholeSignDeletionRule.swift","FieldEvidenceApp/Infrastructure/Packs/BundledInspectionPackageRegistryV2.swift","FieldEvidenceApp/Infrastructure/Packs/PackageSandboxRunnerV1.swift","FieldEvidenceApp/Infrastructure/Packs/PackageEvolutionLifecycleAdapterV1.swift","FieldEvidenceApp/Infrastructure/Content/LocalContentStoreContractsV1.swift","FieldEvidenceApp/Infrastructure/Content/ContentIntegrityV1.swift","FieldEvidenceApp/Infrastructure/Content/ContentContractRegistryV1.swift","FieldEvidenceApp/Infrastructure/Media/EvidenceBundleStore.swift","FieldEvidenceApp/Features/CheckRunner/CheckRunnerContracts.swift","FieldEvidenceApp/Features/CheckRunner/CheckRunnerCoordinator.swift","FieldEvidenceAppTests/S1PackTokenTests.swift","FieldEvidenceAppTests/S3_1DraftSchemaTests.swift","FieldEvidenceAppTests/S4_3ReportDeliveryTests.swift","FieldEvidenceAppTests/S6_1DeletionGraphTests.swift","FieldEvidenceAppTests/S8_1SecondPackZeroForkTests.swift","FieldEvidenceAppTests/V9_11PackRegistryTests.swift","FieldEvidenceAppTests/V9_15ContentReferenceProvenanceTests.swift","FieldEvidenceAppTests/V9_18PackLifecycleIntegrationTests.swift","FieldEvidenceAppTests/V9_22LocalizationAccessibilityTests.swift","FieldEvidenceAppTests/V9_25AuthorityCriterionDerivationTests.swift","FieldEvidenceAppTests/V9_29WorkPacketManifestTests.swift","FieldEvidenceAppTests/V9_36RecoverabilityVerificationTests.swift","FieldEvidenceAppTests/V9_LocationHierarchyPlacementCompositionTests.swift","FieldEvidenceApp/Infrastructure/Persistence/PersistentSchemas.swift","FieldEvidenceApp/Infrastructure/Persistence/StoreGenerationFactory.swift","FieldEvidenceApp/Infrastructure/Persistence/StoreMigrationContracts.swift","FieldEvidenceApp/Infrastructure/Persistence/CurrentPersistentKindLifecycleCatalogV1.swift","FieldEvidenceApp/Infrastructure/Persistence/CurrentSyncClassificationCatalogV1.swift","FieldEvidenceApp/Domain/Mutation/WorkspaceMutationContractsV1.swift","FieldEvidenceApp/Domain/Mutation/MutationReceiptV1.swift","FieldEvidenceApp/Application/Mutation/WorkspaceWriterV1.swift","FieldEvidenceApp/Infrastructure/Persistence/WorkspaceWriterAdapterV1.swift","FieldEvidenceApp/Infrastructure/Persistence/MutationJournal/MutationJournalStoreV1.swift","FieldEvidenceApp/Infrastructure/Persistence/MutationJournal/MutationReceiptRecoveryServiceV1.swift","FieldEvidenceApp/Infrastructure/Persistence/KernelMutationReceiptRegistryV4.swift","FieldEvidenceApp/Domain/Replication/ChangeJournalContractsV1.swift","FieldEvidenceApp/Infrastructure/Replication/LocalChangeJournal/LocalChangeJournalV1.swift","FieldEvidenceApp/Domain/Replication/IntegrationEventContractsV1.swift","FieldEvidenceApp/Infrastructure/Replication/IntegrationEventProjectionV1.swift","FieldEvidenceApp/Infrastructure/Replication/IntegrationProjectionCheckpointStoreV1.swift","FieldEvidenceApp/Infrastructure/Replication/IntegrationConformanceConsumerV1.swift","FieldEvidenceApp/Domain/Backup/V4BackupContracts.swift","FieldEvidenceApp/Domain/Backup/V4BackupImportContracts.swift","FieldEvidenceApp/Domain/Backup/RestoreIdentityV1.swift","FieldEvidenceApp/Domain/Backup/ReplacementRestoreRule.swift","FieldEvidenceApp/Domain/Backup/DeletionLedgerV2.swift","FieldEvidenceApp/Infrastructure/Backup/BackupCanonicalEncoderV1.swift","FieldEvidenceApp/Infrastructure/Backup/BackupCanonicalDecoderV1.swift","FieldEvidenceApp/Infrastructure/Backup/BackupPackageValidatorV1.swift","FieldEvidenceApp/Infrastructure/Backup/BackupExportService.swift","FieldEvidenceApp/Infrastructure/Backup/BackupImportService.swift","FieldEvidenceApp/Infrastructure/Backup/BackupRestoreService.swift","FieldEvidenceApp/Infrastructure/Backup/KernelBackupRestoreRegistryV4.swift","FieldEvidenceApp/Infrastructure/Deletion/WholeSignDeletionService.swift","FieldEvidenceApp/Infrastructure/Deletion/EraseIntentStore.swift","FieldEvidenceApp/Infrastructure/Deletion/EraseAllService.swift","FieldEvidenceApp/Infrastructure/Deletion/KernelDeletionEraseRegistryV4.swift","FieldEvidenceApp/Infrastructure/Deletion/DeletionLedgerStore.swift","FieldEvidenceApp/Infrastructure/Deletion/OrphanFileCleanupService.swift","FieldEvidenceApp/Domain/InspectionKernel/CompletedActivitySnapshotContractsV1.swift","FieldEvidenceApp/Domain/Workflow/FinalizationContracts.swift","FieldEvidenceApp/Infrastructure/Finalization/ReportSnapshotEncoderV1.swift","FieldEvidenceApp/Infrastructure/Finalization/FinalizationIntentStore.swift","FieldEvidenceApp/Domain/Reporting/ReportProjectionContractsV1.swift","FieldEvidenceApp/Domain/Reporting/EvidenceDetailCardContractsV1.swift","FieldEvidenceApp/Infrastructure/Reporting/ReportProjectionRegistryV1.swift","FieldEvidenceApp/Infrastructure/Reporting/DeterministicOpenJSONRendererV1.swift","FieldEvidenceApp/Infrastructure/Reporting/SnapshotValidatorV1.swift","FieldEvidenceApp/Infrastructure/Reporting/DeterministicPDFRendererV1.swift","FieldEvidenceApp/Infrastructure/Reporting/ReportRenderService.swift","FieldEvidenceApp/Infrastructure/Reporting/ReportRecoveryService.swift","FieldEvidenceApp/Infrastructure/Reporting/ReportHistoryCoordinator.swift","FieldEvidenceApp/Infrastructure/Reporting/ReportDeliveryCoordinator.swift","FieldEvidenceApp/Domain/Search/SearchContractsV1.swift","FieldEvidenceApp/Domain/Search/SearchPersistenceModelsV1.swift","FieldEvidenceApp/Infrastructure/Search/LocalSearchIndexStoreV1.swift","FieldEvidenceApp/Infrastructure/Search/SearchIndexRebuildCoordinatorV1.swift","FieldEvidenceApp/Domain/Models/WorkflowModels.swift","FieldEvidenceApp/Domain/InspectionKernel/WorkPacketManifestContractsV1.swift","FieldEvidenceApp/Domain/Models/WorkPacketManifestPersistenceModelsV1.swift","FieldEvidenceApp/Application/WorkPacket/WorkPacketManifestCoordinatorV1.swift","FieldEvidenceApp/Infrastructure/WorkPacket/WorkPacketManifestLifecycleAdapterV1.swift","FieldEvidenceApp/Domain/Drafts/FieldDraftContractsV1.swift","FieldEvidenceApp/Domain/Models/FieldDraftPersistenceModelsV1.swift","FieldEvidenceApp/Application/Drafts/FieldDraftCoordinatorV1.swift","FieldEvidenceApp/Infrastructure/Drafts/FieldDraftLifecycleAdapterV1.swift","FieldEvidenceApp/Domain/InspectionKernel/InspectionPackageReleaseV1.swift","FieldEvidenceApp/Domain/InspectionKernel/PackageReleaseBindingV1.swift","FieldEvidenceApp/Resources/Localizable.xcstrings","FieldEvidenceApp/Domain/Localization/LocalizationContractsV1.swift","FieldEvidenceApp/Domain/Accessibility/SemanticAccessibilityContractsV1.swift","FieldEvidenceApp/Infrastructure/Localization/BundledLocalizationCatalogV1.swift","FieldEvidenceApp/Infrastructure/Diagnostics/DiagnosticExportV1.swift","FieldEvidenceApp/Domain/Compatibility/ReleasedDataCompatibilityPolicyV1.swift"])
NEW_PATHS = tuple(["FieldEvidenceApp/Domain/Packs/FieldReferencePackContractsV1.swift","FieldEvidenceApp/Domain/Models/FieldReferencePackPersistenceModelsV1.swift","FieldEvidenceApp/Application/Packs/FieldReferencePackCoordinatorV1.swift","FieldEvidenceApp/Infrastructure/OfflineReadiness/FieldReferencePackLifecycleAdapterV1.swift","FieldEvidenceAppTests/V9_37FieldReferencePackTests.swift","FieldEvidenceAppTests/Fixtures/V22/FieldReferences/V22P03C23FieldReferencePackCorpusV1.json","Scripts/v23/p03_c23_contracts.py","Scripts/v23/generate_p03_c23_contracts.py","Scripts/v23/verify_p03_c23_contracts.py","Scripts/v23/field-reference-pack.schema.json","docs/design/v23/tooling/V23P03C23FieldReferencePackContractV1.json","docs/design/v23/tooling/V23P03C23FieldReferencePackEvidenceReceiptV1.json","docs/design/v23/tooling/V23P03C23BrandImpactManifestV1.json","docs/design/v23/tooling/V23-P03-C23-tooling-manifest.json"])
PATH_FENCE = EXISTING_PATHS + NEW_PATHS
FULL_FENCE_PATHS = PATH_FENCE
MANIFEST_INPUT_PATHS = tuple(path for path in PATH_FENCE if path != MANIFEST_PATH)
SOURCE_REFERENCE_PATHS = EXISTING_PATHS
AUTHORITY_REFERENCE_PATHS = (
    "docs/design/v23/EXPANSION_V23_ARCHITECTURE_BLUEPRINT.md",
    "docs/design/v23/EXPANSION_V23_FOUNDATION_PLAN.md",
)

PRIOR_FENCE_OVERLAP_COUNT = 1017
PRIOR_FENCE_PRIOR_OWNED_PATH_COUNT = 998
PRIOR_FENCE_PROOF_CANONICAL_SHA256 = "4c703ece631369a5ee4abebf761d7665e653f8b0e95bafb1d62316a5fc1b2e74"
PRIOR_FENCE_PROOF_CANONICAL_RAW_BYTES = 892533

# Compressed only to keep source review practical; generated artifacts expand
# every authorized path edge and its bound-evidence object.
_PRIOR_FENCE_PROOF_ZLIB_BASE64 = (
    "eNrs3Vl320aXL/zvkus+rZqHvpMpylEiSz6U4qz0e6FVo8xuCtQiqTxx9zrf/d3gJFGCrMkZTP6TZRsEJRIo7B9QBVTt+t8fws3s83gy/J+ST38vk1G47o1vmtkP/8EZt//28N1+vizTH/7j//vfHyL9XO7/PsylSeWH//jfH8JsVq6uZ0cH9Mv/9kMKTR7mMCs/lpB/+I8fasgsBWE5L8l5HrhMQfNqXNIqJi9V4Sm47H6486vnk0Kf/ENQPsTquQrCJO+LKrUIp4LNIskYmKrWS1nN/Fcnud2AHz4J+X8+MvZ/epy1qz+X9N/X42EzOxjS9tPu/aBlMFUG57SvtCyCi86IZDTjNQRtSszaBe5FDi7Q93lveJYsBBELEz60nzpuZuWP24+MtCvVOWeDYcwY44NVzOnEQnSOO5NjVVwYk3VSJRVvrbBVuZBtKLYUTR95HWafD9sCXX9olSqLIguVTalZ12q5MlQinj6zSJ+siSx4oZPmPkYt6BtYEFoJZlTmKdKH0pEb1mEKs+G4GdAXD69vt5klFTQTQrd7SVsdrUrMeFVyoUNTVGWeSqeaKpIWmY4DsyUZ+iUlXWXO//D//u2HPJxej6fD9uPpE3s/9ns/Xwx+OTnpDy56px8+7J8cXLR/Do9O9o+P/nP//Oj05OL9L/uDg4tB/+Pg9PSQ/v2/vxwN+gfLEqBPORyW0Tq69q+v9w5LmN1MynSv1x7LwU3TlMnd5R4djElIs+m/T/81rLP2kybD8aTXHRDz975xQf+/fwMKoPiHoRhP8rAJs/Hke2JheQiWU3wlz2zmjsrVVqsMN4YXx6RSiQLGpA4WNVFIBiG4pY2JIjCmVJW1clFyKnTcWAw+VtHNgj/CIllXqxOqiqB0TIpnxoqRNjiVhPDVcM9ZspyKJzteFL2MSqRgkwlMmA4W3iadrS4hUAFzX7JVXLkknGWaBWVjoU+xKQlm6UwgneCZviHQBvhUhWCdLLRhUcbMFKMNzEGZmGivPR0y2k7HFC/cuxxdioUCWzLOreSVKFJZJhf5EyzoaxOL1rmUSinSOeHp6yqdwlgoXhglWaYikk6Xqk10Njnli5Xea89rlQ9Z9Af7Z33ycNL7ZTDon/R+m5s4Pjrs937rHfdfQuGoqZMwnU1uUiti76CMSvsle31aW/ZHo7My+X2YypMMeDeDNxfta64OdGpt/zfMmTaOZXKBcbo+uOplErbolLxwpYNBirrqSoEqrS+EJmueE4/SedoirZORxTsl5UMG/P/02CMMlKETv49MRM9itPTJMltLH1a4DjGFwEN70WCRuDkhVaVrCM+mZMJhNZ0WHzKwhX6yFDqBUuAzOsW4JEssRFdbnTmXLlNhJ5voAkPIXGoLOhRjaV+ktbGTgTDV0dmDItLI7BV5IqO0PbaE6nSuqdK1M7FqpZBctOGZqkm0Dd5LuhY/dXVQWUUVDR2cEliVIvMoNJ3sNF0D6SRI169M10q6hBZfqDS0NzZSKHgVRaZKdX7I4IwuDx/2L85+6fX6Z2eng7mCD0fvB4vLwusVfCyT6XA6a9+9XZ6d0bG9Cl+vKK3CoIPCm4sXFEDhb6VwRvWh8r5QBWm+V4fUbBhPvnxPHqiaXIt1XCWqD1XuqURV4m3dnIIjChttNIzip8ODom21NkuqZFF8BZ1CKkFW2hhFcWqK0KxwIVy3B9HtIRuZMjUeqPKSVaKQ0Mwklrym66bTtojiuDesuhilMYVqSrSJlUutFFW2ZVcNiVMVglVqMgRq1lBdvBQRLLVBfLaMSGSqW1Atk9oK2tCuCl9qkoyqpFTJo1pVKd01JG4yVbgiNZdMMm2lLphMl2qqqtD1XLYbGnnUhWo1hnNGX0D7FL22PknjmH/CA+0clStV/Rz9Q3WhYErb0FGZagWVIsAo79qv0Zk21NJeWWoaUai4KCt9rX7o4fTXk37bSphXhs7OTwdUXTo+PelfHJ4Ofp7jeN+nNsVbdbwL6b9vrpf/HF1djyez51SYVhHRVWF6a0lDBVT8k1QMaGfosgEWYLHjLF7VtoYJmNgZE0fNvJ3dXi+AAih2HsWvn8ejcja8bFZrcMUAjh3HcThswmj4P/Od2niBiwd8wMfeh5KHYW/1A+8oFukSAhRAscsovsFTDOiAji3VMSjtg4thc7lcGpQml8n32NZwFB9SGVaU4arIGEswieckWPA5sMCLrhQwHTCc1T5plUui4yIjK0IEl0KpkbUPHQvjihttQzcM2Q2DmcCrtKY6YSyJpU+uKgYhi6WI1jwGnkwu3CgTjNbcVWdzViq6qOKiv919GJnZQltUlTe6ZrKrUxIqs0KFl6uNnBVXaqUTgM2+Jm1FzoEWjfZUEsl3wpAyJKWEiiIWKjIqNF6qdl7T5tacAhfecV289CFpWnRMpFSFFY7RF3L9BIxkPf1HxzmY4AudqUJuu19KetWexQLziQ58qFLWaujzCteV1NRaGK2hk9HDfoGnH3+7oJj/dXB03t94zt07/dQf/PY3PbyQ3RTeXLygAAp/A4W3dYMCBmDYUgyvbEJABERss4gPw8sFiOcNKvqHkXDU+JWmKlGMpLLmIguRi2QiMi6roVASJSlRu0ZP6Nw28zJFo/QyJ0mbRm3iwHTMtHmBwitV2vhuEqqbBH27pGavdo5ZRu12Z0LImrCKduSA19Q65jxrRUWls8lMWZZ5LMkYLZk3nYOK2iEm1VLABJ45RZBgVdZok9aSRyG584n8aUWFSpFWbeFSZUviaQeL6CahUzCKzGb6ixPGarXLzDAvchXMGWFizC6pElrBSQYnc2Fa0EGjpjyvT42eSMLxUDxtLpNt0z9FyyuvilkhJDUiqWFdWaJ9knTolOc8sOqq0rYEpZx9SGJ/0Pvx6FN/3n4+/dg/aQcWfSQV746Oj86/WdOh/8dLegOqRxrRby1bOICDv9fBy3rFwgEcbKeDj/R3uCyfwqiNlPHkE/+eMChuQ0ntsF6nqWpGlfysopXJCRGD95pKmVNLgndg4MpW7gxVqgPnLmhrI2MsOe00i4pq8SE7EWvqxqC7MbQtDUMfo32ger6lw0wq6UDXRCuqN9XHYEvKNbASWaXAoIYFNR5cW/kPQnVgkEkTeWoTRZcMc0lTddJrqlBmR00Sl1yVwpfAKaLIAqNlHxNVuoUr84FKnRiylNnnZEtUxlJ1tURbjBNFGzo9sKRpq7WoNnFFB85yTicIbmP23GXLnAxPYNCM4jwlLul8wrVXifsgvOLe0fbTkTeJgoAH2Y6NKoXaQoLZxHLm3mfajNDRXtg/OT056u0fX7zb7/38y8f1g4dWx9FB/+T8hSYOxldh2KwsLG+oHtHbs+HsyzMQ6G4Eby5YIACCvwnBJ7VYeH4zGQiA4LtH8LXaUS8044Z2bdRv0jiXCS4MMLHrJl52BwkcwGGrObzsRhI4gMNWc3jF/SSYgImtNvHC7nrwAA/b5uEbdFMCC7DYehav6Kv0D3JRtDVBpuB51t7WWtvUqm24MQpAinNfq8vFxA4XkhfaNGci10ml2qYFtIF5yQyFn7I+maIoYHO3C/NIXr+sWxqafpP2U+ncDgXS1XuWqqNgVUZYV4WhzQyqJvp+ihUurGp/zMsuF6UKxpXzkakQ6b+c6URgRKmZPizmGFSoKba5g6NmVB5VFF6Fo9ItqqqQO114rjIvWrVPtZNixldR6ZzgPX0Xs4yLEmOVVkhSndtn9Nn6aIOm3VC0yekJF6ZEHYp1tMWVWWM0/ctZliYxSSeN2r5Koe0rWSLPzlvreaDVsUjDamEPXRz0j/vn/YtFwtfWwsfTwfn+u+P+67K9bj6HWGUVOC75skw+iScFmG4Bby5VCICAv0XAoFyPQipXpZkt2w6Dm1GBAzjYNQcv7ZYBAiCwVQRe3ikDBEBgOwh8GOcymu79Op78dx2N/7V4ifhH/O9I/K8Cf90iXuQSQzUIBnbPwJ1MrAAAALsH4EHWVdwTAoRdgPCsDtoH5bkdtCECInZBxPOHLEAERGyxiJcNWAAGYNhiDC8brgAMwLDFGF4xWAEiIGKLRbxwqAI0QMN2aVhPcrXZC/V5U5WAAzhsKYeXTg4KCqCwzRReMq0bLMDCllo4nVx/Ds3hcFR6oxKam2tcH2Bix028enpcmICJ7TLxtql64AEettfDK9NgAAVQbDmKVyTBgAqo+L5VnNNmTvfOzAVfNRveT8L15/nq7yn8q7C8hKKkkTy3eZKKSDxxoznjrnIKfiKgfNcs0EYn451irp1FS3Lms2tnW87C0aI0voSUKd4emZ/Edod/dC5wk3XKWrEclcnGMzr2knbXCuuD4LlK+pESuCyS5SK5NVKnIhNzInWEvzXFGl7Io0jBxHZur3YGFdbOemaT1FZ7U0o1tUgbpVTKCpGjKVpr+oIiO8O/BseEitlJzn2hbQuO2+hj8kU74aIrXErhvJmfGJKLNbezjRXhU3C0tU+Ef050qLOyMfqgkgpG0j54rXyuhSchTSg8uppEFiFywY0IIZUas1LO8Ogfhv+Awp8i/+DiYP98fx7/Px61yZGOem3UE4XXT1iyHPrQG1/RTwzjcDScfdkbEIswLfkgzMLGOx/Ho2F6TnIA263kzSUPJVDyNyj5dn1e/0EwNAWAZJJTSGvvopBeJ80My1kIJbmkGlCoZjFt1D0Y9POeW7qWa7rCBRmijomOW2injGKGW7Ll21RvD2EIKgPeDcMLTXWbJH3y7VxN7aRUScrKk5WawjhQ2KZooxNVSyV9pWpRYSyZtjIVq9AdMEgR1epi4U57VTL9odChq64LVAdzISbeThKlM885UHxGqrRRTY3LXIqv1rju6a3anaV6jaIDkE2mo0QlZpxVla7ojCozyQYfWFIEVpTCKb6z5jlpnhTVhdgTMFQsxgvBZJAlJRalpQppkopqRlYlzmSlv1sqVIsouvL2xEAmGG+rH9WkhzDOTql6NJ/+czBnQQw+tP++AAD9GS23d+/DzWyx0I6Xm16Tyl8nw9mTwx9WR75rPqu3liiiH9H/J0b/KknGg8BfrVm3nmEABrbTwGEJbd1nutdrj9vgpmnK5O5ybzye5GHT9u0GARDYRgLfqv8qCIDAlhF4VUcMOICD7XBw97navVbxfg7XaByDwq5QGJT2duiwuVwu0T6MaZ++4IIABbusoMnUNPj+DBSmnfRBi+CpvI1NVUXOnbcqUFhElpXlTmTWYUD5nIRstyBH7jIFvSjeJuMEK8lzAmVDqSl0GxDdBtpuElnLQB/tuLPVa2OiiUSg5MR1piKgEEjOxlSyTN6pGl0WqtI2C+5M19MzinWWWDaxcs9SiqYy7mVmVKoUWsWwWnX1JtE3Vet0bWcesjy69lEMQenuYkEbmotnwpRauIguOh81yXWcx+CcclkpXWWm8uDRSEsxSlFLkc1YoGJ5ykCozGpnaLtrVpziPBj6y/pi2kdEkT4puOQTbalTIlgVleHBeKJgXaAAe2Dgwy/n++dHpycU7L3+0cfzi59Ofxmc7B9fLCD0Tj/1B7/9DY8MxCP9Ld5avrAAC3+ZhTfPOQIJkLCFEl425QIQAMEWI1jkCwMFUNg9CusGwmphuStoIIDBLjJ4Uw8jiICI717EN0xFDxMwsTsmnpeMHiZgYutNPH9oDjiAw9ZzeH5CenAAh63n8MKU9DABE1tv4gVJ6eEBHrbRw5uG9QAEQGwtiJckpgcGYNh+DM9NTQ8N0LDVGl49/hMqoGLbVNwdDbrqv/HT+GbShNH91/NLB248gQmYdDJZ7uW9QaQAAzA7DuZlUzxABERsu4hXTPIAFmCxEyxeOM0DXMDFtrt4dZqmfxCM6LgVhgkVfCkyVCcS90b7kEStPEtusrRKdaW2tzI41R4KOjgiKXLBVHUlOUGHxmcmJJO0G6YbhuyGwXgIzFUbMo9R0TJ9RPQuap6Kb9PbmyKKMrSlKROdwJl1ImZeWBIsxNABw1tbA8U9J62aayvoV0w2wtciUjt9Bm2yze2MK1pyOg1wXtvvVpJxSVHXDYO+rIgapPR08qjF2OCrM0KRXVrOThvJolGKOS6YkdUkQeY0t9YWXub58r8Go0avRaq2zUwTZarCMuFkINSSSjlUrnViMtEeccVMrYxe0vYUmUoJUdSOBDW/nfQuesf7Z2dHh0e9hZFFopqTw+Oj3vnrB59uPuT+JJ4Mf9kd/m8uUoQ/wv+vD/+XJyBA/CP+tyD+v+WEP2ABFlvC4g15CCAAArZAQNsurqPxv9Ytg0UfJwAAgB0DcKeHH6If0b9j0X84bMJo+D8vfGoABVCwTQoW2bvPmnA9/TzGZQAAth3AN067BA7gsPUcnp9xCRzAYVs5vCzZEiRAwrZKeFmeJUiAhG2V8IoUS+AADtvK4YXZlUABFLaIwpsSK8ECLGyjhZfmVIIDONhaBy9JpwQIgLCNEE4n159Dczgcld6ohObmGlcGgNhlEK9OLQYQALFNIIbhshlPZ8M0vbO8eOqG+6rQsFsa7nZP3XiBNgRM7KiJu+ktejeTSevgS5N6ozCdrvewF2ZhNL7EFQM6dlfHN8rKCiEQsmNCXp2QFVZgZUutvDwXKzAAw5ZieGUaVoiAiG0W8YoMrCABEltEYjGUethcLpd+HLadYb/0xuNJHjZt7/DvSUQwVglHHy+kDtmmpIqKidkqoqFgScEJJVXKHSJqYplCy1Hs10RBagTXdHiklYJnZVT7ecJW1y1CdYugvfWeV6ujDRS/LFC0piSJJdPGcMMpTKxTsRrGkzaOtp+MsORyZZ4IdYiQTJRK4W5r4sUpFq1WsehUQylCKwo8neg76FOYzbWqLKuomsrcF65Kjp0iagnG62KjZqyGHCO5VFVpy4im5/R/EvS7jM4qjpuYVc0pF+WrtiSuhidE0AZIwuiZtCkyOg8o7Yug04DRhnlWYuSytF9cKh0ARyevQAWQuDTVK1p8KOJ9/6Q/WEA47u+f9ecczs73j/sXvw6OzvuDv/UZt+oW8eZShgiI+DtE/Ak3aUEERHaNyKvv0gILsGwrlpffpoUGaNhWDa+8TwsSILHVJF5xoxYmYGJbTbx6mqx/EAomrAhUqEmoUL2TStZcSUXUvGiK8Jhl4VyqDhTZMFmtlHSUctbZCa5q1T6mwCK3IkaVrGVZdKPQ3Si8dRT7wmmvXfbJkNCoo3Ra2SySlj5EF3mmAC7tX9GzTJSLiUqlQqA6UBihg/YmsphZNTYpki5jqYVFpiXzVWotdfI5EjxH++DpTZmrszGHFEInCtrtkI1hwZkUJSuqBMtC8T6RZUu/HkNIvDoqGsk4p2+WNmfDvTDBypCeQpGVtTbS2cXUImPKPlDcyxoLwVdBhhw8xUcoyWpN5yQboqDCZoU2iDyzhygG/bNfPuy/IwM/nb67eHf6y8nB/ssmjDssoSUw3eu1h21w01D96O7yS55W6G4Bby5VCICAP0/AN04ACwRAsKUInp/2FQiAYLsQvCzZK+If8b9d8f+yFK+If8T/dsX/KxK7AgEQbBeCF6ZzBQAA+O4BfJO8G5AACdslYXOeONwZgoQdkvANRvbAARxsnYN73a+BAAh2EUFDVSEQAIEdJLCeOPo7vU8avOWMZ8+M46ZSUXM68omJLKISgRaKNNx09SYNWkmRvAztoHqfVfTS1Cq5jD5l5l3b+9MJX7oJmG4C0ZQYuDLtbpVM0U9hQJugKRZdicYFTe+wlFRlLmQleY0qckYEVanB1A4CzgjORWWeyeiqda1zKUr19BFUlJ57ZoML0kcprHKlMK2TVfQWHYvquof9kz0rZJVCFdpAUzSJUs46Om9wOorRJGYLd9F7K4xTiutkvBBMZq9l1U/1Jm3TGhBcQkqbWCNXqhRFpwKraCna6Nt+tNxIqUtOtAckIlshqmL0TYqbhwQO+p+Oev2L86MPi46kFPnn/d55/+DiYP98/yUU6M9oudnr0Wj3O5E+A4HpRvDmggUCIPjzERyMr8KwK/5Xa9ZjC74vCroqoT0VZ1Ztt/X2",
    "w7QXVlaWpI48RF6KCayLAveueE7bIYSgMApG5UxVl5hclXQVK3Qho43zj1SJbDeFLGmvKydXTnkt2o8TFPDMFy4s1XmqSZn2fV5l4bmYogJn9P0mR6oYMN5BoU1N440M0RYRRAnkQkSpsjfFaxsyQTOKDFTOgtROEMI2+42jLyfWrnt0gSiCTgJFF8MUVVs02XSSMR/Ip2NRFqqiOCoKWkxUCoJqnsnEyiWno8a5e4ICFYCwUTGqwFnXJrnRutLvZx1ph6kOa3yl7ZR0fjA68KBkZFxpqk9wOkEwLx9SOH131h98WgwvuOvhJ/LQrnu5heWDM6oajcjBVWlmy6dng5vR080C+0jil7eWKwzAwF9u4JNadiR99gAzhD/C//sP/w/jXEbTeWWojsb/WrxE7CP2dyH2v0lTABZg4fu3sLoAbPSgQGUICHYSwWbPIVwEEP+7Ff8PUp/ihhAQbDuCbzzIHhqgYds1PL9PNTRAw5ZqeNmwe0AAhC2F8LLx94AACFsK4RUD8aEBGrZUwwtH5EMCJGyPhLfPJgUP8LA9Hr7JAH2QAIntIXE3s3vvZjJpM7Z8aVJvFKbT9Q72wiyMxpfAARw7i+MbzT0IIACynUBePpkaLMDCdlp45VRqAAEQWwziFROpQQREbKeIV0+jBhIgsT0k7icHOyijYZsh7yWpIiECIrZXxEtzRkIDNGyjhtdkzvsHWUg6BCpcE02lqEqesaKtkka5aIzQInNfdam2w0KxxnjLo5H0azXwSkHmjIhamOiZo0OiaqWg7bbgui3wwEyotMspOu1UiIp2tlblkvexJEEbljWTlr7cepetCSLJzJhTOmlVc5cFldrJpGUOTBthjLFZheKqslXWYKQvUfuYsybRbdARmcozYZRFSF1YpwXlaOdNZEwxQXseNPO6ZkU8vaBTCFkO9AMiZe+CKsrIWphPlirWpopU9BMWknZJ0gfRQVeRhWKckFmVUjMzxqXinRYqKKepoKvNtBehclcFC9lLJ/JDC2e/nZ33P1z82N8/Pv/xone8f3Z2dHjU2/9WfTn6tLbsj0bPvR64bgNvLlcYgIG/2sAwXDbj6WyYpneWF0MgnnE1gARI2BIJ37jbxj9IBk8uyuw9VZWDYDbLyGlFYUp4IXmS3DGqoPMuGVSTt55JTtVs6ah2p0so2TopKFapFh6ZSRTH5ZE2g++WYbyvjloeORWRWbXUEikuZem44jrLNke2tIr2OqpqMm1AUDlY8siohl8460qyXQWxcFZolqJt0zNnJbUVbaZOVjmhKEKVyFNIOqVUA7MsUCBWE+kXk+iUEVihD2VWZpFrUIxOBloxapC4pNt8tHSOyIIqtcVL+pZENXzF6EuTbtPGcsufkBGclsy1e+6lpc+nDw7aBFsTmeDK2iBjFNGUlGPwzNCpjBpNus2RS5pTR5vhY39wdkQ4Ts4vfj6i5sLx0WG/91vvuH/RO/3UH+y/778iiUBvfEU/MYzD0XD2hRoPo0KVpXxAEDbe+TgeDdOXZ8Dw3TDeXNiAARh/DYynLxy3HTd+Hjb5eFhL+pJG5flXDyABkm1H8pbaFXzAx9b6eHm3v38QB2uY9CFTy9RVCnxOjRxPR6BkKtbcfhsXJSgfOjgQFO4CUSlWC26So1gSJlPjJwadTErtPebMO5rhksqAP/KAQrUxGp2xlQpDCaWrkzk5ClkmjA1VUigESc1Niv5YczIsGc2q17wqakZ3cFBC0I8SoyI9rz46Cvw24T+13aKgNjp3Lod2zgBDP6OCF6VGYZytXvHAhOvkUKkhL+jsYdtHHJU2K1RLreIoo2bW5KgJWKxecC8D7VJobxyk4trzTI08yyc4KG+MjipbLpShprbN2dG2h5J88lpYT4LpOxTTQvPgRCQ2FCtU6iom2vwODvu9nxcx/55UDH67ePfbef9s8Zjil3fHr2iQLxsc7WjrKfmYXpfUftdy9PVtDlfxVQ+rWOjw8OYyhgd4+Kd4GJRLukhMvoADOOwEh/s1pjmLdxR9o5KhAzp2Wsc5bel075O/4LwVsAr/+ervSUBw9G3WFSpmVpWez+LWNtyYaaeEU5lRW9TnmjoEJK1Z1ImlFEspsrJMTV1XslZVu2yLUqFUoW23APGIAN5ObGZzooays5zilBcbvMoleG2dpV311tUak+MiUFsyiuyoheVT5dScSh0CqEEsXSqZ81LoF1m0JXpZvXGJFVOTzVVrXanZTvuvVaxKRuNpv3WqOs3n7ux4isedkNZQJHJLrW9FR8JwpVLkbcOPWoEppiwUFR6vyWRJ4exNaeehK0zE+NREcKbtHRZziDY7VmuWxjGRZIiOPo8p5lNyjmfnlQhU0JZlHz2dwOgsFHytXxVw3N8/61+8H+x//HEB4Ojk5Ojk/StqSrdXgZ/LpCmjrkrT/PHFE3eYVvHQ9fzureUMEzDxt5rYlPBuSAHTXAIEQOwIiG9wewkUQOG7pvBnNaX/QTAUNVMpGqyn+OYkwWVqDUefZbZMGl48vcwUnF0DJXR0bVglIxNtBKdGTqE2q9XZGUNRKIpy0qhHYOhHugPqGnTMUQip2pnlqzXJS2rnF5WszyllbkJk7SMzFYPPSlETUxQZeOFcO9UBQxBVXSjCnSj0w/RxPLJQK6eWmfHc6KpKO7hAaeHo+2ylwAqCixRNZjHZ7qa0Ke3XMuUZfaRKVHpMJp0EZ3SWoGawMNQurNFE3/ZYzC6022h5LjFEOqpPwfA8SjopGWrSy8XJgtqLKmseK3EwulRmqfmvHLWcq9F0DuHSU3PTJvoOph7C6J2ezJ/JDfqH/UH/pNe/+HVwdN4fXBzR+ve0+Ntcye3Tutd0gWrap3Grf4/HqR0s8SE0w0p79dzJ5VbB0dXSfmuhAwiA/HOAfJyMfy9NoJ+BDdiAjbs2BqWWSQEN0NhhGvfaH/eIrGSsGx4AAiAAcgvkiP6+nAxnkAEZkDGX0bbJR8sX88xoqF7ByI4aue0Lou83Om5b5s/rGfIPkuFyqoopK3TVse19E41kWVRuilKacUn7mMhIh4wYKBYVL8Vq63mwjFE0qRxCpihkTApG0GR5pG+U6ZbRBnp0xalQeZFR2VxTpeNulfIlMOLmea2SVSmlLvMb+0FkYwSTnPR0jbPgTLsirBeBM4p8+mQWlHRKKUMbKIINMQofvM+BC59cYbEdNmzo66oXInfKSJG3ncdMmx3H0gFIRQQW6RN9zsVKa5TOkvz5qG3Wgr6wFK6obGT13mbxhAz6JZ9LIrWh7XpWtWLOGplN5izp6hUTQjmvDWsfeFiejHWWkMhCZxPpZJeMDx+P++f9g4uzk/2PZz+enl8cffjwy/n+u6PjlsU3eAbejlwdlVnJ+7T2d6pIrTLhvOSqYbptvLm8YQM2/jobt9mgVm8elFkYjtqAhwZo2FUNiyWqL/3X4soBC7CwIxYezRdIV4YyuRo2wzZH1Ol1aX46Oz0ZlCZT42ICF3ABF8P08eAQJEBix0ncrz694FneP4hEbhMhRMeDt15WSSGTLIWYyJlijkkbXdTcG9dBQsQ2D7N0NWXuhbK0ocl4CsAihJO55KilKsJ1k3gk23KNOlPE0vENISidROY5mhhDzEV7y7RQNYpsQ2a0nYViwNegqRBijJwb2UEi5kD7JG1qB3P5WoIxJso2N52WQVVaw1jJxSTh217GqXoZKa580onOErKbhKwmSENYvUpc+yRUEoZOHkYzE2u1lqB673KVqTIVNJUjvRF51qY4YZ66G0tQa6Hys0loKX2hCGiz6DkudaJSZtLT+cdQITFmNY+Cvqi2affaHsdK8I6cgj/3Byf944t3+72ff/lIgX92fjroXxz0WyYX/UHb4XY9VO/N02gvbkJtTKa95qGe5PFIAuY3Fzl4gMffy2Odj3kBZPVynp0ZQABk54HcTRK1MLKaMnW5h9+nEstNlZkpn5SSbfMjV5WK0lYUG0qKQvEgfe5Skl3wqmbJfY5OFcdUtFqXYG076oZksTbrclLdSh7J3Byzp03iNZVak3ZR5ZQZNQFcqBThwXpqfCiVvJTt017BDCklN8759nl955wW3gpLv2mtNilwTYHU+sjGxVwJhU/MB16prSQEfbH0xoZA2pNpGx9adT/zdj4TqyCVSTL7driW0bp99O9MStIwU6gN0OaCDixEHhzLiTbQOqmozUQYn5rTwjCqRVtNtWxTbSzOGFd4VqomH5IUWjCWQ9XU0qMzCB381I5iapts1VJz0XWPYbrzRPuelvZx91LMC4jQn9FyB9YTCN+fCewZjY5H0jW/uYjBARz+Sg7L5xgPJazWvOQ5BlAAxTagOCyhrT9N93rtgRzcNE2Z3F1+3uSpEAERuyPieXNFwgRMbIuJ7pu1i38WEyI9Z34wiICIXRCxTA7y3KkjwQIsdoHF8nkerhQgscMkXjWzKjzAw7Z7OJ1cfw7N4XBUeqMSmptrwAAMwGj2fv08HpWz4WWzWgMYgLHDMO529bj3NHs/h2s81IaNnbVxv5c5XTKGtJNf8NACNEBjgwbt1LilgdoUWIDFHRbtAD2gAAqgIBSr7Dd4mAcUO4biNleaa59oHw9rSV/SqCxSbM7363mZ0v5BHhS31ltbRPC0VKiEq0jR2hyZo6Km+ItOy9g1iyQXOdjU5uNjvp3uMOospLLKki4t6V1rnNDRdHt4ZEZ63U5SY6KuPHufZZIkIYjqqQSYCVmodty4q1Qulr7TGMEli9UnoZPWwXZ5yOSrneEmVklbW4vL7YwixF2nzINoc/XxEnPkJhjCzTXTdARa0Um4qHX3nDAhBXqXOMlqJf2mTVX5XFnJpghH/hi9mUlrlHQgvc5MGmmiFZmO2nx0+9c8RE6nFCWKdiU5nYiBdSmynKNoTwdSC9qrSD9inWY2MFUyHS46DI6xaCt/6OGsvz/o/Xhx1vux/2Gfgv3dL0fHB69PrfmNhlI8Mhn9m0sXEiDhL5KwHEWx7NmxeiRxXPIlCRAQAAG7JYCaCiO6BFzNU8kuEhbcjAocwMFuOfikFgvPHzAEAiCwHQTanMm0A3E4Gs6+7C2nD84HYRY23vk4pjbEFzQTIGNnZKzbyveycQABEOwegjdlHIAHeNgOD22TeXUztfc5NJflp/HNpFlMUgQO4LBbHM5KmKTPy39AAAR2nMCd/t0fxrmMQAEUdodC20aoo/G/Hg77wXMFQNgFCF/LIdALzbihHRsdlETXBvS5gAiIWIjoNxABERDxwoRkwAAMW4zh6AoYgAEYXpuYDyIgYotFvDAnHzRAw3ZpeHU6PlAAhS2l8LY55gADMLYUxqtTVMIETGypiVdnp4QJmNguE3cTU/ZuJpPSzNarZj8Pm7xOodELszAaX+L+E5RASTM7+9Kk3ihMp+udBBAAAZCyHjq0HCBx//VZe/MWSIBkp5HcVrLO6ABfBaQegIdd9jC/KrwvTVkk6TsMiVZ8AQqg2HUUH4bLxJXIUgMVUPGG+VPAAiy2i8XdrATH4xRGG6kJOlZBCZTsnJLlSO25hsXyUZPLH7gRBRA7DeKOhUGJN8NRvjPl1vcFwzllrVSMJym8NsnqGpTQWZpkmJWyKBZcLbxrzghOP5TabP3SyyxaU1oExaUwkv7WiZcctJGdMDjvhmFy9bamzBzXVnAVXTU6lWhU5anSnkattDa1Cl2d9JwFnVOkWKFqrfWsdMBItjovS5DKh2pJEQUhI1pZJEk7KbmUPkmpFBn3ppRAJUBuuGvRe9c9Z0Qihc5HWVKi8NWMaSbpt63kXIfkuGdC0tfpUlMydGJJJbESBBNGhOAzfwJGZZUlk6KXmjn6WAp30ixCSrrSYWmnzLAUDWRaGG2jtPT52eoSvalGuA4YP53+MjjZP74gGL2fP54enZzPVZCF4/3f/vrs+PPj32HgzeUKAzDwpxv4hrnNAAEQvl8I32xoNhiAwdYw+BPuLv2TfESXMoHw1uVqZKVNKDz5aB2FYFTBMcWZYrZ2+GDCplCMk4pk5CJSpVeFR03GuDLUCrc1BpG7fYhuH9xLajkWE4X1OnivFbUqi3IuUVlQAFTVWvGV9pmaUkJJLckg05ZKhxravsOHqYLa9JoFKsjCKH5yzG0zXGRnaINj4UoXWbWMJXEestEqKzpHVBWome1zpw9q2FoqdhM0Z9kIK4uhX26ngiOyUZt2IjgZeHtfgHbIWhW8tdZVV7PNjj01z5xmgg5uNsEWSeFOMmKLuUoWSzCetOhIhz9UQiOlVVROOlU6X1Rvssz5oY9l5H/otzDOzn4Z7J/0+isip4Pzv6HZILoZvLlowQAM/goG32I+ISAAgi1C8OLJhBD/iP9tiP9vMlUEMADDNmBYp0JeTMe+noodAABguwEcltDeNZru9doDOLhpmjK5u4x6ESRAwkLCupcFLMDCVlv4tmnAwQEctpbDyx40QwIkbKuEl+c8Bgdw2FoOL0t4DAqgsE0U3py1DyAAYqtADMNlM57Ohml6Z3nRekBNCRp2S8PhsKFmwv8snkBvPnTDbSWY2EkTf0JSVxABkS0n8oaMrtABHduq49ukc4UQCNlWIS/O5QoMwLCtGF6XyBUiIGKrRbw8iytIgMS2knhtCleYgIltMvFnZNgAERDZLiLjyWzYXC6XBqXJZYKuH8Cw0xjWA0u/zz6ySkgdXXFKcS1pVarKSApGxYoI1QXFnHQ52K5ExjJVTVHl6Se8rJk0eedqTTHkIFwuKRfyZbsxyG4MMQtdFCeHgqIg1pDp01lO1oVIyFjitbIoQw1JcV4paB0LIQZrmCDNrAODqIyFrELVqljnCynLXAWj2kxlrBqTTdKKU4gp2WZJ1kGKonM2ZMRyxTsxyOAoEkuiiKRThlPt6cBZ2qYYDGlirCSRBQsuOWa9Sd4rrbWPJqmkfKlPYODKC+Uil9wHa0WhYhVCWeGKprU1psgEnaSM1kXUILQTpipGQdCmMPOsIzfZAQV47/zi46A/j/azo/P+Rf/T0UF/bmKt46/PwCS7Mby5gIEBGP46DMusA/tUBtPpMA5Hw9mXvbNyFZrZMG2sfUkuDtiAja2xsRxKseo0flzyJV0gBBAAwc4heGWiPlAAhe2jMI//I3p7RtUj1IqgYAcVvDxpJRRAwbYqOLpqb6/CAizsoIXe+Ip+YnUPaUDN5TAt+SDMwsY7H8ejYUJ1CTh2CsdRM70uqf2Wn8ukKaO5llGZlbxPa38nF6sHcrjPCiI7SWTeWWk1EPvuC4iAiJ0UsX46vVpY7gscwMFOOnjTBBEgARJbQ+KbTLkLERCxTSKWXVtXbx6UWRiO2rgHCqDYcRSLpY+T8X8tbkOBBEjsJImzEibp8/IfKIACKLgzsvrDOJcRNEDDTmlYT7rYn4RpOWraVEwwAAM7aeDFE4+CARhsH4MHs0VgpAMs7IiFZ026eFCemx0fKIBiR1A8f8oIoACK7UbxsvlI4QEettvDYnQQPMADPLxyll6gAIrtRvHCuXoBAiC2FcRipNwGi0G5HNLPffmkIAMydk/Gei7r+YPq/dEI1wlogIY73Tbmk6WAAzjsMIdFxWn1co4DFSfYgI12COn9bh2oQYHFzrI4HDa3OTc2O/7hSTZk7LCMjWw07ygIRyVvJKV59tTu4AEeW8fj7mSMvZvJhFret7NY/zxs8vGwlvQljQqgAAqg3IVy9qVJvVGYTtf7CSMwAiNzI6vMTqspTO+9nt/ehRM42XUnt7WtMzrGVwHJxkFix0nMrw3vS1Mm8707DIlWfIELuICL8mF4OdlMmQkYgLHbMO5N+rufwzXm/oWMHZVxN6Xs/EnHRl7ZjlWAAig7CmWZVPOg0PXiatjQBWWYTq9L89PZ6cmgNLlMcB0Bj13ncT/n7LoTImRAxk7LWGdXw9hXkNhlEss8tPPGxWL5iGpPf+AxH0zsuok7HAYl3gxHuTceT/KwwfUCNnbGxqBMxzeTVKbrHrlxVP79j0RcqCI1Rfwj/rc5/s9pS6d7Z+aCr8YrvZ+E68/z1bgCQMCuCPjk",
    "L4S4O/5in4pkOl3OKQ8O4LBzHPT+zezzeELh35s/vqYvPKC/f5/v2XcnggQIbRzPWladAsWcjsw4r0tgFNlRR6lYIAEPRdgcPYWjZKlI2uIUDBEy0VfLoqCoDo5zqXXqFqG6RdD28MQ57RwTJlMsMGM144GOvNGJkUJnfeWOR/JCm86NNoEpJTlhdkV1iLDVCMOSSdHn4kWVvLBQo/EqUsgrKvCgDO1iYLw9K+SiqECIWCi0M7GEThExkMBoRJS2psoZiUrKqlRDkGRMB1GSq8Y6KlTOgna8Zq9YNEbJILJ8QoTUjvaf00nAWfqSEp3KKdgikpdc25CkLCwzoUq0RD1SEUmpmdBJ6yxUeijidHBAFg5aEgf9Xv/s7HRwcfbjfrvq+Oiw3/utd/yiBgL9WT+2fjhR8KJnxzNay6qbwpuLFxRA4a+isJzCYqNqtHdWrkIzG6aNtS+Z9w4yIGNLZCwTC66a0sclX9LFQYAACOwYgbazH1WPrkozW6XWfM70RoAACNsGYR79R/T2jCpGqA/BwM4Z+KSWsxg9e2gQDMDAdhpYTNICCZCwcxJ64yv6idV9owE1ksO05IMwCxvvfByPhgkVJdDYIRpHzfR6MYZhkVt5bmVUZiXv09rfScWqRzfurALIDgLZSJe5kScTHuBh9zysn0SvFpZ7AgVQsIMK1v0xVmtwWQCIHQRxN8fGRi4NeICH3fSwHBG9evOgzMJw1EY9SIDETpO4nz4DIABiB0FsDIeGARjYdQN3Ulh+GOcyggVY2CEL7b2kOhr/6+6svxAAATsoYHPGRiAAgh1E8GBGX4xkgISdkHBYQpswbLrXaw/i4KZpyuTuMnqxQgM03GpYZ8+DB3jYeg/3skouxzksR/qEZtzQno0OynNneQcJkNgJEv0GJEACJG6u+3/Mby+Vye/DhBY1NOy2hsXIUGiABmi4uf5If4fL8pIJTEACJLaZxDKVDK4Q4LDbHBZjpDdQrKd+U3ABF7vmYvVketFlaX80wjUCFmBh3X1vPt0bMADDzmJYVJlWL+c0UGWCDMh42L0PdSeg2FEUh8PmNsvSZudvPLWGi511sZF97B2F4KjkjSRkYRZG40vgAI7dw3FnuOhe72Yyofb2etXs52GTj4e1pC9pVMAETMDklsnZlyb1RmE6Xe8lhEAIhJCQVR6/Zfqy+6/nN3ShBEp2W8ltPeuMjvBVwEA8gNhpEPPrwvvSlMl83w5DohVfoAIqdl7Fh+HlZDM1MliAxS6zuDeJ+34O15jLHS520sXdxOHzJxsb2cM7VoEJmOwkk2Xy5INC14qrYUMXk2E6vS7NT2enJ4PS5DLBNQQ4dhvH/czi666GcAEXO+xinUkTo1oBYndBLLONzxsVi+Ujqjf9gYd6ELHbIu5gGJR4MxzlO0kFIQMydkDGoEzHN5NUputet3FU/v2PRFioCjVF9CP6tzf6z2k7p3tn5oKvRiO9n4Trz/PVOPsj/ncj/j/5CyHujq/YT3Q9mA7jcDScfQEGYNgxDHr/ZvZ5PKHg780fVdPXHdDfv8/367vzwK2kotXCC02fEShafBKByxgVj5IVVqtJ0qkOD6EmkwOjIFSFNi4ZxbIuzNMOWB5zira6mkTs9qAf8VAU7W6NzDKZiEOkDXAuCEsxX73yvNKBr7LawK0tJgn6BiGJrfGs0Ld3eHC0ExRURiRDhI3llplsUvsJSZmomIoUVEJZUuKUUFIQZc0kU5r2UIpOD3S2IEqJfrd6Rscp6JwV/WLy2lvJjA7MmGIqlSqdMKSyyatkla3eMHrfPeGh8kobwItmpdB5oIhgKgVHNlk5OnlZKnmTfaUjX2PVnLGqtdEiRplECSo8z8Ovp4OfLz7u937un1/snxy8qalAf9YPrR9OBb/o1fGMVrPupvHm4gYN0Pgn0GhFtOk0y+zO4ofQDCvt3ctuMIEKqGwbleV8XxttjL2zchWa2TBtrH3J5MCQAilbKmWZhXN1h+q45EuqZwmQAIkdJ9H2oqWWx1VpZqu8tM+ZKxIwAGPbYcw1HNHbM6pIof4EEztv4pNaTgz27PF4MAETu2FiMRcSZEDGzsvoja/oJ1b3pQbU6A7Tkg/CLGy883E8GiZUrEBlh6kcNdPrxYCjRbrzuZ1RmZW8T2t/JyWrARi4kwswAPMQTNfzQUiBlJ2XspEBeiP1M3zAB3x8GOcymnZcP+4k3Fn8DJzAyQ47WXVTXC0s9wwqoAIqbjvvrtagegUgALKRnm0jDRt8wAd83Emxs3rzoMzCcNQqABEQAZGvZGcDEAABkM0cPDABEzCxaQK3cmEDNtY22ntVdTT+115/EqblqGmnYYIIiICIe1OHAwVQAMXer5/Ho3I2vGxWA2cxNhAydlLGYQlt1tvpXq89qIObpimTu8sY9wEd0PG4jnXGHviAj53zcS91+nLk4HIsbWjGDe3p6KCkcUb2NxABkceI9BsQAREQeUik/8f89lWZ/D5MaKFDB3Tc1bHIzQAd0AEdD3W0o5/CZXnJDH8gAiK7RGSZDA5XEPAAj7s8FkkYNpCsZ05WcAInu+5k9eR80eVqfzTCNQQ2YKPDxqI74nxGZeAADuBY4lhUsVYv51RQxYIUSHkg5UF3RdS1gARIFkiG4bIZT2fDNL2zvHhsiBu+EAIhh8PmNl/i5nAQ9DuBEzhZOtnIK/qOQnJU8kZ60TALo/ElsAALsNwZgL7Xu5lMSnObXnT287DJx8Na0pc0KmADNmDzOJuzL03qjcJ0ut5riIEYiOkQs8pEuky4eP/1/BEL1EAN1NxVc1svO6MjfhUwlBdAAOQOkPl1431pymS+r4ch0YovUAIlUHJPyYfh5WQzGTyYgAmY3DJZT5vw62Q4K5P9HK5neMICJ3BSNqZOmD9Z2Zg/oWMV2IAN2Nymiz8odC25GjbDto/L6XVpfjo7PRmUJpcJrjHAAizlK3MrrDsXwwmcwMnayTo3MMbJAwiArIAs51uYN0oWy0dUz/oDDxkhBELuCrmDY1DizXCU76RFhRRIgZTbudg7pmVf95TEvWKQ2V0ygzId30xSma474sdR+fc/EimiVsoUGqBhdzSc03ZP987MBV8N+X0/Cdef56txdYCH3fTwyV8IcXdI1n6i68V0GIej4ewLcADHjuPwD1sX350KwZMukXMuKIqFMb7aXIywtgbDnLTGOMmz5h0qeOKOjk809ItR6qJcCdxzrkNmPtUYNf1+UrxbhelWQcHNQ5G6Kl5YIK7MVJ+0T8FmZx2zzgradVYEYxTKWorqRI3CcV0zE10qZKWYov2i32Tcs8CdKY6xIDOP9PFFeVdj4VU4KTxFlE6cwqtQ4ZogQzGdKrhThUwFXYgX4zY4siUr/b6zSYeSqNAyr7IET+cKK6yns0+iXQo60FfKJ1QU2jWXlWa8Jq3IAZ0cigxV6aiq8lHJmLmKttDPCG+SszYoOnUUTd8Xinqo4vi0t3989J/750enJxf7vdbF0buj46Pz3+YgDgen/9k/uTg4Ovt4vP/bK2Z727g47J2Vq9DMhmlj7UumljbdRN5c7CACIn8XkY0h7xtj3QEDMHYRxp+WEwJKoGRblbQtjumKx1EzvV50uFrOv7DudyWABEh2B8nrH2iAARhsC4P1zSnO2+vB6mLwvNtSgAAIWwfhzY8w/kEqpIs6Zoq2SEXMmTeFcc0IhRXBF6Gji8xEEzpUuCxNVI5Fxpn0XhKGpHOIJlemdaxGRpGDy90qbLcKqTntYSCU2SrefojPsQbaSSEKSzknXhwVjtM5V9o4JQ0TRkhmMkWKrR0qWPtG0NKrol0hxDzGFCi4MgWZCFYrX1gpTkejyYGXTEcqVeW889HMn948VBGt0cVGrUzhqfK2oNqDE6pzdF5wIYiQvaZTTJQqCs5UMCrmZHxp0YX8hApOe1ddEqW020zb79tYoC0yUhs6QjU55ZzhdPooJieKFzozOW1TkoLRoXuo4oCCu3fePsGYR/rZ0Xn/4kN//+yXQf9D/+T84qfTXwYn+8ethwWLd78cHR+8pLpEf9aDA1eJfe6Ppn1GO9t243hzgQMHcPx9OJb3a9cuVgvLfYMLuNhlF3cHlm8MIH/JcwwIgZCdENJOSLVM49P/vTQzIAGS3UbytSlyF1OJPHfGHfiAj93y8cIppAEEQLYeyKsnx4UO6NgdHW+bARRWYGV3rLx6DlAwAZPtZ/K2WUBhBEa23sg3mQcUUiBl66X8GZMbAg7g7CKct0xvCDMws1NmFjfE7nXuwi0xgAGYP3VGULiBm61380gXsN64qePJVaBfosXpzRXuA0AMxHxFzLzT5O28ItACLdDyqJZbKL310Ue9DG7g5k+cFRFwAGcX4Lx9qjdIgZStk7JMH68u5ELGQRkNaRefmV/iH0TCUQDIXCoL0cuahYo8K1FrTYJTuBddeZIxdGVdkdk6HYriRimVfLLSVpYZvQqKGWO05xSK0neTcN0kCINLSniZZNAEK0THqnWZXlThkiYu8zwwKsSakyuqZl6YNUzXwKyOHSR0ciITXk/ArJKaRSrMZGtm1eRQKydijklHQUanAeEMcS7WG6sDnRXmZ4OHJEqg4yStrtlROIYYqZgMoyKMxXiZhaXYDCmx2oImbYEL5aJwQcTATChPkPDC06EoOUVl5ymgOX0Or7rQ2UBJKarxubhK/3PaAmWC4VxYF2MIlU4Q8Xkpspcpsc96P/Y/7F/8OiAmgzsJsttsLG0C7f33/Yt3RycHRyfvX5tv4mASKoGZ/8x8+WUzWLluMG8+CAADMP9MMG9I0AIswLL9WP6cHPSwAzs7Y2c5yng13uW45Eu6wAggARIguYekvYdMlbCr0syW4/EHN6MCKqACKg+ozH0c0dszqn6h1gUlUPJAySe1WFi3TqAESqDkESVHV+1TFliBFVh5YKU3vqKfWN0DG1BzPkxLPgizsPHOx/FomFAdAx7guYOn48kkbhdDCqQ8kHI779xiFOVex0R080sP4AAO4HwFziaXd0OKquYSaqAGar7x1NkQAzE7I+bDOJfR3abMnYH8i/cgBmIg5ptM9wUncLJ7Tta9kVdrUBkDGZDpINO28acPb5HdekE/S3iBl6e8rAcagwu4gMu3nZAVYiBmJ8W8ZYJWoAGanUFzVsIkfV7+AyVQAiVPKcFDF2iBlq9oae8h19H4X4u5W9uqWIMHLjACI11GHsxKiWHHsAIrXdkql0PGlsMqQzNuaN9HB+W5M+8BDdAAzRzN86erBBqg2W00izmQnztZOLzAy257WQzlhxd4gZfneFl2hPkURm1EIV0y0ADNk2iWOchwlQEYgPk6mMWY5A02L5gQGXIgZ+fkrJ7FLJ5g7o9GuM5AC7Q8S8vief98fkpwARdweZTLomK2ejnHg4oZ7MDOM+w86DaDGhrYgM1jbIbhshlPZ8M0vbO8eLCJ280wAzMdZu7njT0e1pK+pFHZz+EaM/UBDuB0wjkcNrd5/RazJ5814Xr6eTxDtzPIgZxH5WxkxHxHQToqeSMxZpiF0RiJZMEHfDr4LDLMLN0g0Qz0QM+L9Syx9H8fj27mc8ai0QM90PMyPWcUS3H8x+CmaSAGYiCmU8xtGo293s1kUprbdOazn4dNXl960OwBJEB6CaSzL03qjcJ0ui4HGIIhGHqWoUW3nHsTBqBjDgAB0PMAregsE9befz3vGooLERzB0dcd3TaHzigGrgJmRQcZkPkqmfm15X1pyiL382FItOIL3MAN3Dzp5sNwmTJ9nQcacAAHcL4GZz1f2q+T4axM8JQUciDnUTmPTNFB15s6nlwF+iVanN5cQRAEQdALBM0nufk4Gf/Xossb9EAP9Dxbzy2c3joacJcajuDoGY7mAxQ2ZijsWAVIgARInZDGk9mwudw7KLMyuRo2w3Zk9ul1aX46Oz0ZlCaXCVpD4AM+L+Dz8eAQciAHcp4jZ7F02wRa93SDHMiBnCflLK40SD8FMiDzJJlVIhBMdgAyIPMVMssZp+d30hbLR3SZ+QN3pWEGZr5u5g6XQYk3w1HujceTPGxwvYEd2FnYOac9me6d8TZjwfn4v0szXwEbsAEbSxvygs/zfi4G38AHfMDHXR/qQi4a9gdlNKRd/gIiIAIid4kYuoQs5yd4PwnXnyEEQiDkrhB3wc8KHZLcNkT+s0zGh+PJf4MJmIDJHSaf/AWfN9VXD+chBEIg5J4Q1wpZZw28078fWqAFWja1CHF3ZoH9lMp0OozD0XD2/V1cQuVSlWToQyxzMdPhiNo4lrTURnOvhfckSndw4SJGb7MwIgknIquMJ8W5l8VwaXh0XGtTfOnm4ru5MOGttvQxQScqB1m04EF5rr3WoXqRHNnwWUZZSpSZR1JVbI7Je6dLNh1ccvaiqiyZVM7lbCwjfEm5lpcUgoo66eCZDtZKWRQrFKquFC49nQqYq51cVJS+JsaLqTrQNiTyWq1W3AtpKNRl0iSAzh501qE9yO3phzZERpZyonPSE1wK0zw7Y71yyTlnpLdM2URnBU2oaTeciZrTNwtCzVXMiltWvJbe0Qmqyudx+dDfP/tl0P/QPzm/ODo5778nML/NlSwh3dJ5waNF+rMe4bLKX3Z/sP8zniX6biRvLnggAZK/H8nB+CoMm72Ni8feWbkKzWyYNtauM8rADMzATLP3jpoqN9fr+WyPS76kC4oADuAAjiWOdpQxVbauSjMb0L6NJ2VwMyogAiIgsiYyd3FEb8+omoXaFXRAx1rHJ7VYeH4+S+iAjl3TcXTVduKCERiBkbWR3viKfmJ1T2tAzfQwLfkgzMLGOx/Ho2FCtQtogGbYptRbzbm8mENprmhUZiXv09rfyctq/C/uB4MO6HyNTsf85fNrEMAADMB0gNlk8m5I0dRcQgu0QMsySeuyr9fGC1TEIAVS7kj5MM5lNJ139aqj8b8WL0EDNEBj3Q/y3tzIuHTAB3x09RNerUEtC1RA5Q6VtrE+fXiP69YJekLCCZw85mSdoxtMwARMNuYj2ph3CBUvSIGUR6Tcnz8SWIAFWDaxLPPWr948KLMwHLUegAVYgKUTy/0ZhUAFVEDlDpWNRPXQAR3Q8ZiOj2UyHU5n7Y8sHsVDCZRASbPuoLLXn4TpPNldgwfxsAEbd20sWiLrSefAAzzA45bHr5/Ho3I2vGxWaYiQXwVGdtzIYQntZHLTvV57eAc3TVMmd5cxTh5O4OQ5TtZzLkIKpOywlHuzlC6zrywzE4Vm3NA+jw5KGmekFAYWYHkaS78BFmABlq9h6f8xv/VVJr8PE9r0cAIn3U4W2e/gBE7g5GtOliNPPoVRG0ljVL6ABVgew7JMy42rCqAASjeURdauDS7rUY0KYiAGYlZiVk/nF1299kcjXFegBEq+qmTRIfKsvayACZiAyQMmiwrY6uUcDSpgMAMzXzHzoMMkamLgAi73uQzDZTOezoZpemd58UASt41hBVZurRwOm9vE3JvDVdDLBWIg5oGYjVT27yg4RyVvZLQPszAaY+YHsAGbO2zuDKTf691MJqWZrVfNfh42+XhYS/qSRgWAAAiAngPo7EuTeqMwna73H3ZgB3a+amdx3/neFBK48ww4gPN1OCsyy9TG91/Pn3XiwgM/8NPt57a5c0bH/ipgBD+ogEonlfm15H1pyiI7+GFItOILvMALvDzq5cNwmUwfKWIABmC+CmY9Q96vk+GsTPZzuJ7hUSfEQMxdMY9M1kLXlzqeXAX6JVqc3lxBDuRAzjPkzKc5up2YAmqgBmqeVHNnJpd1FOBuM/zAz1f8zLukbcxF2bEKgAAIgDYALecQOyizMrkaNsN26MDpdWl+Ojs9GZQmlwlaO2ADNs9g8/HgEGIgBmK+Jub+ZJXrnmgQAzEQ86iYxZUF459BBVQepbKeeQxZM0EFVB5SWc71Or8ztlg+osvKH7i7DCuw0m3lDpNBiTfDUb4z1RLMwMxOmxmU6fhmksp0nScgjsq//5GIEVXIpnABF7vo4pz2YLr3yV8IcTdXxn4iKdNhHI6G",
    "sy/zn8HlA0zA5ELo/ZvZ5/GEWPTmPZRpQw7o79/ne/zdSRE6s2Sdq6qG4ERN9MXOae5qTCkqrRlFlBKuQwozTqlYKVCZN5lijHsntU46usRZ4FJmnd080h5KEaxbCnc6l6xkFclHIbnLNWpXcuY+ERyRQwpBypi4zCJkrkXVQqgkbTY8MdkhhTFnBO1KUV5lFnT0nhvGSTHn1hBpqRWdJ1KN1fMsXbZRJeLPGL0jhOmUUpmU9LUxMGESJ3HJ5sKr4UYLHQR9pNC85CKqpcNZbUxCBU1nIakYfah7QgpFvZM5GtovXmMuNnGlmWlLVQVCrJU2FCmeCYqS6lMxynpbIzNKSvqN50n5ODj6tN/77eJ8sH9ydng6+HBXycf93s/77/uvq2zRn3V/l9Vo5Ptd+59ukcyDpAPKmwsfUADlnwHlYHwVhs3eRnWLGvJXoZkN08ba9dgxuIEbuFm4WU4Zs0q6fFzyJV1YBIAACIDcAdL2P6aK11VpZqsplW5GBUzABEw2mMxtHNHbM6pyoaYFIRCyIeSTWiw8O5MFhEDITgpZTB8OJ3ACJxtOeuMr+onVva4BNd3DtOSDMAsb73wcj4YJVTDAAZw1nPnUlat/28f11Fr5EJphpf3E/WGQAZmvk/k4Gf9emmV6JGiBFmj5ipZBqWVSgAVYgOVxLB/bvl/py/kkNNM2+R6wAAuw3MNy1EyvF6PoF5O8zG8CjMqs5H1a+zs191cDIsEHfMDnKT63Kz6G9N/hsixvowEN0ADNI2g2qbwbUkQ1lxADMRCzELMxgfLGzMmolEELtGxq+TDOZTSdj2qpo/G/Fi/BAzzAY85jNezr3oSuuITACIzcM7IeGrlagxoXuIDLPS5tA3768N7XrRUM/IIVWPmalXUSY1ABFVCZU7k7OcvGJCyohEELtHxFy/0J9AAGYADmIZhl0u/VmwdlFoaj1gTAAAzAPArm/hQs4AIu4HKPy0b2bwiBEAj5mpCPZTIdTmftjywe2UMKpEDKQsqqM8tefxKm5Wg+wgU+4AM+7vlYtEzWs3iBCIiAyCaRXz+PR+VseNmssrMi5SScwMneYQntrF3TvV57iAc3TVMmd5eRMgxWYOW5VtYT3EELtOy4lnvTQi4TUi4TtoZm3NB+jw5KGmfMvgIwAPM8MP0GYAAGYJ4C0/9jfkusTH4fJrTzYQVWHreySA4OK7ACK09ZWY5c+RRGbTSNUREDGID5GpjlLEa4ugALsDyOZZEVbIPMenSkghqogZq7au4lB189pVyTQa0MZEDma2QWoyUxrySswMqjVuZpJ5cvzto6GUa0QA3UPKJm1bVy0V9/fzRCox9SIOVJKUe31xdQARVQ6aSyuEO2ejmHgztkcAM3T7h5MPIFtTKQAZkuMsNw2Yyns2Ga3lle9CRDex9e4GXTy+GwuZ2hZXMMMropQw3UdKrZmNfoHQXoqOSN6Y3CLIzGmAoMdEDnHp072ZL2ejeTSWlm61Wzn4dNPh7Wkr6kUQEiIAKi5yI6+9Kk3ihMp+sygB/4gZ8n/SzuSd+bUwx3pYEHeJ7Gs2KznN/i/uv581BcgGAIhh43dNv8OaPjfxWQpglcwOVRLvNryvvSlMU0MYch0YovMAMzMPNVMx+Gy5mVkA8QaIDmSTTrKZR/nQxn5f9v706bm8jSPYF/l/u6pzj7Mu9ctql2FWDGpqnoO3GDOCtoWk4RkkzDjbjffZ7UZm2UJdmAUf6ju7As2elU6vzy7M8zPMnh4xjToVADNetqvpLBj+qZOhjeBPoleji6vYEe6IGeHfVM8l/eZSqDHMiBnJ3kLKX3W5QEjETDEAzdY2i6VXo5YfmWp4AIiIBoA9EswexZGZfhTa/ptdsOLj+W5vfry1dXpclliN4P6IDOjnRenz2HGqiBmvvUrGc0R/g0qIGa3dRMaxjspQYXcPlLLou0tAiZDi7gsp3LdQnD9GE6YjZ9fEHVy2eMPMMLvHzdyxKVqxJve/28lIMTbuCm826uymhwO0xltIg7EPvll8+JKFHjbAQbsNFVG2/oXYyevfXvhFiOv3GSSMuoF3v93vjL5GdQjYAKqEyp6JPb8YdBmzfgdLKymU7mjP79NHnXP50WlajAJJakDl5TcRcuJ+aSLs6owpMLUnlWq9+iJWVLRcpHrqMtLjhlOIs+MMdSqpo+bcOiqkJv18K3axGCFe2E98IpZgu9URsi81LaIJ2qvrAsjLZGVCrrjtvMrWOEQEmlc7VsmxYpPV1WLrhzVOBY8M4Qg+gylT3DEtMu8KKVSarU7J1NLITqdGRc0K3Db9USPOGU9DsiBBUM3Vw4mfah0p/y9LFlLlmRtggR229M8D5WEUumu4sLVt6jRdeQKl0EOorRnEm6R8jKNf0/Fh3pPLXx2toq6Q7CdFacabrDVBG451xnvpuW0xcX56/evDs9eX3y68WLizf/nGh5UGuL/lssiDkbhkpoJj8zebxf14RvV/LgKw8lUPKElMw3/a/vmIEQCOmukLPBTeg1z1a6Is+uy01oxr208uw+CWkABmCOG8wsmeY80vmLkt9TVSIgAzIgo5XRrtinNtZNacbzLLO3/QIf8AEfUx8TFBf08ni33JigARqdoPFWTR/sHgEGNECjUzQubtpFjwACIAAyBXI6uKGfmI9gXVG/PIxKPgvjsPLK60G/l9DaghiI2TJtiBFe8ACPKY+LZvRxullxGnt/UsP0y7jkE3r2E9Ul8/0mcAM3cPNVN3dPvKa+S3hfZo0zaIEWaFnXsmrk1x4VpeY9qIBK56mspLNcyWOJ9heYgMmMyctBLv3lbv1StPDpa2ACJmAyZdIuBq79wb+n38IFXHTdxXyZ/FquSVQawAEcG3tI5s+gDwIncDJ30g5ijTYHfu+QYKE8kADJViSL0KgwAiNdN7Kc92ElvwPaW2ACJtuYrCfnghRIgZQlKbNowfMXz8o49PotBkiBFEjZlLKevAFO4ARO5k5WAgSDBmiAxlYaWIYCIiCyTmS+/uTZ+TCMStt3bzDVDhiAsYAx7X0scvvABmzAxszGnx8G/XLde9/M49AhxhaAdBnIWvKeWdSUWTih0AwaesP9s5KoA4LAv5ACKX8t5byBFEiBlK9KOf886ZzsmJsXSICkg0imweqABEiA5KtIZqt/98ldDSmQ0kEps8jZqE+gBEq2KJkGElqxsthTosAFXMBlwmU+ZzKdej/p91GjgAiIfJ3IdHXKdVuhwAiMwMiqkWm7a/7tRAzaXQADMF8Ds7F6BQ0wWIGVFSu98L4ZjMa9NFp6PJ11xAgxoADKHMp6MpMXvVrSl9QvJzl8RJp3aIGWOy3Pe81dKO3VBfZY8gUu4LLKZSXy/K9UMvslrwSgD+PQHyBLA8zAzNzMNLrdDAuC3IEMyOxGZibk/NOgf9ueDjoyIAMyu5C5pgIUB5+vbpsGTMAETO6Y3MVeeXZ6OxyW5i4r0PiPXpMXlQy6MtADPffquf7SpNN+GI0Wbx5wAAdwvg5nujpmLakQ1sdADdT8hZq5l1nU+/XvJ2sxUeUAD/BswXPXxbmmD/4mIL0jnMDJppNJLfJbaco0a8TzkOiJL8ACLMCyHcvL3izDyiLeN7RAC7RsaFnkSf1z2BuXIaYwwQVcVrl8JXcX1Sx1MLwJ9Ev0cHR7AzZgAzb3sZmkvLtLVQQyIAMyf01mKbHXoghgYBl4gOdreCZr/1fSEW95CnqgB3ru9MySSZ6VcRne9Jpeu5H58mNpfr++fHVVmlyG6OHADMzcZ+b12XNwARdw+SqX9XzFi1Vm4AIu4LKdy7ROQQQmOIGT7U4WKSgRoh9O4GTNySzX92QcbPr4giqUzxhIBhRA2QJlychVibe9fj4dDIa516BmAZhug7kqo8HtMJXRIvBS7JdfPicyRO2wEVAARedQvKHTHz275m2oizeDf5Vm8gRqCYDoNgj5jk/CvU53eAEFUADFtXonp8NWZ6Xfo/f5BS7gAi6uDVUWs1QTvw3Dxw9gARZgce3e8etCn0NuOxf/WYaD54Phv2ADNmDjrX/HJ33u+RoSsAALsGhZuJbFIm7k0n4SEAERECEiQiwniThJqYxGvdjr98Y/XzVCpctpb61RKlhelKeio6LzLkYtbGFSy5gdL1uMiJq8Z6UYKro5mOJUZLbmTKdP58SkqcZ6I9l2I2K7ESdscjxzOnTgnJE1Eaj8Jiaj91oW6RhTlqWQo09USDwTivAUKehCiRq3GFFFZJZ4VcYLI50NrnAdrHdZa26VqkFIpVxSlu4Gypigss7SM5mZMDmprUbocyqsWs+tSW1RDjEpY6mUsmKIqnCCPiLJXfTcW+NyrFlpZpyTNYmq2H1GpNE5+1K5Ulmx4LgxIgaZRay8JuOTZJZKi/NMa2GCtuQoa+cnH1eMuxm5Oj+9fHt+9c93ry8vyEoL5Iy+uzq/fnN5tdfU3tngJvSaeab6eWf8Rcnvy3CHXBBiO4gHX2SAAIinAKLdZBhSuSnN+Irez2BYrm77BSzAouMsJhYu6OUxNZ52WB0FERBxzCLequmD3ePPQQREdEHExU078Q0XcNFxF8sBS1YCkyxsoB0FHZ3TsbYbY1Z7zFpToRk09D77Z2XXJNgAAiAdBLJ7lngAAZDuADn/3PY+do2iABuw0R0b0545bMAGbKzbmGWw3ie0CIAASHeAzKYAUXsAB3Dc4Zhm1V0hskdOXSiBkqNWctYL75tBGzV3tPR42klHEws+uu5jOVXb6e1w2ObOWSTN/aPX5MX+jtMwDv3Be6ABGqDZQHP9pUmn/TAaLd4zvMALvGx4eXk7nrzFedqcte93jRYKMzDTeTOzt0xfBm2Mn9nQGPRAD/Tc6bnrz0xDxGFFMHiAx4LHpMX1W2nKNHbD85DoiS8wAiMwsmLkZe8uMTu2lgAJkKwi+XMw/NfoY0jlz2FvXIYnOXwcY4EwlEDJt8gcDTRAc1RoFkGzpJkNaIVppKy3S+9xt6hZT8iGkMVpzn0VQmTBUqJ/smdUrhl9o4hF9VSezFYbVoigHVeGKCRrYqlSRK8dc0lK73MujPO81YbU223EoFWWpgjtGYvK1Nj6tPQ2OSEQOnqnlVQ2RSrUOSjJfUzSOUsXwXmzLbJcUTbKoAwVLeFbeZWloqsKOhcfSEjkgjOjTMopl6jpqLUIpb3UXnGRttowynKbi2qR0gVwdGOgS5ElnTp3dJzKMg+Znk6Z7jHZhkgG6e7DnHQi1XKPDcboBqN9yMFKJZike46UKnm6zpIRDWFVIQJO0vuQJcjIlNFVyBxqbE9o08aLy9OTNxeXr969fnFyev7yfGbh9PLl68vri8krl3++Or/apxqh/xb1xnzMd72ZdX9VMSkKWzg8+BKDAzh8Tw4PCx0HBmBwhAwOCxgHDMBwhBj2DooFB3BwTA5OBzf0E7MQ01Q39EsYlXwWxmHlldcD6ld8QdcBPLrF46IZfSyp/TvTbVMTL9SNKPmEnv1EMq6b8HH0YTDeI0QWkADJMSFZjDStLTOEBEjoqITFmOv8GVQPQNFRFI8RVRQmYOLITAyG417zfvbo9XDw/6b9DKAAio6iaBtNtT/497M/Pwz65br3vplP2WGGAho6o+Fxw02DBVh0h8XOQabBAiyOnsVeoaUhAiKOXsReAaUhAiKOXsT+YaTBAiyOnsV+waNBAiSOkcR8/HVzRBYwAKPDMJ73Gmow/fd0Uns6hTdfCIghKNjotI1vECEaVEClI1QeEBcaSqDk2JU8TjRoSIGUY5eydxRboACKY0dxWOxayICMTsjYP2ItaIDGsdM4NE4tbMDGMdr4BtFpQQVUjpTKbJ/fWaE646bX9Np0spcfS/P79eWrq9LkMkRdAiAAsr4RdpGUHDZgoxM2FgHNuWtX5S6myS/o+s/65TuFM4cHeDgqD22Pov0zf++VYRimD19ezyPYtuHYZufw09GoopSorMiWlcpqoXKWmePFWlM5fQA8WvpkktxCw8giojCu0tkSLZNDkIlO3HEnHKsi5knB+woNs50GvbNao7U8pFpFrsarrEIIRalgspbG+RRFW841t55OUhGl5FVlwTor9LYsGFReTORBaW0IeyTopeZUXPKVGceDJoh0Oan0aUGcjeIy5upMNDaaWLfSEEznqo2SVVVLpVaVyLQI0gQnLNeMUVkvkUtO9wvVXiHmVKW/m7QJwQh/D42kuK02sBJNztFzKgKKKxIuqq5GB1ZTLK30GFUphq5J4olXujJOB3q4SeOMivnpmzYJxqTMk4bzdxev3pz/djUVc/621UIqfqcfa584MOL/2TBUAjP5mcnj08FgmHvNjts6zHYaD77coAEaP5rGA5JhgAVYHBOLWbCdk5TKaDQP/HxdbkIz7qWVZ/cJRQUlUHKESg5NHQMO4HC8HA5MIQMUQHHMKCYSLujlcZuEEm0meOiyh/1TK8EDPBy/h2kIKqiAik6reOzEY2ACJkfIZMucHgZlYaLTJiYLzOfBd5a/gQ3Y6LiNl4Nc+sv1xdJGpulrsAEbHbVxeJ5KiICIYxbxoHyVwAEcR4jjUfJWwgZsHKGNRaq+82EYTTYoNWhGQUPXNRyWuBIqoOKYVDwvod3bPaJWE32gV7dNU4bLjzH3DRmQsV3GYsMebMBGp2w8ctpj8ACPzvHYPfcMeIBHV3jslwYZMiCjKzL2S4cMGZDRFRkHpEUGD/DoCo890yODBmgcP40/yrAp/RUgiyC2CkZgpMtG2km/0oznX+dzgHtEeQYQAOkOkGnQZwQSgQzImMmYJpaZfjNJV4aFuDACIxMj8wWH0wW5J/0+uuZwARdrLi7u6g7AAAzAIBjTUav5txMmGLWCEihZUXI5/PghNM97/XLaL6G5/Yj2FYAAyB2Qja1PAAIgALIZwG2R1m/3POIgAiJHTGQlntuvVBz7Ja+EdQvj0B+8BxRA6TaUlyX3wrP5D0ylYDALMDoPYynI4bPT2+GwNHdxD8d/9Jq8aHShLgEZkNlO5vpLk077YTRavGNogRZoWdMyD5E4iwa3/v2kQQYxEAMx94mZvWH6MqDr8GU2Ygw7sAM7czt3/Zhr+rRvAoJmAQdwzHBM2lq/laYMJ+/zeUj0xBcIgRAIWRLysvd+uBrVHURABESmRBa5D/4c9sZliGl5GIERMrKc/2C69Wo5CcKWp0AGZDpG5qqMqOynMlosYon98svnRIp6zfsRJEBCNyS8oXMePbuW7/hkkeN0rGryJOoESOigBEMSZivhfxuGjx9gARY6auGtf8f1LG7DVall2L76ejj4VJpAjyADMrorQ4jlpe4nifoSo17s9XvjLz8fDMNFSpZl540IKlB5YSkL+hucWZ+SlkLR31VbYKhgpWKRazpHX7yRUlQZLfNZ0YejZJBUXHkI22G47TCsdzFZLX0IwlfJdNGpKsMCkWNGJ5uk8TxWw2oMLBNOE7USSXK6WkXHLTAsl96oUnWWjueshOFes8w5kzroJFjIheeSSCHX9CVm6QsP0XotlTN5K4z2E7HZ0wl4ZoLnWiThOZXKooK0hJalyMietcIakwxj3ITqeTLC2hDUPTAEfdpe0X3F8KwDT9aIXCR9yqFkutrC5pJzovsZ3Xuk8vRdVZZuHIm5bFWymzBOTk8v//HqzcmvFy8u3vzz3cnpm8urd//nHycvLp5fnE5tXL86eX3998s3+/Sm6b/FiNNmatrp8OwOg0xuu4gHX2WIgIjvLGKWYHClWnh2TV3rZtxLK8/uEwsLQADkuIDMIvDOe9wvSn5PVYWABEjopoR28o6K0M2kyz0NRb1LKlp4gIej9PBWzVKl7bwCChRA4bgonA5u6CfmvYgraiuFUclnYRxWXnk9oE74F3QjIKRzQi6a0ceS2j81jYo4IUNdipJP6NlPhOO6CR9HHwZjdLfhpLtOViL2rITqAQuw6CyLxZzF2gZXYACG7mJYTODNn0ElARfddbG8rWJl+wRYgEWnWQyG417zfvbo9XDw/6ZdcbiAi+66uC5hmD7MvoACKIDC",
    "5MvSDu6Xg1z6IAES3SPR9q1rf/DvWaNpPjsBC7DQXQsbqWiw9AkgugRiLZDHbAnUbAFUaAYNvcH+WUnUbsJ+CsiAjFUZ5w1kQAZkLGScf550LnZM6AcUQNEBFK/p3/C+vA39ttgMUF1ABmRMvsw2HKG+gIpuq3h4cmTYgI3jtPG819wtIV+dvUD/Gzy6zuPxciLDCIwcp5FvkfUVWqClM1oekvAVUADl+KE8Uq5XYAGW48eyf6pKuICL43dxYJZK4ACOjuA4IEEldEDH8es4ODcleIDHcfL4FmkpoQVajlbLLKzCWaGa46bXUNXSS5cfS/P79eWrq9LkMkSNAiMwsiX0yFV5T1yGCIYLHt3lMQu7MGlYTR9fUKXxGXMfgAEYi3gkExNXJd72+vl0MBjmXoNdIQDSLSBXZUR97lRGi/WLsV9++ZzIDDWvRkAABEeP4PEyuz4lE1Ipuu5URHIwMqjshQzOO5kK95ILZYxjzsUtJnSlEkqcZOHFhuiipo9HRJ0yZ+1rhERrxep2E367CRaj0tVr74UvMYZotFXKRVeYKDkkKinJ2FhsLS5oSQXY5FRzCZbKePLbTCRuowrZO1uytpUeKxWpdOVAB4jcZ18CK4IOVCSZ9laamo1hdP6My0l24k0TyRZRNb1r2xbBnJQILLKk6RO0siQXMglNxihBxk1Q3OUcireuFsNDEfeYKLJGST9Pb9orWU0tTAlesqFbkGKGTjIzujsEyWymO4ijwlIqU56T4hTcNhPX1+dv3l2fvzx59ebi9Prd9T9+/X2SA/nk9I+T387fnbw6e0c+zk//efri/AfkdvXbTTz4OsMETHx3E98muyuIgMixETk0vysswMKRWjgwwytEQMSRitg/xyswAMOxYXjsLK8wAiPHZuTb5HmFFEg5eimzsIezeuXXHhWe5j1wAEcHcTxKGmTAAIxjg/GARMjgAA5Hy+FBqZAhAzKOTUbbmxgtdTJmvYs7FpjiAwuwWHS6Z9uRoAIquqdieef3yg5vtKIAo+MwvrKBFTIgo8syVrboAQMwAMPsy1KUqZeDXPpAARRdRLHIGr6agwYaoKHLGjYylmFxOUh0i8ROucLPyq65ymADNrplY/c8frABG52wcf550snYMfsrWIBFJ1jM5rffhn5bcAaoMmADNmZfZpu7UWfARdddzMeiNkenoAM6uq7jea+52420OpuBnjiAAMjKdr1fqSz2S17Ztbdz8mMogZJjVTJdez7jgSXoQAIkf52j7/R2OCzN+C778R+9Jr/o1ZK+pH5BpQIv8LLFy/WXJp32w2i0eLugAiqgskxlvk18ntxy7ftdUzCBC7h0gctdE+yaPuqbgACgkAEZrYxJTfFbacpw8iafh0RPfAEP8ACPOY+XvffD1aA88AEf8EE+1vI0neTwEemaAKTbQJbDkUymEVdikmx5Cl7gpdteZlFKzgrVHje9hqqXXrr8WJrfry9fXZUmlyFqFSiBkq2xfBZT7wACIN0FMotiMmleTR9fUMXxGXMhoAEaSwF+JiquSrzt9fPpYDDMvQZbq0Cka0Suyoh636mMFst/Y7/88jmRGmpkjcAADDrA4A2d8OjZW/+O83Yh77wrMXka9QEgdBCCayEslule0Icwm/4DCqDoKAohlvdDnSRqNo1m+WJ/OhWBClYodHDjpJRVe8VKDT7SeaRqHafjUnEReouKkLyWvqZYcwqBOW5CIkb0IVVGULLmWhqe+FYVim1XwbWjEmo8lYYQmWbBFeuVjVq1RTpysuIMi4ZbIyr9qNfKp0rFJ0VhZNymooYaS2Ip5Vas0VVKngKVnRqsklZypqrkVbrIY/tXM7lQWnEWsxPJl60qVKBPJPvoVajM51Dp3SYqyCoIbqzMKbKgNX14gVtHtJwrpL3IUjMX0tv7VNBJGbqqutBx6IoKupIh1MQ5vUInqF12JMN7a6zSnpfkOb3NqnKUlf7GpoozKtwtgqvzSUm/vnhDEv7x5u+XVxdv/jkxcf33Eyr/h/Uf6L/FLN9mHqfpfPj9fepJodgC48EXGzAA48fAmEUMXakknl2Xm9CMe2nl2T3irsMJnBynk1lMn3nAkhclv6eKQwAEQHQaRLuKihpSN6UZzyJd7RJpGizA4qhZvFWzYLq7rkWHCIg4ThGngxv6iXkP44oaUGFU8lkYh5VXXg+on/4FXQxA6S6Upt37Ov/aDuVSe+plaHqV3hd64SACIqtErkotw/ZHgAM4Oo/jLtjbH2XYlP6k5dUv45JP6NlP1MaaxxMFF3DpPJeVcKIrcUShAzq6rmMxVz5/MHtfMAETnTexWD8yfwZVBnh0nsc08vRGyOk7G5gthw3YOCwcO2iAxnHSWI7DsxJvB40q6ICORTyR+YtnZRx6/dYAgAAIgHw14A54gEfneazEFIEIiICIZRFLUXJfDnLpQwZkdFZGO61R+4N/r2WfBQmQ6DyJjZTl2OYEFx10sRaycLbdabbZKTSDht5n/6zsmK8cQACki0DOGwABEABZB3L+edLxKMNPvYTWFWzAxp2N2ZKRt6Hflp4BKg8AAZBlILP4I6g9gAM4CMd8pGpz7ApEQAREiMjzXnO3B3B11gNddCiBkomSlZ2yv1KB7Je8smE2jEN/8B5UQKXrVKb7PGZGsN0DUiBlh/zkp7fDYWnGi6fGf/SavMjtgeoFaIDma2iuvzTptB9Go8V7hhd4gZcNL/NYDbPdhevf75iAFmZgpjtm7lpk1/R53wSEsQYP8FjwmNQZv5WmTDMPPg+JnvgCIzACIytGXvZmyTmRDwFIgGQDyVpCwpMcPiIvIZRAyUp0oMmc40qIoC1PAQ3QAM08JspZoXrkptdQRdNLlx9L8/v15aur0uQyRP0CKqDy9fBBi8l6KIESKJkpWQSFwDYU8ACPKY9ZSKFJZ2T6+IJaWJ8xpQgf8HHnY4nGVYm3vX4+HQyGudegHoGTTjq5KqPB7TCV0WKNfeyXXz4nokONrREswEJXLLyhsx49e+vfCbG8t+QkkY7RLEf05GdQTYBGV2nok9vxh8GQKJxOJgrpj5/Rv58m7/Kn06G0C9xnUTI3Thi6yjLyVIxztQZFhdwVKpTab9FhVdI+Gc+TFUlmaRNzkSUfdJbcZSO1Uyo4sV0H365DVu+s0XQyjhcVrE9Jp2KZ0YnKsLfMy9Ceok0u2BroDAhlDoU7qYll2qJDBMdFtiqXaiPzRUnpg/eek2yyz0Ky1ZsQrWZGiJqoQCYSKhxzinyrrToSU6oyravVObv2AxKhBJujZVyJ6GwxtkZJmquoJhivYqh0qVmVLDDG7tER6UdUds4ISySYzazSvUhrujSB7ma20F/kXNG9zJJfVlkIKdPRdamFWeN20/H8H69O31xcvjp58e761cnr679fvtmn5UT/LeYFN/OyTafRd+hS8O0aHnyFoQEavqOGWbTSlcYSdbdvQjPupZVn9wkBDxzAcTw4ZrGC5jFQXpT8nqoIAQVQ0D0F7bIqaifdlGY8C5u1UzxrWICFI7QwAXBBL4+phYSGERh0kcFbNQtSvfMWDTAAg6NlcHHTLnkCBmDoIobTwQ39xHwk6Yr6zGFU8lkYh5VXXg/6vYQWE3R0S8ddYLc/yrAp/QmXfhmXfELPfiIY82WyGG6FkW4aWQkauhItFCRAopMkFvPU8wezNwMIgNBNCIsFG/NnUDnARDdNTCNHb4SMvgOBmWqAAIh9YqjDAzwcj4flSDgrEW/QZgKJzpKYhSWYv3hWxqHXbws+VEBF11Wsh7SBCZjopomVCARgAAZg8GEpAO3LQS59cACHbnFopx9qf/DvZ+fDMCoXTZvoAgiAoJsIVvMfwwEcdNPBnx8G/XLde9/Mt4piaxwwdAXDWuS+2aaI2c6g0AwaenP9s5Kow4D4GlABFXcqzhuogAqomHw5/zzpTJThp15C4wkgOg9iup8UIAACICZfZuv59kkkARVQceQqZsFoUE9AROdFTDdXr7hYrP5WoAEaHaQxn5OYTlmf9PuoKcABHJZXcEzSbsEDPHTZw7TtNP92ogNtJ+AAjknYgfUVHmhEwUV3XTzvNXehmlZXAWJOGzS6TGMlitmvVAr7Ja8EMwvj0B+8hw/46KSPaZCOGQzE6gAP8FjhcbfF7tnp7XBYmvHiqfEfvSa/6NWSvqR+QUUCKZCyIuX6S5NO+2E0WrxRIAESIJkimUfMnAWBWv9+MgkCKIDSeSh3Da5r+pBvAlK5wETXTUxqh99KU4aTt/c8JHriC2AABmAMy8ve++FqNHLIgIyOy1iE6v9z2BuX4UkOH8eYGASNjtJYjsY8mRBcCcm85SlIgZSuSpmFoz0rVGPc9BqqUnrp8mNpfr++fHVVmlyGqEngo/M+1sM1L6bPQQM0uk1jEZUQu8VhotMmZiGcJx2M6eMLakB9xnwfUHQexZKHqxJve/18OhgMc69BjQEc3cFxVUaD22Eqo8Xy9dgvv3xO5IXaUiMAAICjBvCGTnX07Nq84/P9fb8Nw8cPk6dRB4BAZwi89e+EWN6udJKoVhj1Yq/fG3/5wR7+62//UdtDnhIKOqJhs+9H//G//++mjJXzYv/rlLXnVVdOiWkR6WRE5jnRxZZJtafhkqUL70KishR4Nd5WlpVKQdJ50Skqp5hPRSdDBxzQ594PH1/TRW1P47+m13d+hi3he89LbJ5X4XRKUnCps2UyhdgWnSIVY3Ra9PeLjKwwGXgmTD7k5G301nHCJoRO952XWzsvseN55eyTLHQLCVmmWJNmnrNsI51njcHJlHOgD9UXSx+ecjzQOWauqs4E3giz73ltv15q47xMNbkWLbQojtEtjG5ZWqZSA1FSNblkFN0UdNVRJzqzapSLJThD70QYVtx95+V3ul6b5yWijIULWTSnkm5Ne49iybFcDNPZpSAqFaScrKfbbeaFBZWq4FTGeDKOlX3Pa/v10pvlK9a2tNskLN3SuWfOZpcJg7c8uhrpcyZ79Mn5UJzxjq6rZ9bpUEvwdKe+77w42+nEzMaJpaB8TKkt95lOjhy41N4bqNg7poKJbYHnMbrAHH2mUQr66UwVSPCBarvwOAXMbp6XUUUUk5xQ9KeUau8ExslqcwiuFCEDi1YZTrc1QXWco1qPq5ToVle5Uz7fe8F2u1O4zZJPf9AGuhS5ZkHVa8yGKv8QmGa8Vq6p6KWgDd0WDJPch0C3E148j57xUnm878SE2OnE/MaJWS5dVMrSvSrS7YBKP92zolCSir5yVbPMdFS1tg2NSpfOqJgyfdAsaRWlubfoC73LiXG2cWJVKmofSeJPLYisa6VPylCx89G5In2yJrLg6SaquY9R0wcuWBBaCWZU5mnLFdvsTj0voR1kGD07bZtEV7dNU4bLjzdXiR1wiMUwxewga9eH73R9NutEbRjdtTJTjGeWgzKxvUN5ukxO0a1L8cK9o08qxeICVc2cW8npthayoYIf+S7XZ78IZYeUSL5ZeSUhMxU8QzcRqhRciWlys/Ui68RMobJqBK9WEF2q46XjvGjvrQha0u3Q5Eep7LncrFSDz0XVbLXidIcJku5uoi15QjmvqCalGj/Wtsg6Fj2dPJ1Y8NrpZLPWO9xb7r9gfGvrSJjqeC1eGENXQGnW3tyEVNRcrU7nmirVD4lVKwW12qT3OlWTIrPeS2F5PKAk7LYK/9HWLe9da/GtzSLq32S6rcSiqIow1NVywWRiQb0asiMtVR2RR11izYZTq16JQMi8pvu1pGreH3ChdggU/hhBZB8cW/Dh0dgeL0TPXkFNlr855LReltwLiyTj0+3u+x1hj9X3+y4YmK6g+cu7LN/JwubdTEq6XSmhoohU8VMHz1A7QztPvXm6x1F/SnjHdfHUaafePvVYmKB2kqDbLmtvbfqhFg4syN/5xvO3R1xivnYT0zt9cJt9FWonUjOy2Ez/cBWpJtQuM8OofqyCWtvCxEhdFlVCMrkkSd29XKgDTZ8gi5rXh35w29N/fO/74FdDzB90lTd7XllSVUodvhKVoV6fL9EW40TRJlObK+lIBES1iSu65JZzHakiidlzly1zMuxylWfZ6Wbvawbigl4e98bLK4Pu+cW3apat6P7G6oHJjo6pfPztu9+mftANRuxW9Df79p5T/6lolYSxSTHTDvMx6ip7wTizjFMjKVZpBXUpQqY6wWfrow2aUTvTcZ/2L/rzhsCLkt9TwRO7lvx2pXZI5YbEzIOIL+dzfALgZr84TcK9yEM5/fbe31qkrZxfn400xgdmP35gnszHyiyI29OPuj0t2uKr8g5s0D+BPsXl8OOH0Dzv9ctpv4Tm9uPB5/Lg3slP3EL92yHzrau1jnQ71TqbI7c1UA9DUctVcu5L9TY4alD5mHzRTrjoCpdSOG9UqoaqI+qjtz2UInwKTqeyR61zOrihM55NlVE1QCVmVPJZGIeVV14P+r305THvM2uXSt57qcTW8R6tY8rMGkXvP1N71MechXFWVaqHmbU+2eADoy6ATKIU7oPKmuekeVJGB7bLpaL/Fpug5vFH1jcK7lCjbP7q/JlF2furo+w/uPq9732Peru4dyPm/uMHqf2kv+x7UgeMQ+idCvPmmJzXnvqnnglTauEiknQftU9UtnkMzimXldJV5mQcj0a2s6uJU2fMMxZCqd+xMD9Kq3P/xuPaL05bH3u0PedveP5gtujh2+tFsxDNwp98qPkBYbke49Azqmu38QP/yE/fGH1A1blaWWm2U2W1OWguWCiiBil9ZLkWQ+2s6oxQXGd6nJ02kkWjFHNcMCOrScI6rbm1tvBS5PcbGtm/mnm0VvHD650fN/CxPJu0+6Vb/PpqhH3UjagbMWSyy5F64X0zaEMHjJYeT4vdHh/zo84LHxi1Fg2Kn7hBsd7t/XuvvVV8uW8Jl3Y7NSc2p3JrCcbrYqNmrIYcoxNRVaUtY0l4Tv9LouTIKs+Om5jbiflclK/acl5reMgSLjSN0TTeNo6jdirLest6EhOyMSw4k6JkRZVgqbXsfQpc2ypzDCHx6nzO7VrEzKq0ORvuhQlWhvQ4yzX3Hw5Ey+upt7wetVrfKyHWo9UXT2vk9m+PEp1jbTLD7nTf2FxtED2zQlYpVBFcmKJrYcpZVzRrt5hFkxj1nV1sV/gap6irnYwXgsncLlXT4YlOZqzdVXe7OpuzYqIIL0PR7WL8bGq7G89JxnwIWTkWZYnCupjah4kuihBWJBMrl5yuE+fukGVI33d0+7ClEQ8cmf5h3X4stOjoqMHjLnp+aMX1c3duu9xa378FQAWu17YknkarZNf2xI5D9Jsb7ZQzxpvImGKCVx4087pmxXPxIvKgog/0AyJl74Iqykhqb7QLJlIxVaSiH39b1Hcb/zpI9UENlc1thIEVKTOzMotcg2Imeq1YCdwlLYo0wpksqKVSvNSMpSqMYlLbpE271cbyJ7B85yEZ3Z7ADfdrd8VD+vdbtmP6TKA0c9K5wk1l1G/3trbhHXTM9DHWWFwpxXipYlsAki4lUoPe6uyZzvduRd7xxDZXQyUfS/XUIYjGlBJccdwoLoNR9K2uslQtWQoy86ytt7EomVxlWnIlmA36EU5Mbl2mVUNxwmZp2234NVQZ6HI5HWXUzJoctWoXUnvBqYXfbtqTtthEF5EpUSPP+0wWTnN1biTpvGsL3z9v+JVDbMnz+eiJQ78a4YLz9pfmv/H1RYc7fkSbi48Ud0Ja46nraZllij4Aw5VKkbdFmG5oKaYsVBWe12Sy1FF5U1yl7ikTMe6zy+PuQvxRhk3pb7vUkzvZDt2HjWOtHuFXuldRXbvDgR5Sbh72qR/0AW5OyLuihEqsMMtddrkqLmyge4GySlHlT18rV4l60FnIapxKidH/VDVRCx2reST8akuAhBoZZ5oaGqxEq2q0wbPKHNdK+iyLjO3yVd7uz4p096oxFJW9cpn67cakRzqxzXHaakq7R5kpz6hM0wVJnMmkk+CsvX3rKAzduGqkCtwEOnsXigxUQecSQyQce1XUkwG6+dc2",
    "Wg01+F6GhurR0XifjvrakV4P6RSaMIkwc/BBrkotw7LrMdZK+9qx5ofYEtZ5zyO1Y5rvh/dsR/nKIaaZCQZ3o6K7vLO7m61evzB3l/nBt94tEUSocSBzNprqakuFKxUR2GSzXc7F0k1Z6SxZqD5qm7UISpbCVQhZVu9tFg+59bbtRGqyl3xCz36iiz3vlexTnO76NPMXz8o49PptoKXDjrMeJPyQgrl/SP4Dj/j67PmDDnZvRPSDytnmCCrd9oM01VmvEtc+iXZfW0nMaOqj1GqpusjeU9UhU2Uq6OgivUDtL00VvTDq8O2y08K2Mny0eJNq/xGk6eHm3066mgccbrnHMD3ixoTq2jEP+hw2++XOZ5ME1cgmtUEqVKC6Rqe2KWVSkoaZIttdyj4GFqif7lhOtp0HkIpV6Yo5pk0L3yCozPcfnH0qI6sPXkr1RPeOHflA4Leenvyrlo5ry+5iNGfa5Jr4/ot9bWyn+97mwJgKKQhq4icvq5UmGNuG48mVlWyKcDVYRi9m6WqUdFP0OjNppIlW5Db8QP7++1t+zG7sn3rB8uNMRy4nHltJMLbPQVbipR/8i0s3oumMLCY1Man5+FXv47Rpn3pN/hNOJmD29sfN3h6cfPKR8ss8akaOtdCLO7Witsw+2eJZG5jPWZ7MJPKl122AZ5sZ1zpI3gYGZcwnQ915JZmMLARjnLImO1bvDRws/E4ntmX2SQfrfJQlJVG0Zkwzybyx7QKskNqQvUL6UHWpKRkZqWQkVoJgwogQfObfsXn3sObF49eKhxf1tRhfcqfPbnP2J7Js6WMwQXOWjbCymMR54VlxFqI2WrA2dLc2UUtVrVXBW2tddTVbKlXm+LeeP/Iyu93Xyf0MYyhPqE15NKvcvsVOsG+wWA5NOTTlfmhT7kct89e7NeC2hJsNLlRDraSSVBvVRdRcnE2KR2qmacVYSSILFlxyzHqTvFdaax9NUkn57xrmZSWTCjVzb0JD96CVZ/ep/boS4/CBYWoeezTv20z6LmfcWflmn4Mcx0DjE5n/fjrDngeGnMDmEYyzfs91BE8g9MQjD/s+rb01K1XEbD3kSk3xGJ0EdEDQAXkiHZDHX2d279Kwb7VC4CkMmP/tkKS/B6VJfXhiya8fQZ/cjj8M2nWsp5PCS8c5o38/3bPKwvOdupeby61jYKJGI6K0NVXO2gxNyqpUQ5DGZB1ESa4a63QKnAXteM1esWiMkkHsttcC3Ut0L9G9RPcS3cuff8oG3Vx0c9HNRTcX3Vx0c9HNRTf3+3ZzOd+tn6u3hNlo05cnpmL1jPq4QeesBA/Ja28la7O7GFNM1TJIlqSyyatkla3eMHrdfY9+7vLvt7/WNi/KeOnh3Q7gncoF+s3oN+971G2F7Xt3w+8C262eySG9QPTp0adHnx59evTp0ad/8gtmMTSAoQEMDWBo4PGGBtYO95e9ysWtYIfi8hMOOfjNd/z1gQZndhpn2IzOxJ0qSZmgS7KBcRucilFWH5SzSYeSeNaZV1mCZ1lbYb2UMhUWgg6mqH1iFz5yv/5hfbdvX5M9NDjiwWX2L+MpPrzMro1wuZ0K3ma4pmjNJCGOMoWnyoWOri1poTrHuXYhiJC9rjZHqaLgTAWjYk7GF504vfYjwgTt3yd/rN704iBLMUzOPy0FpBv9wF7MsUUXwOa2p9ey3i2E2Q9trX+FKQmtg+HNLIjl6Pbm4Ibtuv27ZuPDD7g0stYO2Xwc9GY95ye6D26vJvOsLafeydUAWV+v1tRu2982o9+VQFWatLpmZ4MNMfI25p2XNbYRs7OwSYqQEqs51uB0DFwoF4ULIgZmQtm3WjsbhkrvbfIzk8c7NrSxxhFzNYvjbSlED5iSeQrxrh9zYufusvyUEzo/NmT8k2oH//TzQdgIiNkUzKY8nR7aRsW5z5jkTzYz8+DxrK0HnP3++adB/3bS5Dv8Aq4c8Do0OQ4+T6ee0U1+Qt1kTGphQOHIZ/W+b/6Epx2M+2lONM5GhCbTJG8G/yrNLnMk1/Idn9Ty05vVTr/yl2NOjzrreO3e8Wtqyze5fVP/WYaD53QD2nHu56AJo93Cqz/6jBOzO43NbYnQHqWvifF22XSQQSema7VacS+k8ULJpKnCZJkJ3i61zjUJnrOXkaWcVOTYO4xxtae4BvrYBtwOTRGOEbanMsKG9d9Y/4313xixxIgl1n93af03ht8w/IbhNwy/YfjtG4UA+MG7+cUuI09iM6tNZVIKldrgdSZxLUWyufBquNFCByG1EpqXXES1xdRqYxIqaN6mI2FaCIeRJ4w87TXydEwZ2deO8bqFmr68GYZm1FbEDxo6w4AcBuQwIIcBOQzIYUAOA3IbB1urt+eF7oA+0NqRpveye9pkXznEtN85uBvcO2QPHIYaMdSIoUYMNWKoEUONGGrEUOOTG2rcKU+12MxTHbzhSSqTRAgqGFcjdyX7UL1Q3uaSuWRF2iJEbL8xwftYRSy56uKCldiAiuHKn3wDKgb1vsO2VowMYmQQI4PI7okROSyRw6ZebOrFpl4M9WGoD0N9GOrDUN9Pl1gI+4B/wn3AYqfcSkJsDJEmqQqr1nNrkhdchpiUsbUKVky1TDiRS5bcRc+9NS7HmpVmxjlZk6iK7RHzGOOJO/36w0ZE0CPudI/4cXp9yDyx76EXHZHU3g2/zAoBOg1PPL3FotaVZvbRhWlV+7YMF4Xx69Wu3inTgNzMaGiU5TYXlUKOXFFtqmLQLktpCnc55coyD5meTlkLm22IqoZgOXPSiVTLd9wD8UNr7f0r358jbMWxZbZ7yDQHxv470tJ5ojm90dhBOwRptnbIGfAYoxuTzXf043/vUXEYpg9fXs9bB229Ohj17mlw7ZRhR26mdhJM56qNklVVK6VSJTItgjTBCcs1Y1T/lsglj4V+ghplzKlqSk3ahGCEx0owjNz8XCvBEPX/cRu73zlcPfa8oZWNPW/Y83bA2qHL4Ue6yT3vUYeFaqDm9uOP66g95vKhx1/x87LkXlgs9Zwecr+PEH1HDJR3o4N68HKCA9YHHJhnmOv1kCp3AVq+bRBuvVOvdDNBXtv3tNlnIz0zwXMtkvDc6VBUkFZzy1JkxSVrhTUmGca4CdXzZIS1ISiEQsKswqN3+TA18ZR2YGArxbfp6GEuBJElMLuC2ZUnMLvS2VgBq81oI3dqRW+mskm2iKpDdNaqZHNSIrDIkqa2tZUluZBj0ckYJVxMJijucg7FW1eL4aEItKLRin66G9SxSxx9AvQJ0Cc4pj7Bo++0RScDnQx0MrrVyfiJtufZnbo2ajNXggrUgck+ehUq8zlUzXWKMqgguLEyp8iC1tTXCdw6KbxzRelaZKmZC+ktujY/adfmm+UsOCjdAKYrutU/QvQr9LPQz0I/C/0s9LPQz3qkyDQIH/1jwke7nTZpq83o0YkpVZnW1eqcXdvjEqEEm6NlXInobDG2RsmFr6KaYLyKobrAWZUsMMbQ+cJ+H6wKQzcL3SwEGcYWKAQZPr4gw+j/ov+L/i/6v+j/3rMJ6sAdTQdNNnr+P/+16HkutihxSz9EXebh5b+bkl8v/bh3f/uP2yZM+9b/XfLlym+y//n/Mi8+TA=="
)


def _load_prior_fence_proof() -> dict[str, Any]:
    raw = zlib.decompress(base64.b64decode("".join(_PRIOR_FENCE_PROOF_ZLIB_BASE64)))
    proof = json.loads(raw.decode("utf-8"))
    canonical_raw = json.dumps(
        proof,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")
    if hashlib.sha256(canonical_raw).hexdigest() != PRIOR_FENCE_PROOF_CANONICAL_SHA256:
        raise ValueError("C23 prior-fence proof digest differs")
    if len(canonical_raw) != PRIOR_FENCE_PROOF_CANONICAL_RAW_BYTES:
        raise ValueError("C23 prior-fence proof byte count differs")
    return proof


PRIOR_FENCE_PROOF = _load_prior_fence_proof()
PRIOR_FENCE_OVERLAPS: tuple[dict[str, Any], ...] = tuple(
    PRIOR_FENCE_PROOF["authorizedOverlapEdges"]
)


CONTRACT_NAMES = (
    "FieldReferenceReleaseV1",
    "FieldReferenceBindingV1",
    "FieldReferenceOfflineReadinessV1",
    "FieldReferencePackCoordinatorV1",
    "FieldReferencePackLifecycleAdapterV1",
)
REFERENCE_KINDS = ("SOP", "MANUAL", "DRAWING", "SPECIFICATION")
PROVENANCE_KINDS = ("LICENSED", "SYNTHETIC")
LICENSE_SCOPES = ("LOCAL_USE_ONLY", "CITATION_ALLOWED", "CITATION_AND_EXPORT_ALLOWED", "RESTRICTED")
RELEASE_DISPOSITIONS = ("ACTIVE", "REVOKED")
SUBJECT_KINDS = ("WORK_PACKET", "ROUND_SESSION")
SUBJECT_STATES = ("ACTIVE", "FINALIZED")
AVAILABILITY_STATES = (
    "READY_OFFLINE", "MISSING_BYTES", "EXPIRED", "REVOKED", "SUPERSEDED",
    "STALE_BINDING", "PROTECTED_DATA_UNAVAILABLE", "UNAVAILABLE",
)
INTERRUPTION_POINTS = (
    "AFTER_CONTENT_READBACK_BEFORE_RELEASE",
    "AFTER_RELEASE_BEFORE_RETURN",
    "AFTER_READINESS_BEFORE_BINDING",
    "AFTER_BINDING_BEFORE_RETURN",
)
EVIDENCE_IDS = tuple(f"{CARD}-{suffix}" for suffix in ("G01", "A01", "H01", "I01", "R01"))
TEST_METHODS = (
    "testV23P03C23G01FieldReferenceReleaseAndBindingAreCanonicalAndOffline",
    "testV23P03C23A01AvailabilityExpiryRevocationSupersessionAndCodecAreExplicit",
    "testV23P03C23H01ForgedBytesWrongBindingsAndFinalizedSuccessorsFailClosed",
    "testV23P03C23I01ImportAndBindInterruptionRecoverWithoutPartialCanonicalState",
    "testV23P03C23R01V22BackupRestoreExportReplayAndRetentionRemainBounded",
)
FORBIDDEN_CLAIMS = (
    "RUNTIME_WEB_FETCHING",
    "MUTABLE_URL_RELEASE",
    "UNLICENSED_SOURCE_BYTES",
    "STANDARD_DRM",
    "CLOUD_DURABILITY",
    "NETWORK_STORAGE_PROVIDER",
    "ACCOUNT_OR_CREDENTIAL",
    "EXTERNAL_DURABILITY",
    "AUTOMATIC_COMPLETION_OR_COMPLIANCE",
    "SILENT_RELEASE_REPLACEMENT",
    "EXECUTABLE_PLUGIN_OR_MARKETPLACE",
    "SECOND_WRITER_OR_STORE",
    "ANDROID_WEB_BACKEND_SAAS",
)

REQUIRED_BEHAVIORS = (
    {
        "id": "IMMUTABLE_CONTENT_ADDRESSED_RELEASE",
        "contract": "FieldReferenceReleaseV1",
        "requirement": "An offline pack release binds every required immutable reference byte, manifest digest, provenance, version, workspace, and release digest; successor releases append rather than mutate the original.",
        "evidence": "C23-S01",
    },
    {
        "id": "EXACT_WORK_SESSION_BINDING",
        "contract": "FieldReferenceBindingV1",
        "requirement": "A work packet or round session binds one exact release revision and digest, with predecessor identity and finalized work remaining immutable.",
        "evidence": "C23-S02",
    },
    {
        "id": "EXPLICIT_OFFLINE_READINESS",
        "contract": "FieldReferenceOfflineReadinessV1",
        "requirement": "READY_OFFLINE, missing bytes, expired, revoked, superseded, stale, protected-data-unavailable, and unavailable states remain explicit and fail closed.",
        "evidence": "C23-S03",
    },
    {
        "id": "BOUNDED_PROVENANCE",
        "contract": "FieldReferenceCitationV1",
        "requirement": "Reports cite bounded source metadata only; restricted content and unlicensed source bytes never leak into report, search, or export projections.",
        "evidence": "C23-S04",
    },
    {
        "id": "SOLE_CANONICAL_WRITER",
        "contract": "FieldReferencePackCoordinatorV1",
        "requirement": "Import, readback, release publication, readiness, binding, and retry receipts use the existing sole canonical workspace writer and one local transaction boundary.",
        "evidence": "C23-S05",
    },
    {
        "id": "ORDERED_LIFECYCLE",
        "contract": "PERSISTENT_SCHEMA_V22",
        "requirement": "V22/records21 closes migration, backup/restore, import/export, report/search, journal replay, delete/Erase, retention, compatibility, interruption, and forward-fix behavior for two durable families.",
        "evidence": "C23-S06",
    },
    {
        "id": "STATIC_BOUNDARY",
        "contract": CARD,
        "requirement": "The result is PASS_STATIC_PROVISIONAL; native, hosted, adoption, acceptance, release, provider, network, account, cloud, and Phase 10 claims remain false.",
        "evidence": "C23-B01",
    },
)

EVIDENCE_CASES = (
    {"id": "C23-S01", "kind": "GOLDEN", "assertion": "A complete reference pack imports exact bytes, publishes one immutable release, and emits a canonical mutation-bound receipt."},
    {"id": "C23-S02", "kind": "GOLDEN", "assertion": "An active work packet or round session binds the exact release revision and remains readable after later release supersession."},
    {"id": "C23-S03", "kind": "ALTERNATE", "assertion": "Missing, expired, revoked, superseded, stale, protected-data-unavailable, and unavailable inputs never become READY_OFFLINE."},
    {"id": "C23-S04", "kind": "ALTERNATE", "assertion": "Citation-allowed metadata is exportable while restricted provenance and source bytes remain omitted from projections."},
    {"id": "C23-H01", "kind": "HOSTILE", "assertion": "Wrong workspace/release, forged digest, stale binding, mutable replacement, runtime fetch, account, provider, cloud, and second-writer inputs fail closed."},
    {"id": "C23-I01", "kind": "INTERRUPTION", "assertion": "Each content-readback, release, readiness, and binding interruption leaves no duplicate or partial canonical success and remains retryable."},
    {"id": "C23-R01", "kind": "RECOVERY", "assertion": "Backup/restore, import replay, delete/Erase, retention, and successor recovery preserve immutable release and finalized binding history."},
    {"id": "C23-F01", "kind": "PATH_FENCE", "assertion": "The corrected hydration fence is exactly 119 paths: 105 existing and 14 new, with zero S10 overlap and 1017 authorized path-level prior-fence edges."},
    {"id": "C23-B01", "kind": "STATIC_BOUNDARY", "assertion": "Activation, native, hosted, adoption, acceptance, release, provider, network, account, cloud, and Phase 10 flags remain false pending accepted S10.6 reconciliation."},
)

REGISTER_ROW = (
    "| 60 | <a id=\"v23-p03-c23-register\"></a>["
    + chr(96) + "V23-P03-C23" + chr(96)
    + "](EXPANSION_V23_ARCHITECTURE_BLUEPRINT.md#v23-p03-c23) | Version-bound offline field reference packs and work-session bindings | "
    + chr(96) + "IMPLEMENT_NOW" + chr(96) + " | "
    + chr(96) + "NOT_STARTED" + chr(96) + " | V23-P03-C22 | "
    + chr(96) + "EXACT_WITH_GENERATION_REBIND" + chr(96) + " |\\n"
)

SOURCE_PROJECTION = {
    "registerRows": [REGISTER_ROW],
    "registerSectionSHA256": REGISTER_SECTION_SHA256,
    "registerSectionUTF8Length": REGISTER_SECTION_UTF8_LENGTH,
    "registerRowSHA256": REGISTER_ROW_SHA256,
    "registerRowUTF8Length": REGISTER_ROW_UTF8_LENGTH,
    "dossierSHA256": DOSSIER_SHA256,
    "dossierUTF8Length": DOSSIER_UTF8_LENGTH,
    "inheritedV21BlockSHA256": INHERITED_V21_BLOCK_SHA256,
    "inheritedV21BlockUTF8Length": INHERITED_V21_BLOCK_UTF8_LENGTH,
    "inheritedV21PayloadPresent": True,
    "facetRowCount": 1,
    "canonicalRecordWriterOwnershipRowCount": 4,
    "policyRefs": ["V23-POL-ARCH-001", "V23-POL-IPHONE-001", "V23-POL-TEST-001", "V23-POL-LIFECYCLE-001", "V23-POL-MUTATION-001"],
    "contractRefs": ["V21ToV23RequirementRebindingV1(V21-P03-C23).CONTRACTS", *CONTRACT_NAMES, "DirectPrerequisiteEvidenceSetV1", "CardAcceptanceInclusionProofV1", "CandidateAcceptanceCompatibilityReceiptV1"],
    "journeyRefs": ["NONE"],
    "deterministicEvidenceIDs": list(EVIDENCE_IDS),
    "aggregateAcceptanceMemberships": ["AutonomousRequiredAcceptedSetV1"],
    "conformanceSubjects": ["KernelConformanceSubjectSetV1"],
    "invalidationConsumers": ["V23-P03-C24", "V23-P03-C27", "V23-P04-C01", "V23-P04-C27:STATE_INVENTORY", "V23-P04-C29:EXACT_CANDIDATE", "V23-P05-C01:RELEASE_SELECTOR"],
    "optionalCapabilityProviders": ["NONE"],
    "reservedLegacyOwnerReconciliationDebtCount": 0,
    "reservedLegacyOwnerReconciliationDebtPaths": [],
    "reservedLegacyRawWriteViolationCount": 0,
    "reservedLegacyRawWriteViolationPaths": [],
    "provisionalZeroViolationClosureClaimed": False,
    "directGraphDigest": "DERIVED_FROM_C23_PREREQUISITE_SET",
    "selectorManifestDigest": "DERIVED_FROM_C23_TEST_METHODS",
    "relationManifestDigest": "DERIVED_FROM_C23_FIELD_REFERENCE_RELATIONS",
    "dependencyDispositionDigest": "DERIVED_FROM_C23_OFFLINE_READINESS_STATES",
    "impactManifestDigest": "DERIVED_FROM_C23_BRAND_IMPACT_MANIFEST",
}

DIRECT_PREREQUISITE_EVIDENCE = {
    "schema": "ProvisionalExecutionPrerequisiteSetReceiptV1",
    "schemaVersion": 1,
    "successorCardID": CARD,
    "successorAttemptID": 1,
    "ordinaryDirectEdgeCount": 1,
    "nonreleaseSpecialEdgeApplied": False,
    "canonicalRelationPreserved": True,
    "disposition": "PROVISIONALLY_SATISFIED_FOR_ORDERED_IMPLEMENTATION_AND_STATIC_TEST_ONLY",
    "predecessors": [
        {
            "cardID": "V23-P03-C22",
            "attemptID": 1,
            "candidateHead": BASE_HEAD,
            "candidateTree": BASE_TREE,
            "contextDigest": "4e2d0c1f46926387a8e15a798d551744fa23448c4790f466a4d5d3903d026dc4",
            "pathFenceDigest": "c34e0f79176c9213abc467ff20e6f70282ded318b919768dbfd4506883fc2f40",
            "verificationReceiptDigest": "5365dd9ef144d40a81662ba3d2bf1fc69c30761c8905526a5703ad58953bd8bb",
            "checkpointDigest": "827c81d1c99a110f592ae54c03b9953e3800470cadb9c77f9024384e32d9a2fb",
            "disposition": "CHECKPOINTED_PROVISIONAL_CANONICAL_DIRECT_PREREQUISITE_AT_EXACT_C22_HEAD",
        },
    ],
    "prerequisiteDigest": PREREQUISITE_DIGEST,
}

SEMANTIC_SCOPE = {
    "durableOwner": ["FieldReferenceReleaseV1", "FieldReferenceBindingV1", "PersistentSchemaV22"],
    "durableFamilies": ["FieldReferenceReleaseV1", "FieldReferenceBindingV1"],
    "stagingDisposition": "OFFLINE_READINESS_AND_FIELD_REFERENCE_PACK_STAGING_NONPERSISTENT_DERIVED_ONLY",
    "atomicAuthorityPolicy": "IMMUTABLE_CONTENT_ADDRESSED_REFERENCE_RELEASE_AND_EXACT_WORK_PACKET_SESSION_BINDING_COMMITTED_IN_ONE_SWIFTDATA_TRANSACTION_USING_THE_SOLE_CANONICAL_WRITER",
    "referencePackPolicy": "OFFLINE_PACKS_INCLUDE_EVERY_REQUIRED_REFERENCE_BYTE_AND_EXACT_RELEASE_DIGEST_WITH_EXPIRED_REVOKED_SUPERSEDED_STALE_AND_UNAVAILABLE_STATES_EXPLICIT_AND_NO_ACTIVE_OR_FINALIZED_WORK_SESSION_SILENTLY_CHANGES_RELEASE",
    "provenancePolicy": "REPORTS_CITE_BOUNDED_REFERENCE_PROVENANCE_SEARCH_AND_EXPORT_RESPECT LICENSE_SCOPE_AND_LOCALIZED_ACCESSIBLE_STATES_REUSE_CANONICAL_RECIPES_WITHOUT_RESTRICTED_CONTENT_LEAK",
    "replayPolicy": "ORDERED_IDEMPOTENT_IMPORT_BINDING_BACKUP_RESTORE_DELETE_ERASE_AND_REPLAY_RECEIPTS_RECONCILE_EXACTLY_WITH_CHANGED_BYTES_UNKNOWN_APPLICABILITY_AND_FABRICATED_OBSERVATION_FAIL_CLOSED",
    "lifecyclePolicy": "V22_EIGHTY_FOUR_MODELS_RECORDS21_TWO_NEW_DURABLE_FAMILIES_FIELD_REFERENCE_RELEASE_V1_AND_FIELD_REFERENCE_BINDING_V1_GENERIC_RECEIPTS_EXISTING_READINESS_AND_STAGING_DERIVED_NONPERSISTENT_ZERO_INVENTION_FROM_V21_REFERENCE_PACK_WORK_SESSION_BACKUP_RESTORE_IMPORT_EXPORT_JOURNAL_REPLAY_DELETE_ERASE_RETENTION_COMPATIBILITY_AND_FORWARD_FIX_CLOSED",
    "forbiddenPolicy": "NO_RUNTIME_WEB_FETCHING_MUTABLE_URL_ONLY_RELEASE_UNLICENSED_STANDARD_DRM_CLOUD_NETWORK_ACCOUNT_EXTERNAL_DURABILITY_AUTOMATIC_COMPLETION_OR_COMPLIANCE_SILENT RELEASE REPLACEMENT EXECUTABLE PLUGIN MARKETPLACE OR SECOND WRITER",
    "s10Policy": "EXACT_ONE_HUNDRED_NINETEEN_PATH_RESERVATION_FROZEN_WITH_ZERO_OVERLAP_AND_VISIBLE_UI_DEFERRED",
    "activationPolicy": "PROVISIONAL_PRE_S10_ONLY",
}

CORPUS: dict[str, Any] = {
    "schema": "V22P03C23FieldReferencePackCorpusV1",
    "schemaVersion": SCHEMA_VERSION,
    "cardID": CARD,
    "synthetic": True,
    "containsCustomerData": False,
    "containsSecrets": False,
    "persistentSchemaVersion": 22,
    "recordsSchemaVersion": 21,
    "persistentKindLifecycleModelCount": 84,
    "durableFamilyCount": 2,
    "requiredContractNames": list(CONTRACT_NAMES),
    "referenceKinds": list(REFERENCE_KINDS),
    "provenanceKinds": list(PROVENANCE_KINDS),
    "licenseScopes": list(LICENSE_SCOPES),
    "releaseDispositions": list(RELEASE_DISPOSITIONS),
    "subjectKinds": list(SUBJECT_KINDS),
    "subjectStates": list(SUBJECT_STATES),
    "availabilityStates": list(AVAILABILITY_STATES),
    "interruptionPoints": list(INTERRUPTION_POINTS),
    "requiredBehaviors": list(REQUIRED_BEHAVIORS),
    "evidenceCases": list(EVIDENCE_CASES),
    "forbiddenClaims": list(FORBIDDEN_CLAIMS),
    "persistence": {
        "schemaRelease": "FIELD_REFERENCE_PACK_V1",
        "schemaVersion": 22,
        "recordsSchemaVersion": 21,
        "mode": "NEW_SCHEMA_VERSION",
        "migrationRequired": True,
        "backupRestoreRequired": True,
        "deleteEraseRequired": True,
        "exportReportRequired": True,
        "searchRebuildRequired": True,
        "replayRequired": True,
        "classificationRequired": True,
        "interruptionRecoveryRequired": True,
        "canonicalWriter": "V23-P02-C01",
        "canonicalSourceOfTruth": ["FieldReferenceReleaseV1", "FieldReferenceBindingV1"],
        "persistedFamilies": ["FieldReferenceReleaseV1", "FieldReferenceBindingV1"],
        "nonPersistentFamilies": ["FieldReferencePackStagingV1", "FieldReferenceOfflineReadinessV1"],
        "currentProjectionRowCount": 0,
        "providerRows": 0,
        "secondStore": False,
        "secondWriter": False,
        "downgrade": "PRE_ACTIVATION_ONLY_FORWARD_FIX_AFTER_FIRST_V22_WRITE",
        "forwardFix": "PRESERVE_IMMUTABLE_RELEASE_AND_FINALIZED_BINDING_HISTORY_DROP_DERIVED_STAGING_DENY_UNSAFE_REPLAY_AND_APPEND_SUCCESSOR_NEVER_REWRITE_RELEASE_OR_BINDING",
    },
    "goldenCases": [
        {"id": "complete-pack-import", "releaseDisposition": "ACTIVE", "availability": "READY_OFFLINE", "receiptKind": "MutationReceiptV1", "liveWorkspaceMutated": False},
        {"id": "active-session-binding", "subjectState": "ACTIVE", "bindingDigestMatchesRelease": True, "historyReadableAfterWithdrawal": True},
    ],
    "alternateCases": [
        {"id": "citation-allowed-metadata-only", "licenseScope": "CITATION_ALLOWED", "sourceBytesProjected": False, "citationAllowed": True},
        {"id": "expired-release", "availability": "EXPIRED", "bindingMayProceed": False},
        {"id": "revoked-release", "availability": "REVOKED", "bindingMayProceed": False},
        {"id": "superseded-release", "availability": "SUPERSEDED", "bindingMayProceed": False, "priorHistoryReadable": True},
        {"id": "missing-required-bytes", "availability": "MISSING_BYTES", "bindingMayProceed": False},
        {"id": "restricted-provenance", "licenseScope": "RESTRICTED", "sourceBytesProjected": False, "citationAllowed": False},
    ],
    "hostileCases": [
        {"id": case_id, "expectedDisposition": "FAIL_CLOSED", "expectedBoundary": "NO_PARTIAL_CANONICAL_SUCCESS"}
        for case_id in (
            "wrong-workspace", "wrong-release", "forged-manifest-digest", "forged-release-digest",
            "stale-binding-revision", "finalized-binding-replacement", "mutable-release-replacement",
            "missing-content", "restricted-citation", "unlicensed-source-bytes",
            "runtime-web-fetch", "cloud-or-provider-state", "account-or-credential", "second-writer-or-store",
            "fabricated-observation", "unknown-applicability",
        )
    ],
    "interruptionCases": [
        {"id": point.lower(), "point": point, "expectedBoundary": "RETRY_IDEMPOTENT_NO_PARTIAL_CANONICAL_SUCCESS"}
        for point in INTERRUPTION_POINTS
    ],
    "recoveryCases": [
        {"id": case_id, "expectedBoundary": "PRESERVE_IMMUTABLE_HISTORY_APPEND_SUCCESSOR_OR_DROP_DERIVED_STAGING"}
        for case_id in (
            "retry-import-after-readback-interruption", "retry-release-after-return-interruption",
            "retry-binding-after-readiness-interruption", "backup-restore-preserves-release-and-binding",
            "delete-and-erase-reconciles-receipts", "retention-drops-unbound-release-only",
            "supersession-keeps-finalized-history-readable", "replay-rebuilds-exact-readiness",
        )
    ],
    "claims": {
        claim: False
        for claim in (
            "native", "hosted", "adoption", "acceptance", "release", "acceptanceCredit", "releaseCredit",
            "providerAvailability", "cloudDurability", "network", "account", "externalDurability",
            "automaticCompletion", "automaticCompliance", "runtimeWebFetching", "mutableRelease",
            "unlicensedSourceBytes", "restrictedContentLeak", "secondStore", "secondWriter",
            "android", "web", "backend", "phase10PollingDuringParallelExecution",
        )
    },
}


def canonical(value: Any) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")


def pretty(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False) + "\n").encode("utf-8")


def sha256_bytes(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def sha256_value(value: Any) -> str:
    return sha256_bytes(canonical(value))


def _git_blob(root: Path, relative: str) -> bytes:
    return subprocess.run(["git", "-C", str(root), "show", f"{BASE_HEAD}:{relative}"], check=True, capture_output=True).stdout


def source_artifacts(root: Path) -> list[dict[str, Any]]:
    return [
        {"path": path, "source": "BASE_HEAD_BLOB", "bytes": len(raw := _git_blob(root, path)), "sha256": sha256_bytes(raw)}
        for path in SOURCE_REFERENCE_PATHS
    ]


def authority_artifacts(root: Path) -> list[dict[str, Any]]:
    return [
        {"path": path, "source": "BASE_HEAD_AUTHORITY_BLOB", "bytes": len(raw := _git_blob(root, path)), "sha256": sha256_bytes(raw)}
        for path in AUTHORITY_REFERENCE_PATHS
    ]


def _schema_for_value(value: Any) -> dict[str, Any]:
    if value is None:
        return {"type": "null"}
    if isinstance(value, bool):
        return {"type": "boolean"}
    if isinstance(value, int):
        return {"type": "integer"}
    if isinstance(value, float):
        return {"type": "number"}
    if isinstance(value, str):
        return {"type": "string"}
    if isinstance(value, list):
        result: dict[str, Any] = {"type": "array", "minItems": len(value), "maxItems": len(value)}
        if value:
            shapes = {
                json.dumps(_schema_for_value(item), sort_keys=True): _schema_for_value(item)
                for item in value
            }
            result["items"] = next(iter(shapes.values())) if len(shapes) == 1 else {"anyOf": [shapes[key] for key in sorted(shapes)]}
        if all(isinstance(item, str) for item in value):
            result["uniqueItems"] = True
        return result
    if isinstance(value, dict):
        return {
            "type": "object",
            "additionalProperties": False,
            "properties": {key: _schema_for_value(value[key]) for key in sorted(value)},
            "required": sorted(value),
        }
    raise TypeError(type(value))


def schema_document() -> dict[str, Any]:
    document = _schema_for_value(CORPUS)
    document.update({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://assetrounds.invalid/v23/field-reference-pack.schema.json",
        "title": "V23 P03 C23 Field Reference Pack Corpus",
    })
    return document


def _flags() -> dict[str, bool]:
    return {
        "native": False,
        "hosted": False,
        "adoption": False,
        "acceptance": False,
        "release": False,
        "nativeAcceptance": False,
        "hostedAcceptance": False,
        "adoptionEvidence": False,
        "acceptanceCredit": False,
        "releaseReadiness": False,
        "phase10PollingDuringParallelExecution": False,
    }


def _authority() -> dict[str, Any]:
    return {
        "cardID": CARD,
        "attemptID": 1,
        "registerOrdinal": REGISTER_ORDINAL,
        "executionMode": "PRE_S10_6_PROVISIONAL_ORDERED_IMPLEMENTATION",
        "appBaseHead": BASE_HEAD,
        "appBaseTree": BASE_TREE,
        "baseHead": BASE_HEAD,
        "baseTree": BASE_TREE,
        "coordinationHead": COORDINATION_HEAD,
        "coordinationTree": COORDINATION_TREE,
        "contextDigest": CONTEXT_DIGEST,
        "fenceDigest": FENCE_DIGEST,
        "pathFenceDigest": FENCE_DIGEST,
        "fullFencePaths": list(PATH_FENCE),
        "frozenS10ReservationDigest": FROZEN_S10_RESERVATION_DIGEST,
        "provisionalPrerequisiteDigest": PREREQUISITE_DIGEST,
        "coordinationLedgerDigest": COORDINATION_LEDGER_DIGEST,
        "coordinationProjectionDigest": COORDINATION_PROJECTION_DIGEST,
        "coordinationCASSequence": COORDINATION_CAS_SEQUENCE,
        "hydrationTransitionSequence": HYDRATION_TRANSITION_SEQUENCE,
        "hydrationTransitionDigest": HYDRATION_TRANSITION_DIGEST,
        "allowedPathCount": len(PATH_FENCE),
        "existingPathCount": len(EXISTING_PATHS),
        "newPathCount": len(NEW_PATHS),
        "directPrerequisiteCards": ["V23-P03-C22"],
        "nextCard": "V23-P03-C24",
        "sourceDossierSHA256": DOSSIER_SHA256,
        "sourceDossierUTF8Length": DOSSIER_UTF8_LENGTH,
        "inheritedV21BlockSHA256": INHERITED_V21_BLOCK_SHA256,
        "inheritedV21BlockUTF8Length": INHERITED_V21_BLOCK_UTF8_LENGTH,
    }


def _sealed(body: dict[str, Any], field: str = "artifactDigest") -> dict[str, Any]:
    result = dict(body)
    result[field] = sha256_bytes(pretty(body))
    return result


def contract_document(schema_row: dict[str, Any]) -> dict[str, Any]:
    required = {
        "contractNames": list(CONTRACT_NAMES),
        "referenceKinds": list(REFERENCE_KINDS),
        "provenanceKinds": list(PROVENANCE_KINDS),
        "licenseScopes": list(LICENSE_SCOPES),
        "releaseDispositions": list(RELEASE_DISPOSITIONS),
        "subjectKinds": list(SUBJECT_KINDS),
        "subjectStates": list(SUBJECT_STATES),
        "availabilityStates": list(AVAILABILITY_STATES),
        "interruptionPoints": list(INTERRUPTION_POINTS),
        "runtimeReleaseDispositionEnum": "FieldReferenceReleaseDispositionV1",
        "runtimeProvenanceEnum": "FieldReferenceProvenanceKindV1",
        "runtimeLicenseScopeEnum": "FieldReferenceLicenseScopeV1",
        "runtimeAvailabilityEnum": "FieldReferenceAvailabilityV1",
        "runtimeSubjectKindEnum": "FieldReferenceSubjectKindV1",
        "runtimeSubjectStateEnum": "FieldReferenceSubjectStateV1",
        "persistentSchemaVersion": 22,
        "recordsSchemaVersion": 21,
        "persistentKindLifecycleModelCount": 84,
        "durableFamilyCount": 2,
        "persistentFamilies": ["FieldReferenceReleaseV1", "FieldReferenceBindingV1"],
        "nonPersistentFamilies": ["FieldReferencePackStagingV1", "FieldReferenceOfflineReadinessV1"],
        "genericMutationReceiptKind": "MutationReceiptV1",
        "immutableReferenceRelease": True,
        "immutableWorkSessionBinding": True,
        "liveWorkspaceMutation": False,
        "sourceBytesInProjections": False,
        "runtimeFetching": False,
        "remoteIdentity": False,
        "fiveSelectors": list(TEST_METHODS),
        "forbiddenClaims": list(FORBIDDEN_CLAIMS),
    }
    body = {
        "artifact": "V23P03C23FieldReferencePackContractV1",
        "cardID": CARD,
        "schemaVersion": SCHEMA_VERSION,
        "status": "PASS_STATIC_PROVISIONAL",
        "verificationMode": "STATIC_ONLY",
        "title": TITLE,
        "authority": _authority(),
        "sourceProjection": SOURCE_PROJECTION,
        "requiredSemantics": required,
        "semanticScope": SEMANTIC_SCOPE,
        "persistenceBoundary": CORPUS["persistence"],
        "directPrerequisiteEvidence": DIRECT_PREREQUISITE_EVIDENCE,
        "priorFenceOverlaps": list(PRIOR_FENCE_OVERLAPS),
        "priorFenceProof": PRIOR_FENCE_PROOF,
        "evidenceIDs": list(EVIDENCE_IDS),
        "testSelectors": list(TEST_METHODS),
        "schemaArtifact": schema_row,
        "statusFlags": _flags(),
        "requiresAcceptedS10_6Reconciliation": True,
    }
    return _sealed(body)


def evidence_document(
    source_rows: list[dict[str, Any]],
    authority_rows: list[dict[str, Any]],
    schema_row: dict[str, Any],
    contract: dict[str, Any],
) -> dict[str, Any]:
    required = contract["requiredSemantics"]
    body = {
        "artifact": "V23P03C23FieldReferencePackEvidenceReceiptV1",
        "cardID": CARD,
        "schemaVersion": SCHEMA_VERSION,
        "result": "PASS_STATIC_PROVISIONAL",
        "verificationMode": "STATIC_ONLY",
        "authority": _authority(),
        "sourceArtifacts": source_rows,
        "authorityArtifacts": authority_rows,
        "requiredSemanticsDigest": sha256_value(required),
        "requiredSemantics": required,
        "evidenceCases": list(EVIDENCE_CASES),
        "deterministicEvidenceIDs": list(EVIDENCE_IDS),
        "testSelectors": list(TEST_METHODS),
        "schemaArtifact": schema_row,
        "priorFenceOverlaps": list(PRIOR_FENCE_OVERLAPS),
        "priorFenceProof": PRIOR_FENCE_PROOF,
        "staticBoundary": "NO_NATIVE_HOSTED_ADOPTION_ACCEPTANCE_RELEASE_PROVIDER_NETWORK_ACCOUNT_CLOUD_OR_PHASE10_CLAIM",
        "statusFlags": _flags(),
        "requiresAcceptedS10_6Reconciliation": True,
    }
    return _sealed(body)


def brand_document(contract: dict[str, Any]) -> dict[str, Any]:
    body = {
        "artifact": "V23P03C23BrandImpactManifestV1",
        "cardID": CARD,
        "schemaVersion": SCHEMA_VERSION,
        "status": "PASS_STATIC_PROVISIONAL",
        "verificationMode": "STATIC_ONLY",
        "brandSurfaceDelta": True,
        "uiSurfaceDelta": False,
        "impact": "VERSION_BOUND_OFFLINE_REFERENCE_STATES_AND_WORK_SESSION_BINDINGS_REMAIN_LOCAL_MANUAL_AND_ACCESSIBLE_WITH_NO_NEW_S10_UI_SURFACE",
        "preserved": [
            "immutable-reference-release-bytes",
            "immutable-work-session-binding-history",
            "bounded-provenance-metadata",
            "existing-design-tokens",
            "existing-accessibility-contracts",
            "S10-reserved-brand-assets",
        ],
        "deferred": ["native-build", "hosted-CI", "adoption", "acceptance", "release", "provider", "network", "account", "cloud", "Phase10"],
        "pathFenceCount": len(PATH_FENCE),
        "s10FenceOverlapPaths": [],
        "authorityContextDigest": CONTEXT_DIGEST,
        "authorityFenceDigest": FENCE_DIGEST,
        "priorFenceOverlaps": list(PRIOR_FENCE_OVERLAPS),
        "priorFenceProof": PRIOR_FENCE_PROOF,
        "statusFlags": _flags(),
        "requiresAcceptedS10_6Reconciliation": True,
        "contractDigest": contract["artifactDigest"],
    }
    return _sealed(body)


def _manifest_row(root: Path, relative: str, rendered: dict[str, bytes]) -> dict[str, Any]:
    path = root / relative
    if relative in rendered:
        raw = rendered[relative]
        return {"path": relative, "state": "GENERATED", "bytes": len(raw), "sha256": sha256_bytes(raw)}
    if path.is_file():
        raw = path.read_bytes()
        return {"path": relative, "state": "WORKTREE", "bytes": len(raw), "sha256": sha256_bytes(raw)}
    if relative in EXISTING_PATHS:
        raw = _git_blob(root, relative)
        return {"path": relative, "state": "BASE_HEAD", "bytes": len(raw), "sha256": sha256_bytes(raw)}
    return {"path": relative, "state": "MISSING_NEW_PATH", "bytes": 0, "sha256": sha256_bytes(b"")}


def all_outputs(root: Path) -> dict[str, bytes]:
    assert_corpus()
    source_rows = source_artifacts(root)
    authority_rows = authority_artifacts(root)
    schema_raw = pretty(schema_document())
    schema_row = {"path": SCHEMA_PATH, "bytes": len(schema_raw), "sha256": sha256_bytes(schema_raw)}
    contract = contract_document(schema_row)
    contract_raw = pretty(contract)
    evidence_raw = pretty(evidence_document(source_rows, authority_rows, schema_row, contract))
    evidence = json.loads(evidence_raw)
    brand_raw = pretty(brand_document(contract))
    rendered: dict[str, bytes] = {
        SCHEMA_PATH: schema_raw,
        CONTRACT_PATH: contract_raw,
        EVIDENCE_PATH: evidence_raw,
        BRAND_PATH: brand_raw,
    }
    rows = [_manifest_row(root, path, rendered) for path in MANIFEST_INPUT_PATHS]
    manifest = _sealed({
        "artifact": "V23P03C23ToolingManifestV1",
        "cardID": CARD,
        "schemaVersion": SCHEMA_VERSION,
        "result": "PASS_STATIC_PROVISIONAL",
        "verificationMode": "STATIC_ONLY",
        "authority": _authority(),
        "baseHead": BASE_HEAD,
        "baseTree": BASE_TREE,
        "pathFence": list(PATH_FENCE),
        "fullFencePaths": list(FULL_FENCE_PATHS),
        "pathFenceDigest": FENCE_DIGEST,
        "pathFenceCount": len(PATH_FENCE),
        "allowedCreateOrReplacePaths": list(PATH_FENCE),
        "allowedDeletePaths": [],
        "allowedRenamePaths": [],
        "existingPathCount": len(EXISTING_PATHS),
        "newPathCount": len(NEW_PATHS),
        "sourceReferenceCount": len(SOURCE_REFERENCE_PATHS),
        "sourceArtifacts": source_rows,
        "authorityArtifacts": authority_rows,
        "artifacts": rows,
        "artifactSetDigest": sha256_value(rows),
        "sourceProjection": SOURCE_PROJECTION,
        "directPrerequisiteEvidence": DIRECT_PREREQUISITE_EVIDENCE,
        "persistenceBoundary": CORPUS["persistence"],
        "priorFenceOverlaps": list(PRIOR_FENCE_OVERLAPS),
        "priorFenceProof": PRIOR_FENCE_PROOF,
        "frozenS10ReservationDigest": FROZEN_S10_RESERVATION_DIGEST,
        "s10FenceOverlapPaths": [],
        "statusFlags": _flags(),
        "requiresAcceptedS10_6Reconciliation": True,
        "evidenceDigest": evidence["artifactDigest"],
        "testSelectors": list(TEST_METHODS),
    })
    rendered[MANIFEST_PATH] = pretty(manifest)
    return rendered


def assert_corpus() -> None:
    if len(EXISTING_PATHS) != 105 or len(NEW_PATHS) != 14 or len(PATH_FENCE) != 119:
        raise ValueError("C23 path fence must be exactly 119=105+14")
    if len(set(PATH_FENCE)) != len(PATH_FENCE):
        raise ValueError("C23 path fence contains duplicates")
    if CORPUS["requiredContractNames"] != list(CONTRACT_NAMES):
        raise ValueError("C23 contract family set differs")
    if CORPUS["persistentSchemaVersion"] != 22 or CORPUS["recordsSchemaVersion"] != 21:
        raise ValueError("C23 persistence versions differ")
    if CORPUS["persistentKindLifecycleModelCount"] != 84 or CORPUS["durableFamilyCount"] != 2:
        raise ValueError("C23 model/family counts differ")
    if CORPUS["persistence"]["persistedFamilies"] != ["FieldReferenceReleaseV1", "FieldReferenceBindingV1"]:
        raise ValueError("C23 durable family set differs")
    if CORPUS["persistence"]["nonPersistentFamilies"] != ["FieldReferencePackStagingV1", "FieldReferenceOfflineReadinessV1"]:
        raise ValueError("C23 nonpersistent family set differs")
    if CORPUS["persistence"]["secondStore"] or CORPUS["persistence"]["secondWriter"]:
        raise ValueError("C23 second store/writer is prohibited")
    if (
        PRIOR_FENCE_PROOF.get("fenceCount") != 60
        or PRIOR_FENCE_PROOF.get("priorOwnedPathCount") != PRIOR_FENCE_PRIOR_OWNED_PATH_COUNT
        or PRIOR_FENCE_PROOF.get("overlapCount") != PRIOR_FENCE_OVERLAP_COUNT
        or PRIOR_FENCE_PROOF.get("authorizedOverlapCount") != PRIOR_FENCE_OVERLAP_COUNT
        or PRIOR_FENCE_PROOF.get("unauthorizedOverlapCount") != 0
        or len(PRIOR_FENCE_OVERLAPS) != PRIOR_FENCE_OVERLAP_COUNT
        or PRIOR_FENCE_PROOF.get("authorizedOverlapEdges") != list(PRIOR_FENCE_OVERLAPS)
    ):
        raise ValueError("C23 prior-fence proof differs")


assert_corpus()
