import Foundation

enum ClientCapabilityFailureV1:Error,Equatable,Sendable{case invalidValue,incompatibleVersion,digestMismatch,duplicateValue,wrongWorkspace,staleReference,unsupportedCapability,invalidSuccessor,admissionDenied,partialEffect}
enum ClientAdmissionV1:String,CaseIterable,Codable,Hashable,Sendable{case readWrite="READ_WRITE",readOnly="READ_ONLY",migrationRequired="MIGRATION_REQUIRED",quarantine="QUARANTINE",reject="REJECT"}
enum PackageLifecycleOperationV1:String,CaseIterable,Codable,Hashable,Sendable{case start="START",resume="RESUME",finalize="FINALIZE",amend="AMEND",view="VIEW",export="EXPORT",restore="RESTORE",replay="REPLAY",upgradeDraft="UPGRADE_DRAFT"}
enum PackageLifecycleStateV1:String,CaseIterable,Codable,Hashable,Sendable{case active="ACTIVE",deprecated="DEPRECATED",withdrawn="WITHDRAWN",quarantined="QUARANTINED",superseded="SUPERSEDED"}
enum PortableCapabilityDomainV1:String,CaseIterable,Codable,Hashable,Sendable{case schema="SCHEMA",contract="CONTRACT",package="PACKAGE",media="MEDIA",canonicalization="CANONICALIZATION",digest="DIGEST"}
enum ClientCapabilityReasonV1:String,CaseIterable,Codable,Hashable,Sendable{case exactMatch="EXACT_MATCH",readOnlyCompatibility="READ_ONLY_COMPATIBILITY",migrationAvailable="MIGRATION_AVAILABLE",unsupportedRequiredRange="UNSUPPORTED_REQUIRED_RANGE",unknownCapability="UNKNOWN_CAPABILITY",packageWithdrawn="PACKAGE_WITHDRAWN",packageQuarantined="PACKAGE_QUARANTINED",packageSuperseded="PACKAGE_SUPERSEDED",digestMismatch="DIGEST_MISMATCH",stalePolicy="STALE_POLICY",operationBlocked="OPERATION_BLOCKED"}

struct PortableSemanticVersionV1:Codable,Equatable,Hashable,Comparable,Sendable{let major:UInt32;let minor:UInt32;let patch:UInt32;init(major:UInt32,minor:UInt32=0,patch:UInt32=0)throws{guard major>0 else{throw ClientCapabilityFailureV1.invalidValue};self.major=major;self.minor=minor;self.patch=patch}static func <(l:Self,r:Self)->Bool{(l.major,l.minor,l.patch)<(r.major,r.minor,r.patch)}}
struct PortableCapabilityRangeV1:Codable,Equatable,Hashable,Sendable{let domain:PortableCapabilityDomainV1;let semanticID:String;let minimum:PortableSemanticVersionV1;let maximum:PortableSemanticVersionV1;init(domain:PortableCapabilityDomainV1,semanticID:String,minimum:PortableSemanticVersionV1,maximum:PortableSemanticVersionV1)throws{guard ClientCapabilityValidationV1.token(semanticID),minimum<=maximum else{throw ClientCapabilityFailureV1.invalidValue};self.domain=domain;self.semanticID=semanticID;self.minimum=minimum;self.maximum=maximum}func contains(_ other:Self)->Bool{domain==other.domain&&semanticID==other.semanticID&&minimum<=other.minimum&&maximum>=other.maximum}var stableKey:String{"\(domain.rawValue)|\(semanticID)"}}

enum ClientCapabilityValidationV1{
    static func token(_ value:String)->Bool{let t=value.trimmingCharacters(in:.whitespacesAndNewlines);return t==value && !value.isEmpty && value.utf8.count<=256 && value.unicodeScalars.allSatisfy{!CharacterSet.controlCharacters.contains($0)}}
    static func digest(_ value:String)throws{guard KernelCanonicalHashV1.validSHA256(value)else{throw ClientCapabilityFailureV1.digestMismatch}}
    static func ranges(_ values:[PortableCapabilityRangeV1])throws{guard !values.isEmpty,values.count<=512,values==values.sorted(by:{$0.stableKey<$1.stableKey}),Set(values.map(\.stableKey)).count==values.count else{throw ClientCapabilityFailureV1.duplicateValue}}
}

struct ClientCapabilityProfileV1:Codable,Equatable,Sendable{
    static let schemaVersion=1
    let schemaVersion:Int;let profileID:UUID;let workspaceID:WorkspaceID;let semanticRanges:[PortableCapabilityRangeV1];let emittedAt:Date;let supersedesProfileID:UUID?;let revision:UInt64;let mutationID:MutationIDV1;let profileSHA256:String
    init(profileID:UUID,workspaceID:WorkspaceID,semanticRanges:[PortableCapabilityRangeV1],emittedAt:Date,supersedesProfileID:UUID?=nil,revision:UInt64=1,mutationID:MutationIDV1)throws{let ranges=semanticRanges.sorted{$0.stableKey<$1.stableKey};schemaVersion=Self.schemaVersion;self.profileID=profileID;self.workspaceID=workspaceID;self.semanticRanges=ranges;self.emittedAt=emittedAt;self.supersedesProfileID=supersedesProfileID;self.revision=revision;self.mutationID=mutationID;profileSHA256=try WorkspaceMutationCanonicalV1.sha256(Basis(schemaVersion:Self.schemaVersion,profileID:profileID,workspaceID:workspaceID,semanticRanges:ranges,emittedAt:emittedAt,supersedesProfileID:supersedesProfileID,revision:revision,mutationID:mutationID));try validate()}
    func validate()throws{try ClientCapabilityValidationV1.ranges(semanticRanges);guard schemaVersion==Self.schemaVersion,profileID != .zero,revision>0,(supersedesProfileID==nil)==(revision==1),Set(semanticRanges.map(\.domain))==Set(PortableCapabilityDomainV1.allCases),profileSHA256==(try WorkspaceMutationCanonicalV1.sha256(Basis(schemaVersion:schemaVersion,profileID:profileID,workspaceID:workspaceID,semanticRanges:semanticRanges,emittedAt:emittedAt,supersedesProfileID:supersedesProfileID,revision:revision,mutationID:mutationID)))else{throw ClientCapabilityFailureV1.digestMismatch}}
    func validateSuccessor(of old:Self)throws{try validate();try old.validate();guard profileID != old.profileID,supersedesProfileID==old.profileID,workspaceID==old.workspaceID,mutationID != old.mutationID,old.revision<UInt64.max,revision==old.revision+1 else{throw ClientCapabilityFailureV1.invalidSuccessor}}
    func supports(_ required:[PortableCapabilityRangeV1])->Bool{required.allSatisfy{r in semanticRanges.contains(where:{$0.contains(r)})}}
    private struct Basis:Codable{let schemaVersion:Int;let profileID:UUID;let workspaceID:WorkspaceID;let semanticRanges:[PortableCapabilityRangeV1];let emittedAt:Date;let supersedesProfileID:UUID?;let revision:UInt64;let mutationID:MutationIDV1}
}

struct PackageLifecycleOperationRuleV1:Codable,Equatable,Hashable,Sendable{let operation:PackageLifecycleOperationV1;let active:ClientAdmissionV1;let deprecated:ClientAdmissionV1;let withdrawn:ClientAdmissionV1;let quarantined:ClientAdmissionV1;let superseded:ClientAdmissionV1;init(operation:PackageLifecycleOperationV1,active:ClientAdmissionV1,deprecated:ClientAdmissionV1,withdrawn:ClientAdmissionV1,quarantined:ClientAdmissionV1,superseded:ClientAdmissionV1)throws{self.operation=operation;self.active=active;self.deprecated=deprecated;self.withdrawn=withdrawn;self.quarantined=quarantined;self.superseded=superseded;try validate()}func admission(for state:PackageLifecycleStateV1)->ClientAdmissionV1{switch state{case .active:active;case .deprecated:deprecated;case .withdrawn:withdrawn;case .quarantined:quarantined;case .superseded:superseded}}func validate()throws{if [.view,.export,.restore,.replay].contains(operation){guard withdrawn == .readOnly else{throw ClientCapabilityFailureV1.invalidValue}}else{guard withdrawn == .reject || withdrawn == .quarantine else{throw ClientCapabilityFailureV1.invalidValue}};guard quarantined == .reject || quarantined == .quarantine else{throw ClientCapabilityFailureV1.invalidValue}}}

struct PackageLifecyclePolicyV1:Codable,Equatable,Sendable{
    static let schemaVersion=1
    let schemaVersion:Int;let policyID:UUID;let workspaceID:WorkspaceID;let packageReleaseID:String;let packageID:String;let packageSHA256:String;let workflowSHA256:String;let requiredCapabilities:[PortableCapabilityRangeV1];let operationRules:[PackageLifecycleOperationRuleV1];let effectiveAt:Date;let supersedesPolicyID:UUID?;let revision:UInt64;let mutationID:MutationIDV1;let policySHA256:String
    init(policyID:UUID,workspaceID:WorkspaceID,release:InspectionPackageReleaseV1,requiredCapabilities:[PortableCapabilityRangeV1],operationRules:[PackageLifecycleOperationRuleV1],effectiveAt:Date,supersedesPolicyID:UUID?=nil,revision:UInt64=1,mutationID:MutationIDV1)throws{try release.validate();let caps=requiredCapabilities.sorted{$0.stableKey<$1.stableKey},rules=operationRules.sorted{$0.operation.rawValue<$1.operation.rawValue};schemaVersion=Self.schemaVersion;self.policyID=policyID;self.workspaceID=workspaceID;packageReleaseID=release.packageReleaseID;packageID=release.packageID;packageSHA256=release.packageSHA256;workflowSHA256=release.workflowSHA256;self.requiredCapabilities=caps;self.operationRules=rules;self.effectiveAt=effectiveAt;self.supersedesPolicyID=supersedesPolicyID;self.revision=revision;self.mutationID=mutationID;policySHA256=try WorkspaceMutationCanonicalV1.sha256(Basis(schemaVersion:Self.schemaVersion,policyID:policyID,workspaceID:workspaceID,packageReleaseID:release.packageReleaseID,packageID:release.packageID,packageSHA256:release.packageSHA256,workflowSHA256:release.workflowSHA256,requiredCapabilities:caps,operationRules:rules,effectiveAt:effectiveAt,supersedesPolicyID:supersedesPolicyID,revision:revision,mutationID:mutationID));try validate(release:release)}
    func validate(release:InspectionPackageReleaseV1)throws{try release.validate();try ClientCapabilityValidationV1.ranges(requiredCapabilities);try operationRules.forEach{try $0.validate()};guard schemaVersion==Self.schemaVersion,policyID != .zero,revision>0,(supersedesPolicyID==nil)==(revision==1),packageReleaseID==release.packageReleaseID,packageID==release.packageID,packageSHA256==release.packageSHA256,workflowSHA256==release.workflowSHA256,operationRules.count==PackageLifecycleOperationV1.allCases.count,Set(operationRules.map(\.operation))==Set(PackageLifecycleOperationV1.allCases),operationRules==operationRules.sorted(by:{$0.operation.rawValue<$1.operation.rawValue}),policySHA256==(try WorkspaceMutationCanonicalV1.sha256(Basis(schemaVersion:schemaVersion,policyID:policyID,workspaceID:workspaceID,packageReleaseID:packageReleaseID,packageID:packageID,packageSHA256:packageSHA256,workflowSHA256:workflowSHA256,requiredCapabilities:requiredCapabilities,operationRules:operationRules,effectiveAt:effectiveAt,supersedesPolicyID:supersedesPolicyID,revision:revision,mutationID:mutationID)))else{throw ClientCapabilityFailureV1.digestMismatch}}
    func validateSuccessor(of old:Self,release:InspectionPackageReleaseV1)throws{try validate(release:release);try old.validate(release:release);guard policyID != old.policyID,supersedesPolicyID==old.policyID,workspaceID==old.workspaceID,packageReleaseID==old.packageReleaseID,mutationID != old.mutationID,old.revision<UInt64.max,revision==old.revision+1 else{throw ClientCapabilityFailureV1.invalidSuccessor}}
    func rule(for operation:PackageLifecycleOperationV1)throws->PackageLifecycleOperationRuleV1{guard let rule=operationRules.first(where:{$0.operation==operation})else{throw ClientCapabilityFailureV1.invalidValue};return rule}
    private struct Basis:Codable{let schemaVersion:Int;let policyID:UUID;let workspaceID:WorkspaceID;let packageReleaseID:String;let packageID:String;let packageSHA256:String;let workflowSHA256:String;let requiredCapabilities:[PortableCapabilityRangeV1];let operationRules:[PackageLifecycleOperationRuleV1];let effectiveAt:Date;let supersedesPolicyID:UUID?;let revision:UInt64;let mutationID:MutationIDV1}
}

struct PackageLifecycleDispositionV1:Codable,Equatable,Sendable{
    static let schemaVersion=1
    let schemaVersion:Int;let dispositionID:UUID;let workspaceID:WorkspaceID;let packageReleaseID:String;let packageID:String;let packageSHA256:String;let workflowSHA256:String;let state:PackageLifecycleStateV1;let reason:String;let recordedAt:Date;let supersedesDispositionID:UUID?;let revision:UInt64;let mutationID:MutationIDV1;let dispositionSHA256:String
    init(dispositionID:UUID,workspaceID:WorkspaceID,release:InspectionPackageReleaseV1,state:PackageLifecycleStateV1,reason:String,recordedAt:Date,supersedesDispositionID:UUID?=nil,revision:UInt64=1,mutationID:MutationIDV1)throws{try release.validate();schemaVersion=Self.schemaVersion;self.dispositionID=dispositionID;self.workspaceID=workspaceID;packageReleaseID=release.packageReleaseID;packageID=release.packageID;packageSHA256=release.packageSHA256;workflowSHA256=release.workflowSHA256;self.state=state;self.reason=reason;self.recordedAt=recordedAt;self.supersedesDispositionID=supersedesDispositionID;self.revision=revision;self.mutationID=mutationID;dispositionSHA256=try WorkspaceMutationCanonicalV1.sha256(Basis(schemaVersion:Self.schemaVersion,dispositionID:dispositionID,workspaceID:workspaceID,packageReleaseID:release.packageReleaseID,packageID:release.packageID,packageSHA256:release.packageSHA256,workflowSHA256:release.workflowSHA256,state:state,reason:reason,recordedAt:recordedAt,supersedesDispositionID:supersedesDispositionID,revision:revision,mutationID:mutationID));try validate(release:release)}
    func validate(release:InspectionPackageReleaseV1)throws{try release.validate();guard schemaVersion==Self.schemaVersion,dispositionID != .zero,revision>0,(supersedesDispositionID==nil)==(revision==1),ClientCapabilityValidationV1.token(reason),packageReleaseID==release.packageReleaseID,packageID==release.packageID,packageSHA256==release.packageSHA256,workflowSHA256==release.workflowSHA256,dispositionSHA256==(try WorkspaceMutationCanonicalV1.sha256(Basis(schemaVersion:schemaVersion,dispositionID:dispositionID,workspaceID:workspaceID,packageReleaseID:packageReleaseID,packageID:packageID,packageSHA256:packageSHA256,workflowSHA256:workflowSHA256,state:state,reason:reason,recordedAt:recordedAt,supersedesDispositionID:supersedesDispositionID,revision:revision,mutationID:mutationID)))else{throw ClientCapabilityFailureV1.digestMismatch}}
    func validateSuccessor(of old:Self,release:InspectionPackageReleaseV1)throws{try validate(release:release);try old.validate(release:release);guard dispositionID != old.dispositionID,supersedesDispositionID==old.dispositionID,workspaceID==old.workspaceID,packageReleaseID==old.packageReleaseID,mutationID != old.mutationID,old.revision<UInt64.max,revision==old.revision+1 else{throw ClientCapabilityFailureV1.invalidSuccessor}}
    private struct Basis:Codable{let schemaVersion:Int;let dispositionID:UUID;let workspaceID:WorkspaceID;let packageReleaseID:String;let packageID:String;let packageSHA256:String;let workflowSHA256:String;let state:PackageLifecycleStateV1;let reason:String;let recordedAt:Date;let supersedesDispositionID:UUID?;let revision:UInt64;let mutationID:MutationIDV1}
}

struct ClientCapabilityAdmissionDecisionV1:Codable,Equatable,Sendable{
    static let schemaVersion=1
    let schemaVersion:Int;let decisionID:UUID;let workspaceID:WorkspaceID;let profileID:UUID;let profileRevision:UInt64;let profileSHA256:String;let policyID:UUID;let policyRevision:UInt64;let policySHA256:String;let dispositionID:UUID;let dispositionRevision:UInt64;let dispositionSHA256:String;let packageReleaseID:String;let packageSHA256:String;let workflowSHA256:String;let operation:PackageLifecycleOperationV1;let admission:ClientAdmissionV1;let reasons:[ClientCapabilityReasonV1];let decidedAt:Date;let revision:UInt64;let mutationID:MutationIDV1;let decisionSHA256:String
    init(decisionID:UUID,workspaceID:WorkspaceID,profile:ClientCapabilityProfileV1,policy:PackageLifecyclePolicyV1,disposition:PackageLifecycleDispositionV1,release:InspectionPackageReleaseV1,operation:PackageLifecycleOperationV1,admission:ClientAdmissionV1,reasons:[ClientCapabilityReasonV1],decidedAt:Date,revision:UInt64=1,mutationID:MutationIDV1)throws{let reasons=reasons.sorted{$0.rawValue<$1.rawValue};schemaVersion=Self.schemaVersion;self.decisionID=decisionID;self.workspaceID=workspaceID;profileID=profile.profileID;profileRevision=profile.revision;profileSHA256=profile.profileSHA256;policyID=policy.policyID;policyRevision=policy.revision;policySHA256=policy.policySHA256;dispositionID=disposition.dispositionID;dispositionRevision=disposition.revision;dispositionSHA256=disposition.dispositionSHA256;packageReleaseID=release.packageReleaseID;packageSHA256=release.packageSHA256;workflowSHA256=release.workflowSHA256;self.operation=operation;self.admission=admission;self.reasons=reasons;self.decidedAt=decidedAt;self.revision=revision;self.mutationID=mutationID;decisionSHA256=try WorkspaceMutationCanonicalV1.sha256(Basis(schemaVersion:Self.schemaVersion,decisionID:decisionID,workspaceID:workspaceID,profileID:profile.profileID,profileRevision:profile.revision,profileSHA256:profile.profileSHA256,policyID:policy.policyID,policyRevision:policy.revision,policySHA256:policy.policySHA256,dispositionID:disposition.dispositionID,dispositionRevision:disposition.revision,dispositionSHA256:disposition.dispositionSHA256,packageReleaseID:release.packageReleaseID,packageSHA256:release.packageSHA256,workflowSHA256:release.workflowSHA256,operation:operation,admission:admission,reasons:reasons,decidedAt:decidedAt,revision:revision,mutationID:mutationID));try validate(profile:profile,policy:policy,disposition:disposition,release:release)}
    func validate(profile:ClientCapabilityProfileV1,policy:PackageLifecyclePolicyV1,disposition:PackageLifecycleDispositionV1,release:InspectionPackageReleaseV1)throws{try profile.validate();try policy.validate(release:release);try disposition.validate(release:release);let expected=ClientCapabilityAdmissionEvaluatorV1.evaluate(profile:profile,policy:policy,disposition:disposition,release:release,operation:operation);guard schemaVersion==Self.schemaVersion,decisionID != .zero,revision==1,workspaceID==profile.workspaceID,workspaceID==policy.workspaceID,workspaceID==disposition.workspaceID,profileID==profile.profileID,profileRevision==profile.revision,profileSHA256==profile.profileSHA256,policyID==policy.policyID,policyRevision==policy.revision,policySHA256==policy.policySHA256,dispositionID==disposition.dispositionID,dispositionRevision==disposition.revision,dispositionSHA256==disposition.dispositionSHA256,packageReleaseID==release.packageReleaseID,packageSHA256==release.packageSHA256,workflowSHA256==release.workflowSHA256,admission==expected.0,reasons==expected.1.sorted(by:{$0.rawValue<$1.rawValue}),!reasons.isEmpty,reasons==reasons.sorted(by:{$0.rawValue<$1.rawValue}),Set(reasons).count==reasons.count,decisionSHA256==(try WorkspaceMutationCanonicalV1.sha256(Basis(schemaVersion:schemaVersion,decisionID:decisionID,workspaceID:workspaceID,profileID:profileID,profileRevision:profileRevision,profileSHA256:profileSHA256,policyID:policyID,policyRevision:policyRevision,policySHA256:policySHA256,dispositionID:dispositionID,dispositionRevision:dispositionRevision,dispositionSHA256:dispositionSHA256,packageReleaseID:packageReleaseID,packageSHA256:packageSHA256,workflowSHA256:workflowSHA256,operation:operation,admission:admission,reasons:reasons,decidedAt:decidedAt,revision:revision,mutationID:mutationID)))else{throw ClientCapabilityFailureV1.digestMismatch}}
    private struct Basis:Codable{let schemaVersion:Int;let decisionID:UUID;let workspaceID:WorkspaceID;let profileID:UUID;let profileRevision:UInt64;let profileSHA256:String;let policyID:UUID;let policyRevision:UInt64;let policySHA256:String;let dispositionID:UUID;let dispositionRevision:UInt64;let dispositionSHA256:String;let packageReleaseID:String;let packageSHA256:String;let workflowSHA256:String;let operation:PackageLifecycleOperationV1;let admission:ClientAdmissionV1;let reasons:[ClientCapabilityReasonV1];let decidedAt:Date;let revision:UInt64;let mutationID:MutationIDV1}
}

struct ClientCapabilityLifecycleClosureV1:Sendable{let profile:ClientCapabilityProfileV1;let policy:PackageLifecyclePolicyV1;let disposition:PackageLifecycleDispositionV1;let decision:ClientCapabilityAdmissionDecisionV1;let release:InspectionPackageReleaseV1;func validate()throws{try decision.validate(profile:profile,policy:policy,disposition:disposition,release:release)}}
enum ClientCapabilityAdmissionEvaluatorV1{static func evaluate(profile:ClientCapabilityProfileV1,policy:PackageLifecyclePolicyV1,disposition:PackageLifecycleDispositionV1,release:InspectionPackageReleaseV1,operation:PackageLifecycleOperationV1)->(ClientAdmissionV1,[ClientCapabilityReasonV1]){do{try profile.validate();try policy.validate(release:release);try disposition.validate(release:release);guard profile.workspaceID==policy.workspaceID,policy.workspaceID==disposition.workspaceID else{return(.reject,[.stalePolicy])};guard profile.supports(policy.requiredCapabilities)else{return(.reject,[.unsupportedRequiredRange])};let admission=try policy.rule(for:operation).admission(for:disposition.state);let reason:ClientCapabilityReasonV1;switch disposition.state{case .withdrawn:reason = [.view,.export,.restore,.replay].contains(operation) ? .readOnlyCompatibility:.packageWithdrawn;case .quarantined:reason = .packageQuarantined;case .superseded:reason = .packageSuperseded;default:switch admission{case .readWrite:reason = .exactMatch;case .readOnly:reason = .readOnlyCompatibility;case .migrationRequired:reason = .migrationAvailable;case .quarantine:reason = .packageQuarantined;case .reject:reason = .operationBlocked}};return(admission,[reason])}catch{return(.reject,[.digestMismatch])}}}
enum ClientCapabilityCanonicalCodecV1{static func encode<T:Encodable>(_ value:T)throws->Data{let e=JSONEncoder();e.outputFormatting=[.sortedKeys,.withoutEscapingSlashes];e.dateEncodingStrategy = .millisecondsSince1970;return try e.encode(value)}static func decode<T:Codable>(_ type:T.Type,from data:Data)throws->T{guard !data.isEmpty,data.count<=1_048_576 else{throw ClientCapabilityFailureV1.invalidValue};let d=JSONDecoder();d.dateDecodingStrategy = .millisecondsSince1970;let v=try d.decode(type,from:data);guard try encode(v)==data else{throw ClientCapabilityFailureV1.digestMismatch};return v}}

extension ClientCapabilityProfileV1{func rebound(to workspaceID:WorkspaceID)throws->Self{try .init(profileID:profileID,workspaceID:workspaceID,semanticRanges:semanticRanges,emittedAt:emittedAt,supersedesProfileID:supersedesProfileID,revision:revision,mutationID:mutationID)}}
extension PackageLifecyclePolicyV1{func rebound(to workspaceID:WorkspaceID,release:InspectionPackageReleaseV1)throws->Self{try .init(policyID:policyID,workspaceID:workspaceID,release:release,requiredCapabilities:requiredCapabilities,operationRules:operationRules,effectiveAt:effectiveAt,supersedesPolicyID:supersedesPolicyID,revision:revision,mutationID:mutationID)}}
extension PackageLifecycleDispositionV1{func rebound(to workspaceID:WorkspaceID,release:InspectionPackageReleaseV1)throws->Self{try .init(dispositionID:dispositionID,workspaceID:workspaceID,release:release,state:state,reason:reason,recordedAt:recordedAt,supersedesDispositionID:supersedesDispositionID,revision:revision,mutationID:mutationID)}}
extension ClientCapabilityAdmissionDecisionV1{func rebound(to workspaceID:WorkspaceID,profile:ClientCapabilityProfileV1,policy:PackageLifecyclePolicyV1,disposition:PackageLifecycleDispositionV1,release:InspectionPackageReleaseV1)throws->Self{try .init(decisionID:decisionID,workspaceID:workspaceID,profile:profile,policy:policy,disposition:disposition,release:release,operation:operation,admission:admission,reasons:reasons,decidedAt:decidedAt,revision:revision,mutationID:mutationID)}}

private extension UUID{static let zero=UUID(uuid:(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))}
