#!/usr/bin/env python3
"""Fail-closed provisional static contracts for V23-P04-C14."""
from __future__ import annotations
import hashlib,json,os,re,subprocess
from pathlib import Path
os.environ["PYTHONDONTWRITEBYTECODE"]="1";ROOT=Path(__file__).resolve().parents[2];COORD=Path(r"C:\AssetRounds-v23-coordination");CARD="V23-P04-C14";BASE="73d512ac1ff2832fa5c681078fb027604c7661cf";TREE="c521dcfe1caf97b75b4a6d952f6c2ddea1daab2f";HEAD="aee98813ac4b54ec9dd03ca69caf44bbd4e8b3f5";CTREE="c31d0ea9f8cabb191b46bbd2ad622ab0c2f61666";CONTEXT="435c6ffc8efcf725be7c4f7a70982e8dcd0b494bbbc377d9b5fcbe9f448360fa";FENCE="6a2fac3729e5d3f4d12909d18e951ebe5c350fe9d94b97d8d8d34cbb1e8032c1";PREREQ="1aa55a8060f7c3642f0962632d12ae3f7fb0d9a02a341b23a7ac0b9109449a07";CORRECTION="8e9926610b6bc176c4a949bae29ed6dd9dd379648fe814ad4e064a7b829c3c0c";TRANSITION="8e91f0df481a112f6eb6bae51f6c6b4e8407b31c755288fe744a3138c3a8cdcc";LEDGER="87531a7a04d5b21cde197b7866a4115c17cfd0533c10d1480473565a605a684e";PROJECTION="757a4b63ec6dcfd8de8e072e508925fdae53605d90021648bcd3cad6ec210af4";FINAL_HASHES_SEALED=True
SCHEMA="Scripts/v23/private-system-discovery.schema.json";CONTRACT="docs/design/v23/tooling/V23P04C14PrivateSystemDiscoveryContractV1.json";EVIDENCE="docs/design/v23/tooling/V23P04C14PrivateSystemDiscoveryEvidenceReceiptV1.json";BRAND="docs/design/v23/tooling/V23P04C14BrandImpactManifestV1.json";MANIFEST="docs/design/v23/tooling/V23-P04-C14-tooling-manifest.json";SCRIPTS=("Scripts/v23/p04_c14_contracts.py","Scripts/v23/generate_p04_c14_contracts.py","Scripts/v23/verify_p04_c14_contracts.py");GENERATED=(SCHEMA,CONTRACT,EVIDENCE,BRAND,MANIFEST)
SOURCE=("FieldEvidenceApp/Domain/SystemDiscovery/PrivateSystemDiscoveryContractsV1.swift","FieldEvidenceApp/Application/SystemDiscovery/PrivateSystemDiscoveryCoordinatorV1.swift","FieldEvidenceApp/Infrastructure/Search/PrivateSystemDiscoveryIndexStoreV1.swift","FieldEvidenceApp/App/Intents/PrivateSystemDiscoveryAppIntentsV1.swift","FieldEvidenceApp/Features/Settings/PrivateSystemDiscoverySettingsView.swift","FieldEvidenceAppTests/V9_78PrivateSystemDiscoveryTests.swift","FieldEvidenceAppUITests/V23_P04_C14PrivateSystemDiscoveryUITests.swift","FieldEvidenceAppTests/Fixtures/V23/SystemDiscovery/V23P04C14PrivateSystemDiscoveryCorpusV1.json","FieldEvidenceApp/Infrastructure/Deletion/WholeSignDeletionService.swift","FieldEvidenceApp/Infrastructure/Backup/BackupRestoreService.swift","FieldEvidenceApp/Infrastructure/Persistence/StartupRouter.swift")
SELECTORS=("testV23P04C14G01OptedInAvailableUnlockedDiscoveryInvokesReusableReadAndRouteOnlyIntents","testV23P04C14A01UnavailableOrOptedOutDiscoveryPublishesNoPrivateSystemProjection","testV23P04C14H01LockedIngressResolvesNothingAndReturnsOnlyGenericUnlockRequired","testV23P04C14I01InterruptedRebuildOrRemovalJournalReplaysWithoutDuplicateSystemProjection","testV23P04C14R01DeleteEraseExportAndReportDropAndRebuildDerivedDiscoveryProjection");FLAGS={x:False for x in ("activation","native","hosted","adoption","acceptance","release","nativeAcceptance","hostedAcceptance","physicalEvidence","phase10PollingDuringParallelExecution")}
def pretty(v):return(json.dumps(v,sort_keys=True,indent=2)+"\n").encode()
def sha(v):return hashlib.sha256(v).hexdigest()
def run(*a,cwd=ROOT):return subprocess.run(["git",*a],cwd=cwd,check=True,capture_output=True,text=True).stdout.strip()
def load(x):return json.loads((COORD/x).read_bytes())
def authority():
 c=load("contexts/V23-P04-C14-attempt-1/BootstrapCardContextV1.json");f=load("contexts/V23-P04-C14-attempt-1/BootstrapPathFenceV1.json");q=load("receipts/V23-P04-C14-hydration-startup-router-fence-correction-v3.json");t=load("transitions/000444-V23-P04-C14-attempt-1-HYDRATING-startup-router-fence-correction.json");l=load("state/BootstrapExecutionLedgerEnvelopeV1.json");p=load("projections/ActiveWorkSetProjectionV1.json");proof=f["priorFenceProof"]
 if(run("rev-parse","HEAD",cwd=COORD),run("rev-parse","HEAD^{tree}",cwd=COORD))!=(HEAD,CTREE):raise ValueError("C14 coordination authority differs")
 if c.get("contextDigest")!=CONTEXT or f.get("fenceDigest")!=FENCE or c.get("provisionalPrerequisiteDigest")!=PREREQ or q.get("receiptDigest")!=CORRECTION or t.get("transitionDigest")!=TRANSITION or l.get("ledgerDigest")!=LEDGER or p.get("projectionDigest")!=PROJECTION or c.get("repository")!={"appBaseHead":BASE,"appBaseTree":TREE}:raise ValueError("C14 hydration authority differs")
 if len(c["existingPaths"])!=35 or len(c["newPaths"])!=16 or len(f["allowedCreateOrReplacePaths"])!=51 or proof["fenceCount"]!=4 or proof["priorOwnedPathCount"]!=292 or proof["overlapCount"]!=64 or proof["unauthorizedOverlapCount"]!=0 or set(f["allowedCreateOrReplacePaths"])&set(f["activeS10ReservedPaths"]):raise ValueError("C14 fence proof differs")
 return c,f
def rows():
 a=[]
 for x in SOURCE:
  p=ROOT/x;b=p.read_bytes() if p.is_file() else b"";a.append({"path":x,"status":"SOURCE_PRESENT" if b else "SOURCE_MISSING","sha256":sha(b) if b else None})
 return a,all(x["status"]=="SOURCE_PRESENT" for x in a)
def counts():
 _,f=authority();own=set(f["allowedCreateOrReplacePaths"]);n=lambda *a:{x.replace("\\","/") for x in run(*a).splitlines() if x};ch=n("diff","--name-only",BASE,"HEAD")|n("diff","--name-only","HEAD")|n("ls-files","--others","--exclude-standard")|set(SCRIPTS)|set(GENERATED);return{"changedPathCount":len(ch&own),"missingPathCount":sum(not(ROOT/x).is_file()for x in own-set(SCRIPTS)-set(GENERATED)),"unownedChangedPathCount":len(ch-own),"s10ReservationOverlapCount":len(own&set(f["activeS10ReservedPaths"]))}
def semantics(r,ready):
 if not ready:return
 _,f=authority();scope=[x for x in f["allowedCreateOrReplacePaths"] if x not in set(SCRIPTS)|set(GENERATED) and(ROOT/x).is_file()];text="\n".join((ROOT/x).read_text(encoding="utf-8")for x in scope);need=("SYSTEM_DISCOVERY_PROJECTION_V1","PRIVATE_SYSTEM_DISCOVERY_INDEX_V1","AppAccess","allowlist","REMOVAL_JOURNALED","defaultOff","Practice","XCTSkip",*SELECTORS)
 miss=[x for x in need if x.lower()not in text.lower()]
 if miss:raise ValueError("C14 discovery semantics missing:"+",".join(miss))
 domain=(ROOT/SOURCE[0]).read_text(encoding="utf-8");index=(ROOT/SOURCE[2]).read_text(encoding="utf-8");fixture=json.loads((ROOT/SOURCE[7]).read_bytes())
 if domain.count("permitsNetworkAccess: false")!=4 or "static let canonicalPersistence = false" not in domain or "!activationEnabled, !adoptionEnabled" not in domain:raise ValueError("C14 action/manifest negative-state contract missing")
 if "CSSearchableIndex(name: Self.indexName, protectionClass: .complete)" not in index or "PRIVATE_SYSTEM_DISCOVERY_INDEX_V1" not in domain:raise ValueError("C14 private on-device named-index descriptor missing")
 if any(re.search(p,index,re.I)for p in(r"CSSearchableIndex\\.default",r"URLSession",r"https?://",r"\\bpublicURL\\s*=")):raise ValueError("C14 forbidden public/network index API present")
 sem=fixture.get("semantics",{});handoff=fixture.get("sourceHandoff",{});status=fixture.get("statusFlags",{})
 if not all(sem.get(k) is False for k in("canonicalPersistence","publicRoute","networkAccess","telemetry")) or handoff.get("canonicalWriter") is not False or not all(v is False for v in status.values()):raise ValueError("C14 fixture affirmative false-state contract missing")
 deletion=(ROOT/SOURCE[-3]).read_text(encoding="utf-8");restore=(ROOT/SOURCE[-2]).read_text(encoding="utf-8");startup=(ROOT/SOURCE[-1]).read_text(encoding="utf-8");tests=(ROOT/SOURCE[5]).read_text(encoding="utf-8")
 if not all(x in deletion for x in("removePrivateSystemDiscovery", "PrivateSystemDiscoveryRemovalRequestV1", "WholeSignDeletionService")) or not all(x in restore for x in("dropPrivateSystemDiscoveryAfterRestore", "reconcileAtStartup", "PrivateSystemDiscoveryEraseAllServiceBoundaryV1")):raise ValueError("C14 incumbent deletion/restore/reconcile call-site coverage missing")
 if not all(x in tests for x in("protectedDataAvailable: true", "protectedDataAvailable", "dropAfterRestoreOrReplay", "exact committed parent binding", "changed binding", SELECTORS[-1])):raise ValueError("C14 protected-data or R01 production entrypoint coverage missing")
 if not all(x in startup for x in("await retryChecks()", "BackupRestoreService(", ").reconcileRestoreAndPrivateSystemDiscoveryAtStartup()", "WholeSignDeletionService(", ").reconcile()")):raise ValueError("C14 awaited startup reconciliation coverage missing")
 if not all(x in restore for x in("dropPrivateSystemDiscoveryAfterRestore", "PrivateSystemDiscoveryRestoreBindingV1", "operationID")) or not all(x in tests for x in("same raw operation ID", "changed input digest", "dropAfterRestoreOrReplay", "reopened global journal")):raise ValueError("C14 durable restore obligation/idempotency coverage missing")
 if not all(x in index for x in("PrivateSystemDiscoveryGlobalJournalStoreV1", "globalJournalStore: any PrivateSystemDiscoveryGlobalJournalStoreV1", "guard let globalJournalStore", "throw PrivateSystemDiscoveryFailureV1.unavailable")) or "InMemoryGlobal" in index:raise ValueError("C14 unified durable global-store injection/no-fallback coverage missing")
 if len(re.findall(r"try globalStore\.saveGlobal\(candidate\)\s*\n\s*globalJournal = candidate",index))!=3:raise ValueError("C14 global candidate-save-before-memory ordering missing")
 if not all(x in tests for x in("PrivateSystemDiscoveryDurableEnvelopeV1", "durableEnvelope", "globalSaveFailures", '("PREPARED", 1)', '("EFFECT_APPLIED", 2)', '("COMMITTED", 3)', "failOnGlobalSaveNumbers", "C14InjectedFailure.globalSave", "deleteAllBeforeSameActorRetry", "sameActorState", "a committed global parent receipt short-circuits same-ID restore replay")):raise ValueError("C14 unified-envelope global-save fault/same-actor retry coverage missing")
def documents():
 c,f=authority();r,ready=rows();n=counts();a={"cardID":CARD,"appBaseHead":BASE,"appBaseTree":TREE,"coordinationHead":HEAD,"coordinationTree":CTREE,"sequence":444,"contextDigest":CONTEXT,"pathFenceDigest":FENCE,"prerequisiteDigest":PREREQ,"correctionDigest":CORRECTION,"transitionDigest":TRANSITION,"ledgerDigest":LEDGER,"projectionDigest":PROJECTION,"finalHashesSealed":FINAL_HASHES_SEALED,"fencePathCount":51,"existingPathCount":35,"newPathCount":16,"priorFenceCount":4,"s10OverlapCount":0};s={"sourceReady":ready,"sourceRows":r,"counts":n,"selectors":list(SELECTORS)};scope={"persistentContractMode":"DERIVED_ONLY","persistentContractSchema":"SYSTEM_DISCOVERY_PROJECTION_V1","singleProtectedNamedIndex":"PRIVATE_SYSTEM_DISCOVERY_INDEX_V1","defaultOffSelectedRealWorkspaces":True,"practiceExcluded":True,"appAccessBeforeResolution":True,"deletionDisposition":"REMOVAL_JOURNALED","uiAdoption":"POST_S10_6_SKIP_NO_CREDIT","statusFlags":FLAGS};co={"schema":"V23P04C14PrivateSystemDiscoveryContractV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":scope,"sourceProjection":s,"testSelectors":list(SELECTORS),"statusFlags":FLAGS};ev={"schema":"V23P04C14PrivateSystemDiscoveryEvidenceReceiptV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"sourceProjection":s,"contractDigest":sha(pretty(co)),"statusFlags":FLAGS};br={"schema":"V23P04C14BrandImpactManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"authority":a,"semantics":scope,"sourceProjection":s,"uiAdoptionSkipped":True,"uiAcceptanceCredit":False,"statusFlags":FLAGS};ma={"schema":"V23P04C14ToolingManifestV1","schemaVersion":1,"cardID":CARD,"provisional":True,"finalHashesSealed":FINAL_HASHES_SEALED,"authority":a,"pathFence":f["allowedCreateOrReplacePaths"],"files":[{"path":x,"sha256":sha(pretty(v))}for x,v in((CONTRACT,co),(EVIDENCE,ev),(BRAND,br))],"counts":n,"toolingPaths":[*SCRIPTS,*GENERATED],"statusFlags":FLAGS};return{CONTRACT:co,EVIDENCE:ev,BRAND:br,MANIFEST:ma}
