#!/usr/bin/env python3
"""Fail-closed static evidence contracts for V23-P04-C12."""
from __future__ import annotations
import hashlib,json,os,re,subprocess
from pathlib import Path
from typing import Any
os.environ["PYTHONDONTWRITEBYTECODE"]="1"
ROOT=Path(__file__).resolve().parents[2]; COORD=Path(r"C:\AssetRounds-v23-coordination")
CARD="V23-P04-C12"; TITLE="Honest change-focused reinspection and unified deterministic exception review queue"; APP_BASE_HEAD="93f327908a3f65283ba025875b0f1506efd49b1f"; APP_BASE_TREE="4fe2822a8e1b5e1bc42342eb2ebe2e551ba175b7"; COORD_HEAD="608af67afb3d3afb92de0af85b1d636a59c472be"; COORD_TREE="ef78081be7991526c1ecbad501341b69d1065b7a"; CONTEXT="0a08934dce1d681d39e405f81fae85d53e81a93f57d28e2fe243aa9d609d7808"; FENCE="c3d4facea5b867f1132da02981bb6ad14d9ce95c459cfc8ac1d56f2e80731a98"; PREREQ="61edb78a8ac8b5c4d5225f80fddcdb96d6558e87d94154954fd3b1483206802a"; TRANSITION="43f443c295e46e87f377f5aab3e49f24b1aca4fdc3e5ae12763ab696aa55c996"; LEDGER="4293f2eb2149c65f790edb801c1472dfeecdccdc5323b0e810c4e0d91f08f6e4"; PROJECTION="4ff1ea0230754a2dde70123f6492415b71b1936a2173356c6f39d40ed6de3b48"; FINAL_HASHES_SEALED=True
SCHEMA_PATH="Scripts/v23/reinspection-exception-queue.schema.json"; CONTRACT_PATH="docs/design/v23/tooling/V23P04C12ReinspectionExceptionQueueContractV1.json"; EVIDENCE_PATH="docs/design/v23/tooling/V23P04C12ReinspectionExceptionQueueEvidenceReceiptV1.json"; BRAND_PATH="docs/design/v23/tooling/V23P04C12BrandImpactManifestV1.json"; MANIFEST_PATH="docs/design/v23/tooling/V23-P04-C12-tooling-manifest.json"; SCRIPT_PATHS=("Scripts/v23/p04_c12_contracts.py","Scripts/v23/generate_p04_c12_contracts.py","Scripts/v23/verify_p04_c12_contracts.py"); GENERATED_PATHS=(SCHEMA_PATH,CONTRACT_PATH,EVIDENCE_PATH,BRAND_PATH,MANIFEST_PATH)
SELECTORS=("testV23P04C12G01ChangedOpenExpiredItemsRequireFreshEvidenceAndQueueClearsOnlyOnResolution","testV23P04C12A01UnchangedAttestationBindsExactPriorCurrentRevisionsAndPolicy","testV23P04C12H01ChangedIdentityMissingEvidenceStaleAttestationDuplicateAndForgedDismissalFailClosed","testV23P04C12I01InterruptedPlanQueueRebuildOrAttestationCommitPreservesCanonicalSources","testV23P04C12R01RestoredCanonicalSourcesRebuildExactQueueDecisionsReasonsAndUnresolvedCounts"); EVIDENCE_IDS=tuple(f"{CARD}-{x}" for x in ("G01","A01","H01","I01","R01")); LIFECYCLE=("MIGRATION","BACKUP","REPLACE_RESTORE","DELETE","ERASE","EXPORT","REPORT","SEARCH","REBUILD","JOURNAL","REPLAY")
FLAGS={k:False for k in ("activation","native","hosted","adoption","acceptance","release","nativeAcceptance","hostedAcceptance","physicalEvidence","phase10PollingDuringParallelExecution")}
IMPLEMENTATION_PATHS=("FieldEvidenceApp/Application/Reinspection/ReinspectionExceptionQueueCoordinatorV1.swift","FieldEvidenceApp/Domain/Reinspection/ReinspectionExceptionQueueContractsV1.swift","FieldEvidenceApp/Domain/Models/ReinspectionExceptionQueuePersistenceModelsV1.swift","FieldEvidenceApp/Features/CheckRunner/ReinspectionPlanView.swift","FieldEvidenceApp/Features/Dashboard/ExceptionReviewQueueView.swift","FieldEvidenceApp/Infrastructure/Persistence/ReinspectionExceptionQueueLifecycleAdapterV1.swift","FieldEvidenceAppTests/Fixtures/V23/Reinspection/V23P04C12ReinspectionExceptionQueueCorpusV1.json","FieldEvidenceAppTests/V9_76ReinspectionExceptionQueueTests.swift","FieldEvidenceAppUITests/V23_P04_C12ReinspectionExceptionQueueUITests.swift")
def strict(pairs):
 d={}
 for k,v in pairs:
  if k in d:raise ValueError("duplicate JSON key:"+k)
  d[k]=v
 return d
def canonical(v:Any)->bytes:return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"),allow_nan=False).encode()
def pretty(v:Any)->bytes:return (json.dumps(v,ensure_ascii=False,sort_keys=True,indent=2,allow_nan=False)+"\n").encode()
def sha(v:bytes)->str:return hashlib.sha256(v).hexdigest()
def sealed(v:dict[str,Any],key:str)->str:return sha((json.dumps({k:x for k,x in v.items() if k!=key},sort_keys=True,separators=(",",":"))+"\n").encode())
def run(*args:str,cwd=ROOT)->str:return subprocess.run(["git",*args],cwd=cwd,check=True,capture_output=True,text=True).stdout.strip()
def load(p:str)->dict[str,Any]:return json.loads((COORD/p).read_bytes(),object_pairs_hook=strict)
def authority():
 c=load("contexts/V23-P04-C12-attempt-1/BootstrapCardContextV1.json");f=load("contexts/V23-P04-C12-attempt-1/BootstrapPathFenceV1.json");t=load("transitions/000434-V23-P04-C12-attempt-1-NOT_STARTED-to-HYDRATING.json");l=load("state/BootstrapExecutionLedgerEnvelopeV1.json");p=load("projections/ActiveWorkSetProjectionV1.json");proof=f.get("priorFenceProof",{})
 if run("rev-parse","HEAD",cwd=COORD)!=COORD_HEAD or run("rev-parse","origin/main",cwd=COORD)!=COORD_HEAD or run("rev-parse","HEAD^{tree}",cwd=COORD)!=COORD_TREE:raise ValueError("C12 current coordination authority differs")
 if c.get("contextDigest")!=CONTEXT or sealed(c,"contextDigest")!=CONTEXT or f.get("fenceDigest")!=FENCE or sealed(f,"fenceDigest")!=FENCE or t.get("transitionDigest")!=TRANSITION or sealed(t,"transitionDigest")!=TRANSITION:raise ValueError("C12 context/fence/transition identity differs")
 if (c.get("provisionalPrerequisiteDigest"),l.get("ledgerDigest"),p.get("projectionDigest"),l.get("casSequence"),c.get("registerOrdinal"))!=(PREREQ,LEDGER,PROJECTION,434,100):raise ValueError("C12 hydration ledger/projection differs")
 if c.get("repository")!={"appBaseHead":APP_BASE_HEAD,"appBaseTree":APP_BASE_TREE} or c.get("directPrerequisites")!=["V23-P04-C07","V23-P04-C09","V23-P04-C10","V23-P04-C11"]:raise ValueError("C12 base/prerequisite differs")
 if len(c.get("existingPaths",()))!=113 or len(c.get("newPaths",()))!=17 or len(f.get("allowedCreateOrReplacePaths",()))!=130 or proof.get("fenceCount")!=100 or proof.get("priorOwnedPathCount")!=1579 or proof.get("authorizedOverlapCount")!=4118 or proof.get("unauthorizedOverlapCount")!=0 or set(f["allowedCreateOrReplacePaths"])&set(f["activeS10ReservedPaths"]):raise ValueError("C12 fence proof differs")
 return c,f
def source_rows():
 rows=[]
 for path in IMPLEMENTATION_PATHS:
  x=ROOT/path;data=x.read_bytes() if x.is_file() else b"";rows.append({"path":path,"status":"SOURCE_PRESENT" if x.is_file() else "SOURCE_MISSING","byteCount":len(data),"sha256":sha(data) if x.is_file() else None})
 return rows,all(x["status"]=="SOURCE_PRESENT" for x in rows)
def fence_rows():
 _,f=authority();owned=set(f["allowedCreateOrReplacePaths"]);names=lambda *a:{x.replace("\\","/") for x in run(*a).splitlines() if x};changed=names("diff","--name-only",APP_BASE_HEAD,"HEAD")|names("diff","--name-only","HEAD")|names("diff","--name-only","--cached")|names("ls-files","--others","--exclude-standard")|set(SCRIPT_PATHS)|set(GENERATED_PATHS)
 # Generator-controlled paths are expected materializations, not source-lane
 # readiness inputs; including them would make an --apply change its own hash.
 source_owned=owned-set(SCRIPT_PATHS)-set(GENERATED_PATHS)
 return {"changedPathCount":len(changed&owned),"missingPathCount":sum(not (ROOT/x).is_file() for x in source_owned),"unownedChangedPathCount":len(changed-owned),"s10ReservationOverlapCount":len(owned&set(f["activeS10ReservedPaths"]))}
def validate_source_semantics(rows,ready):
 if not ready:return
 support=("FieldEvidenceApp/Infrastructure/Persistence/PersistentSchemas.swift","FieldEvidenceApp/Infrastructure/Persistence/CurrentPersistentKindLifecycleCatalogV1.swift","FieldEvidenceApp/Infrastructure/Persistence/StoreGenerationFactory.swift","FieldEvidenceApp/Infrastructure/Persistence/WorkspaceWriterAdapterV1.swift","FieldEvidenceApp/Application/Mutation/WorkspaceWriterV1.swift","FieldEvidenceApp/Infrastructure/Persistence/MutationJournal/MutationJournalStoreV1.swift","FieldEvidenceApp/Infrastructure/Persistence/MutationJournal/MutationReceiptRecoveryServiceV1.swift","FieldEvidenceApp/Domain/Backup/V4BackupContracts.swift","FieldEvidenceApp/Infrastructure/Backup/BackupRestoreService.swift","FieldEvidenceApp/Infrastructure/Deletion/KernelDeletionEraseRegistryV4.swift")
 body="\n".join((ROOT/x).read_text(encoding="utf-8") for x in (*IMPLEMENTATION_PATHS,*support)); required=("ReinspectionPlanV1","UnchangedAttestationV1","ExceptionQueueItemV1","ReinspectionAndExceptionSchemaV1","PersistentSchemaV49","WorkspaceWriterV1","WorkspaceWriterAdapterV1","MutationJournalStoreV1","XCTSkip",*SELECTORS)
 missing=[x for x in required if x.lower() not in body.lower()]
 if missing:raise ValueError("C12 source semantics missing:"+",".join(missing))
 adapter=(ROOT/IMPLEMENTATION_PATHS[5]).read_text(encoding="utf-8");tests=(ROOT/IMPLEMENTATION_PATHS[7]).read_text(encoding="utf-8");models=(ROOT/IMPLEMENTATION_PATHS[2]).read_text(encoding="utf-8");writer=(ROOT/support[4]).read_text(encoding="utf-8");journal=(ROOT/support[5]).read_text(encoding="utf-8");recovery=(ROOT/support[6]).read_text(encoding="utf-8")
 if not all(re.search(r"func\s+"+x.lower(),adapter,re.I) for x in ("migrate","replaceRestore","replay","delete","erase","exportCanonical","report","search","rebuild")):raise ValueError("C12 adapter lifecycle coverage missing")
 if not all(x in adapter for x in ("sourceResolver", "exceptionSourceResolver", "sourceProviders.count == ExceptionQueueSourceKindV1.allCases.count", "Set(providerKinds) == Set(ExceptionQueueSourceKindV1.allCases)")):raise ValueError("C12 mandatory dual-resolver/nine-provider closure missing")
 if not all(x in models for x in ("ReinspectionPlanRowV1","UnchangedAttestationRowV1","ExceptionQueueAcknowledgementRowV1","ReinspectionExceptionMutationReceiptRowV1","init(restoring")):raise ValueError("C12 V49 durable row/restoring coverage missing")
 if not all(x in writer for x in ("commitReinspectionException", "applyReinspectionException", "expectedRevision", "mutationID", "reinspectionExceptionQuery")):raise ValueError("C12 canonical writer/query coverage missing")
 if not all(x in journal for x in ("ReinspectionExceptionMutationReceiptRowV1","logicalExceptionKey","semanticSHA256s","receiptCommitted")):raise ValueError("C12 journal/typed-receipt coverage missing")
 if not all(x in recovery for x in ("recoverBeforeWriterActivation", "ReinspectionException")):raise ValueError("C12 recovery activation coverage missing")
 if not all(x in body for x in ("ReinspectionExceptionQueueBackupEnrollmentV1","replaceRestore","ReinspectionExceptionKernelDeletionEraseEnrollmentV1","exportCanonical")):raise ValueError("C12 backup/restore/delete/Erase/export coverage missing")
 if not all(x in body for x in ("logicalExceptionKey", "evidenceSHA256", "IdentityBasis", "validateResolved(reinspectionResolver", "validateResolved(by resolver")):raise ValueError("C12 derived logical/evidence key or dual resolver validation missing")
 schemas=(ROOT/support[0]).read_text(encoding="utf-8");factory=(ROOT/support[2]).read_text(encoding="utf-8");writer_adapter=(ROOT/support[3]).read_text(encoding="utf-8")
 if not all(x in schemas for x in ("PersistentSchemaV49", "PersistentSchemaV48.models+[ReinspectionPlanRowV1.self,UnchangedAttestationRowV1.self,ExceptionQueueAcknowledgementRowV1.self,ReinspectionExceptionMutationReceiptRowV1.self]", "PersistentSchemaV49.models.count == 162", "case v49", "case .v49:return PersistentSchemaV48.versionIdentifier", "PersistentSchemaMigrationPlanV48")):raise ValueError("C12 V49 registry/candidate/migration closure missing")
 if not all(x in factory for x in ("case 49: container = try makeV49Container", "case (.v48,.v49)", "makeV49Container", "semanticExportV49", "requireV49Marker", "backfillV49Marker")):raise ValueError("C12 StoreGenerationFactory V49 exhaustive path missing")
 if not all(x in writer_adapter for x in ("guard let reinspectionCanonicalSourceResolver", "let exceptionQueueCanonicalSourceResolver", "guard let reinspectionResolver = reinspectionCanonicalSourceResolver", "let exceptionResolver = exceptionQueueCanonicalSourceResolver")):raise ValueError("C12 writer adapter resolver-required read closure missing")
 if not all(x in adapter for x in ("guard let sourceResolver, let exceptionSourceResolver", "row.value(predecessor: predecessor, resolver: sourceResolver)", "resolver: exceptionSourceResolver")):raise ValueError("C12 lifecycle resolver-backed read closure missing")
 sync=(ROOT/"FieldEvidenceApp/Infrastructure/Persistence/CurrentSyncClassificationCatalogV1.swift").read_text(encoding="utf-8");lifecycle_catalog=(ROOT/"FieldEvidenceApp/Infrastructure/Persistence/CurrentPersistentKindLifecycleCatalogV1.swift").read_text(encoding="utf-8")
 if "maximumRegistrationCount" in sync:raise ValueError("C12 CurrentSync retains a stale baseline maximumRegistrationCount boundary")
 if not all(x in sync for x in ("StoreSemanticEnvelopeV49", "case \"StoreSemanticEnvelopeV49\":return try subjects(category:.persistentModel,names:activePersistentModelNames)", "PersistentSchemaV49.models.count == 162")):raise ValueError("C12 CurrentSync V49 envelope/active-catalog registration missing")
 if "case \"StoreSemanticEnvelopeV49\":return try subjects(category:.persistentModel,names:activePersistentModelNames.filter" in sync:raise ValueError("C12 CurrentSync retains legacy filter exclusion chain for V49")
 if not all(x in lifecycle_catalog for x in ("kindIDs.count == 443", "laterTemporalOrigins.count == 362", "durableKindIDs.count == 221", "2d92c48b3a85255a79cc28384000b41752e6d8902467d5b454bc7fc255227c18", "CompatibilityCanonicalV1.encode(kindIDs)", "V23_P04_C12", "StoreSemanticEnvelopeV49")):raise ValueError("C12 lifecycle full-universe/digest boundary missing")
 if re.search(r"\b(ai|automatic pass|automatic fail|opaque confidence|evidence laundering)\b",body,re.I):raise ValueError("C12 prohibited claim")
 if not all(x.lower() in body.lower() for x in ("fresh observation","prior revision","queue rebuild","forged dismissal","no acceptance credit")):raise ValueError("C12 invariant/UI-skip coverage missing")
def semantics():return {"persistentContractMode":"NEW_SCHEMA_VERSION","persistentContractSchema":"ReinspectionAndExceptionSchemaV1","namedContracts":["ReinspectionPlanV1","UnchangedAttestationV1","ExceptionQueueItemV1"],"canonicalOwner":"V23-P04-C12_SOLE_REINSPECTION_AND_EXCEPTION_QUEUE_WRITER_OWNER","oneCanonicalWriter":True,"lifecycleCoverage":list(LIFECYCLE),"preservedInvariants":["NO_COPY_FORWARD_AS_NEW_OBSERVATION","EXPLAINABLE_CHANGE_FOCUSED_SELECTION","REBUILDABLE_QUEUE_ACKNOWLEDGEMENT_NEVER_MUTATES_SOURCE"],"containedUI":"POST_S10_6_ADOPTION_SKIP_NO_CREDIT","uiAcceptanceCredit":False,"statusFlags":FLAGS}
def documents():
 c,f=authority();rows,ready=source_rows();counts=fence_rows();provisional=True;auth={"cardID":CARD,"title":TITLE,"registerOrdinal":100,"appBaseHead":APP_BASE_HEAD,"appBaseTree":APP_BASE_TREE,"hydrationCoordinationHead":COORD_HEAD,"hydrationCoordinationTree":COORD_TREE,"contextDigest":CONTEXT,"pathFenceDigest":FENCE,"prerequisiteDigest":PREREQ,"transitionDigest":TRANSITION,"ledgerDigest":LEDGER,"projectionDigest":PROJECTION,"finalHashesSealed":FINAL_HASHES_SEALED,"directPrerequisites":["V23-P04-C07","V23-P04-C09","V23-P04-C10","V23-P04-C11"],"fenceCount":100,"existingPathCount":113,"newPathCount":17,"fencePathCount":130,"priorOwnedPathCount":1579,"authorizedOverlapCount":4118,"unauthorizedOverlapCount":0,"s10OverlapCount":0};src={"sourceReady":ready,"sourceStatus":"SOURCE_READY" if ready else "SOURCE_MISSING_PROVISIONAL","sourceRows":rows,"ownedFenceCounts":counts,"selectors":list(SELECTORS),"evidenceIDs":list(EVIDENCE_IDS)}
 contract={"schema":"V23P04C12ReinspectionExceptionQueueContractV1","schemaVersion":1,"cardID":CARD,"status":"PROVISIONAL","provisional":provisional,"authority":auth,"semantics":semantics(),"sourceProjection":src,"testSelectors":list(SELECTORS),"evidenceIDs":list(EVIDENCE_IDS),"statusFlags":FLAGS};receipt={"schema":"V23P04C12ReinspectionExceptionQueueEvidenceReceiptV1","schemaVersion":1,"cardID":CARD,"status":"PROVISIONAL_SOURCE_LANES_PENDING","provisional":provisional,"authority":auth,"sourceProjection":src,"contractDigest":sha(canonical(contract)),"lifecycleCoverage":list(LIFECYCLE),"statusFlags":FLAGS};brand={"schema":"V23P04C12BrandImpactManifestV1","schemaVersion":1,"cardID":CARD,"provisional":provisional,"authority":auth,"semantics":semantics(),"sourceProjection":src,"uiAdoptionSkipped":True,"uiAcceptanceCredit":False,"statusFlags":FLAGS};payload={CONTRACT_PATH:contract,EVIDENCE_PATH:receipt,BRAND_PATH:brand};manifest={"schema":"V23P04C12ToolingManifestV1","schemaVersion":1,"cardID":CARD,"provisional":provisional,"finalHashesSealed":False,"authority":auth,"pathFence":f["allowedCreateOrReplacePaths"],"existingPaths":c["existingPaths"],"newPaths":c["newPaths"],"files":[{"path":p,"byteCount":len(pretty(v)),"sha256":sha(pretty(v))} for p,v in sorted(payload.items())],"generatedArtifacts":[{"path":p,"byteCount":len(pretty(v)),"sha256":sha(pretty(v))} for p,v in sorted(payload.items())],"counts":counts,"toolingPaths":[*SCRIPT_PATHS,*GENERATED_PATHS],"statusFlags":FLAGS};return {**payload,MANIFEST_PATH:manifest}
