import Foundation

enum ActivityCompletedReportReleaseFailureV1: Error, Equatable {
    case unavailableBundle
    case resourceMissing(String)
    case resourceAmbiguous(String)
    case invalidResource(String)
    case unsupportedManifest
}

/// A release pin is code-owned. It cannot be supplied by a profile or a caller.
struct ActivityCompletedReportResourceV1: Equatable, Sendable {
    let fileName: String
    let byteCount: Int
    let rawSHA256: String
    let canonicalSHA256: String

    fileprivate init(fileName: String, byteCount: Int, rawSHA256: String, canonicalSHA256: String) {
        self.fileName = fileName
        self.byteCount = byteCount
        self.rawSHA256 = rawSHA256
        self.canonicalSHA256 = canonicalSHA256
    }
}

struct ActivityCompletedReportSchemaV1: Equatable, Sendable {
    let rootTypeID: String
    let resource: ActivityCompletedReportResourceV1
    let projection: OpenJSONSchemaProjectionV1

    fileprivate init(rootTypeID: String, resource: ActivityCompletedReportResourceV1) throws {
        self.rootTypeID = rootTypeID
        self.resource = resource
        projection = try OpenJSONSchemaProjectionV1(
            manifestID: ActivityCompletedReportReleaseV1.manifestID,
            manifestVersion: ActivityCompletedReportReleaseV1.manifestVersion,
            manifestSHA256: ActivityCompletedReportReleaseV1.manifestResource.canonicalSHA256,
            schemaID: "https://schemas.assetrounds.local/v23/p03/c06/\(rootTypeID)/schema",
            schemaSHA256: resource.canonicalSHA256
        )
    }
}

/// Exact app-owned manifest/schema admission only. Profile formatting, media and
/// source authenticity still belong to completion's existing production services.
/// This value neither authorizes a write nor selects a current profile on readback.
struct ActivityCompletedReportReleaseV1: Sendable {
    // BEGIN GENERATED COMPLETED RELEASE PINS
    static let manifestID = "activity-completed-contract-manifest-v1"
    static let manifestVersion = 1
    static let objectDefinitionCount = 249
    static let enumDefinitionCount = 139
    static let fileRootTypeID = "activity-completed-file-v1"
    static let reportRootTypeID = "activity-completed-report-v1"
    static let registryCanonicalSHA256 = "49a86470c78ff1f19096f812715e6665f37e93e8817fc62457335c5a5ffd5998"

    // Generated by the pinned actual-manifest compiler. Raw bytes have one final
    // LF; canonical hashes exclude it. Published V1 resources remain unchanged.
    static let manifestResource = ActivityCompletedReportResourceV1(
        fileName: "ActivityCompletedContractManifestV1.json", byteCount: 415_021,
        rawSHA256: "135cb528eb0eb7748887b43e98f4c723182d2663c9fe6dbe61f6f1f8e0ce57b2",
        canonicalSHA256: "7ed5d023b813d3c4363e346e393bb0aec2d9ef87b78a9aef8a79405d5ae1b2ac"
    )
    static let fileSchemaResource = ActivityCompletedReportResourceV1(
        fileName: "activity-completed-file-v1.schema.json", byteCount: 442_691,
        rawSHA256: "55c7ed35f23768929c79745a9f0553281609ac252b895a58c5b078e447336fa9",
        canonicalSHA256: "80b4bf4950106dcc5f4d70f1dd37f52620cdc3ae578bbcfe63123aa0f4bd03f9"
    )
    static let reportSchemaResource = ActivityCompletedReportResourceV1(
        fileName: "activity-completed-report-v1.schema.json", byteCount: 442_697,
        rawSHA256: "3d135a2a9892bfc1679e7e5937f469747c9dc14e13e1b455232d30a6a9f39105",
        canonicalSHA256: "6e931e89b9232b2cbd335bb170c3e2b66b015e8463b42e0a793508de32532020"
    )
    // END GENERATED COMPLETED RELEASE PINS

    let manifest: ContractManifestV1
    let fileSchema: ActivityCompletedReportSchemaV1
    let reportSchema: ActivityCompletedReportSchemaV1

    static var appBundle: Bundle { Bundle(for: ActivityCompletedReportBundleAnchorV1.self) }

    private init(manifest: ContractManifestV1, fileSchema: ActivityCompletedReportSchemaV1,
                 reportSchema: ActivityCompletedReportSchemaV1) {
        self.manifest = manifest
        self.fileSchema = fileSchema
        self.reportSchema = reportSchema
    }

    /// The default is the app module's bundle, including when called by hosted
    /// tests. An explicit bundle changes location only, never the admitted pins.
    static func loadBundled(bundle: Bundle? = nil) throws -> Self {
        let sourceBundle = bundle ?? appBundle
        let resources = [manifestResource, fileSchemaResource, reportSchemaResource]
        let urls = try resourceURLs(in: sourceBundle, resources: resources)
        let manifestBytes = try readResource(manifestResource, urls: urls)
        let decoded = try JSONDecoder().decode(ContractManifestV1.self, from: manifestBytes)
        try validateManifest(decoded)

        let fileDescriptor = try ActivityCompletedReportSchemaV1(
            rootTypeID: fileRootTypeID, resource: fileSchemaResource
        )
        let reportDescriptor = try ActivityCompletedReportSchemaV1(
            rootTypeID: reportRootTypeID, resource: reportSchemaResource
        )
        try validateSchema(try readResource(fileSchemaResource, urls: urls), descriptor: fileDescriptor,
                           manifest: decoded)
        try validateSchema(try readResource(reportSchemaResource, urls: urls), descriptor: reportDescriptor,
                           manifest: decoded)
        return Self(manifest: decoded, fileSchema: fileDescriptor, reportSchema: reportDescriptor)
    }

    /// Regeneration may retain the exact admitted frozen value. A later/current
    /// profile or another valid manifest can never substitute for that release.
    func admitFrozenManifest(_ frozen: ContractManifestV1) throws -> ContractManifestV1 {
        try Self.validateManifest(frozen)
        guard frozen == manifest else {
            throw ActivityCompletedReportReleaseFailureV1.unsupportedManifest
        }
        return frozen
    }

    private static func validateManifest(_ value: ContractManifestV1) throws {
        try value.validate()
        guard value.manifestID == manifestID, value.manifestVersion == manifestVersion,
              value.schemaVersion == 2, value.codec.codecVersion == 2,
              value.persistentContractSchema == ContractManifestV1.persistentContractSchema,
              value.compatibility.minimumReaderVersion == 2,
              value.compatibility.maximumReaderVersion == 2,
              value.compatibility.unknownObjectFields == .reject,
              value.compatibility.publishedVersionsImmutable,
              value.objects.count == objectDefinitionCount, value.enums.count == enumDefinitionCount else {
            throw ActivityCompletedReportReleaseFailureV1.unsupportedManifest
        }
        let roots: Set<String> = [fileRootTypeID, reportRootTypeID]
        for root in roots {
            guard let definition = value.objects.first(where: { $0.typeID == root }),
                  definition.version == 1, definition.unknownFieldPolicy == .reject else {
                throw ActivityCompletedReportReleaseFailureV1.unsupportedManifest
            }
        }
        let registry = value.reportSectionRegistry
        let expectedSections = ["identity", "service", "evidence", "limitations", "provenance", "supersession", "manifest"]
        guard registry.registryID == "v23-p03-c06-report-sections-v1", registry.registryVersion == 1,
              registry.sections.map(\.sectionID) == expectedSections,
              try WorkspaceMutationCanonicalV1.sha256(registry) == registryCanonicalSHA256,
              try WorkspaceMutationCanonicalV1.sha256(value) == manifestResource.canonicalSHA256 else {
            throw ActivityCompletedReportReleaseFailureV1.unsupportedManifest
        }
    }

    private static func resourceURLs(in bundle: Bundle,
                                     resources: [ActivityCompletedReportResourceV1]) throws -> [String: URL] {
        guard let resourceRoot = bundle.resourceURL else {
            throw ActivityCompletedReportReleaseFailureV1.unavailableBundle
        }
        let root = resourceRoot.resolvingSymlinksInPath().standardizedFileURL
        let expectedNames = Set(resources.map(\.fileName))
        var failed = false
        guard let enumerator = FileManager.default.enumerator(
            at: root, includingPropertiesForKeys: [.isRegularFileKey, .isSymbolicLinkKey, .fileSizeKey],
            options: [], errorHandler: { _, _ in failed = true; return false }
        ) else {
            throw ActivityCompletedReportReleaseFailureV1.unavailableBundle
        }
        var discovered: [String: URL] = [:]
        var inspected = 0
        for case let url as URL in enumerator {
            inspected += 1
            // Bound discovery independently of the exact bounded file reads.
            guard inspected <= 65_536 else {
                throw ActivityCompletedReportReleaseFailureV1.unavailableBundle
            }
            let name = url.lastPathComponent
            guard expectedNames.contains(name) else { continue }
            guard discovered[name] == nil else {
                throw ActivityCompletedReportReleaseFailureV1.resourceAmbiguous(name)
            }
            let values = try url.resourceValues(forKeys: [.isRegularFileKey, .isSymbolicLinkKey])
            let resolved = url.resolvingSymlinksInPath().standardizedFileURL
            guard values.isRegularFile == true, values.isSymbolicLink != true,
                  resolved == url.standardizedFileURL,
                  resolved.path.hasPrefix(root.path + "/") else {
                throw ActivityCompletedReportReleaseFailureV1.invalidResource(name)
            }
            discovered[name] = resolved
        }
        guard !failed else { throw ActivityCompletedReportReleaseFailureV1.unavailableBundle }
        for resource in resources where discovered[resource.fileName] == nil {
            throw ActivityCompletedReportReleaseFailureV1.resourceMissing(resource.fileName)
        }
        return discovered
    }

    private static func readResource(_ resource: ActivityCompletedReportResourceV1,
                                     urls: [String: URL]) throws -> Data {
        guard let url = urls[resource.fileName] else {
            throw ActivityCompletedReportReleaseFailureV1.resourceMissing(resource.fileName)
        }
        let values = try url.resourceValues(forKeys: [.fileSizeKey])
        guard values.fileSize == resource.byteCount else {
            throw ActivityCompletedReportReleaseFailureV1.invalidResource(resource.fileName)
        }
        let handle = try FileHandle(forReadingFrom: url)
        defer { try? handle.close() }
        var bytes = Data()
        while bytes.count <= resource.byteCount {
            let remaining = resource.byteCount + 1 - bytes.count
            let next = try handle.read(upToCount: min(65_536, remaining)) ?? Data()
            if next.isEmpty { break }
            bytes.append(next)
        }
        guard bytes.count == resource.byteCount, bytes.last == 0x0a,
              KernelCanonicalHashV1.sha256(bytes) == resource.rawSHA256,
              KernelCanonicalHashV1.sha256(Data(bytes.dropLast())) == resource.canonicalSHA256 else {
            throw ActivityCompletedReportReleaseFailureV1.invalidResource(resource.fileName)
        }
        // These known compiler bytes are canonical JSON plus one LF. Do not
        // normalize a generic Foundation JSON object (which could round UInt64).
        return bytes
    }

    private static func validateSchema(_ bytes: Data, descriptor: ActivityCompletedReportSchemaV1,
                                       manifest: ContractManifestV1) throws {
        let header = try JSONDecoder().decode(ActivityCompletedReportSchemaHeaderV1.self, from: bytes)
        guard header.schemaID == descriptor.projection.schemaID,
              header.dialect == descriptor.projection.dialect,
              header.reference == "#/$defs/\(descriptor.rootTypeID)",
              header.rootTypeID == descriptor.rootTypeID,
              header.manifestID == manifestID, header.manifestVersion == manifestVersion,
              header.manifestSchemaVersion == 2,
              header.manifestSHA256 == manifestResource.canonicalSHA256,
              header.codec == manifest.codec, header.compatibility == manifest.compatibility,
              header.productManifestDerived else {
            throw ActivityCompletedReportReleaseFailureV1.invalidResource(descriptor.resource.fileName)
        }
    }
}

private final class ActivityCompletedReportBundleAnchorV1: NSObject {}

/// Decode only the release header after full raw-byte authentication. The pinned
/// independent validator checks all definitions/references during generation.
private struct ActivityCompletedReportSchemaHeaderV1: Decodable {
    let schemaID: String
    let dialect: String
    let reference: String
    let rootTypeID: String
    let manifestID: String
    let manifestVersion: Int
    let manifestSchemaVersion: Int
    let manifestSHA256: String
    let codec: ContractCodecRuleV1
    let compatibility: ContractCompatibilityRuleV1
    let productManifestDerived: Bool

    private enum CodingKeys: String, CodingKey {
        case schemaID = "$id", dialect = "$schema", reference = "$ref"
        case rootTypeID = "x_assetrounds_rootTypeID"
        case manifestID = "x_assetrounds_manifestID"
        case manifestVersion = "x_assetrounds_manifestVersion"
        case manifestSchemaVersion = "x_assetrounds_manifestSchemaVersion"
        case manifestSHA256 = "x_assetrounds_manifestCanonicalSHA256"
        case codec = "x_assetrounds_codec", compatibility = "x_assetrounds_compatibility"
        case productManifestDerived = "x_assetrounds_productManifestDerived"
    }
}
