import XCTest
@testable import FieldEvidenceApp

final class S8_2GoldenAccessibilityTests: XCTestCase {
    func testGoldenFlowAccessibilitySpineAndControlMetricsAreExact() {
        let identifiers = [
            SignsRootView.welcomeScreenAccessibilityIdentifier,
            SignsRootView.addFirstSignAccessibilityIdentifier,
            NewSignView.screenAccessibilityIdentifier,
            NewSignView.siteLabelAccessibilityIdentifier,
            NewSignView.signLabelAccessibilityIdentifier,
            NewSignView.errorAccessibilityIdentifier,
            NewSignView.saveAccessibilityIdentifier,
            SignDetailView.screenAccessibilityIdentifier,
            SignDetailView.startCheckAccessibilityIdentifier,
            PreflightView.screenAccessibilityIdentifier,
            PreflightView.timeZoneAccessibilityIdentifier,
            PreflightView.timeZoneConfirmationAccessibilityIdentifier,
            PreflightView.afterDarkAccessibilityIdentifier,
            PreflightView.safePositionAccessibilityIdentifier,
            PreflightView.beginAccessibilityIdentifier,
            CaptureStepView.screenAccessibilityIdentifier,
            CaptureStepView.headingAccessibilityIdentifier,
            CaptureStepView.fixtureImportAccessibilityIdentifier,
            CaptureStepView.previewAccessibilityIdentifier,
            CaptureStepView.usePhotoAccessibilityIdentifier,
            OutcomeReviewView.outcomeScreenAccessibilityIdentifier,
            OutcomeReviewView.visibleIssueAccessibilityIdentifier,
            OutcomeReviewView.continueAccessibilityIdentifier,
            OutcomeReviewView.reviewScreenAccessibilityIdentifier,
            OutcomeReviewView.saveAccessibilityIdentifier,
            ValueReceiptView.screenAccessibilityIdentifier,
            ValueReceiptView.savedAccessibilityIdentifier,
            ValueReceiptView.viewReportAccessibilityIdentifier,
            ValueReceiptView.doneAccessibilityIdentifier,
            ReportDetailView.screenAccessibilityIdentifier,
            ReportDetailView.previewAccessibilityIdentifier,
            SignDetailView.recordWorkAccessibilityIdentifier,
            RecordWorkView.screenAccessibilityIdentifier,
            RecordWorkView.descriptionAccessibilityIdentifier,
            RecordWorkView.importFixtureAccessibilityIdentifier,
            RecordWorkView.saveAccessibilityIdentifier,
            IssueDetailView.screenAccessibilityIdentifier,
            IssueDetailView.statusAccessibilityIdentifier,
            IssueDetailView.startRecheckAccessibilityIdentifier,
            OutcomeReviewView.resolvedAccessibilityIdentifier,
            SignDetailView.resolvedIssueAccessibilityIdentifier,
            AppShellView.settingsButtonAccessibilityIdentifier,
            AppShellView.settingsScreenAccessibilityIdentifier,
            PaywallView.settingsEntryAccessibilityIdentifier,
            PaywallView.screenAccessibilityIdentifier,
            PaywallView.storeAccessibilityIdentifier,
            PaywallView.productNameAccessibilityIdentifier,
            PaywallView.productDurationAccessibilityIdentifier,
            PaywallView.productPriceAccessibilityIdentifier,
            PaywallView.trialAccessibilityIdentifier,
            PaywallView.renewalAccessibilityIdentifier,
            PaywallView.noSyncAccessibilityIdentifier,
            PaywallView.closeAccessibilityIdentifier,
        ]
        let expected = [
            "s2.welcome.screen",
            "s2.welcome.add-first-sign",
            "s2.new-sign.screen",
            "s2.new-sign.site-label",
            "s2.new-sign.sign-label",
            "s2.new-sign.error",
            "s2.new-sign.save",
            "s2.sign-detail.screen",
            "s2.sign-detail.start-check",
            "s3.preflight.screen",
            "s3.preflight.time-zone",
            "s3.preflight.time-zone-confirmed",
            "s3.preflight.after-dark",
            "s3.preflight.safe-position",
            "s3.preflight.begin",
            "s3.capture.screen",
            "s3.capture.heading",
            "s3.capture.import-fixture",
            "s3.capture.preview",
            "s3.capture.use-photo",
            "s3.outcome.screen",
            "s3.outcome.visible-issue",
            "s3.outcome.continue",
            "s3.review.screen",
            "s3.review.save-report",
            "s3.receipt.screen",
            "s3.receipt.saved",
            "s3.receipt.view-report",
            "s3.receipt.done",
            "s4.3.report-detail.screen",
            "s4.3.report-detail.preview",
            "s5.1.sign-detail.record-work",
            "s5.1.work.screen",
            "s5.1.work.description",
            "s5.1.work.import-fixture",
            "s5.1.work.save",
            "s5.1.issue.screen",
            "s5.1.issue.status",
            "s5.2.issue.start-recheck",
            "s5.2.outcome.resolved",
            "s5.2.sign-detail.resolved",
            "s1.settings.button",
            "s1.settings.screen",
            "s7.2.settings.paywall",
            "s7.2.paywall.screen",
            "s7.2.paywall.store",
            "s7.2.paywall.product-name",
            "s7.2.paywall.duration",
            "s7.2.paywall.price",
            "s7.2.paywall.trial",
            "s7.2.paywall.renewal",
            "s7.2.paywall.no-sync",
            "s7.2.paywall.close",
        ]

        XCTAssertEqual(identifiers, expected)
        XCTAssertEqual(Set(identifiers).count, identifiers.count)
        XCTAssertEqual(DesignTokens.Control.minimumHitSize, 44)
        XCTAssertEqual(
            WorklightStatusKind.allCases.map(\.rawValue),
            ["complete", "attention", "blocked", "information"]
        )
    }
}
