import Foundation
import XCTest
@testable import FieldEvidenceApp

private struct C07Corpus: Decodable { struct S: Decodable { let id: String; let selector: String; let tier: String }; let schema: String; let schemaVersion: Int; let cardID: String; let ordinal: Int; let selectors: [S]; let coverage: [String: [String]]; let lifecycle: [String]; let statusFlags: [String: Bool] }
private enum C07 {
    static let date = Date(timeIntervalSince1970: 1_788_134_400); static let digest = String(repeating: "a", count: 64)
    static func id(_ n: Int) -> UUID { UUID(uuidString: String(format: "00000000-0000-0000-0000-%012x", n))! }
    static func workspace(_ n: Int) -> WorkspaceID { .init(rawValue: id(926_000 + n)) }
    static func actor(_ w: WorkspaceID) throws -> ActorSnapshotV1 { let r = try LocalActorReferenceV1(actorReferenceID: id(927_001), workspaceID: w, displayName: "C07 recorder"); return try ActorSnapshotV1(snapshotID: id(927_002), workspaceID: w, actor: r, responsibility: .recordedBy, displayNameAtTime: r.displayName, capturedAt: date) }
    static func requirement() throws -> RoundPackageContentRequirementV1 { try .init(packageRelease: .init(packageReleaseID: digest, packageID: "c07-package", packageContentVersion: 1, packageSHA256: digest, workflowSHA256: String(repeating: "b", count: 64)), requiredContent: []) }
    static func make(_ w: WorkspaceID, previous: RoundSessionV1? = nil, state: RoundSessionStateV1, transition: RoundSessionTransitionV1, item: UUID? = nil, items: [RoundItemV1]) throws -> RoundSessionV1 { let rev = (previous?.revision ?? 0) + 1; return try .init(workspaceID: w, sessionID: id(928_000), predecessor: previous, revision: rev, mutationID: try .init(rawValue: id(929_000 + Int(rev))), state: state, transition: transition, transitionItemID: item, items: items, recordedBy: actor(w), recordedAt: date.addingTimeInterval(TimeInterval(rev))) }
    static func history(_ w: WorkspaceID) throws -> [RoundSessionV1] {
        let req = try requirement(); let initial = try (0..<2).map { try RoundItemV1(itemID: id(930_000 + $0), order: $0, selection: .init(assetID: id(931_000 + $0), siteID: id(932_000 + $0), labelAtSelection: "C07 asset \($0)"), requirement: req) }
        var all = [try make(w, state: .draft, transition: .create, items: initial)]; all.append(try make(w, previous: all.last, state: .active, transition: .start, items: all.last!.items))
        for index in initial.indices { var v = all.last!.items; let old = v[index]; let visit = try RoundItemVisitV1(visitedAt: date, recordedBy: actor(w)); v[index] = try .init(itemID: old.itemID, order: old.order, selection: old.selection, requirement: old.requirement, disposition: .visited, visit: visit); all.append(try make(w, previous: all.last, state: .active, transition: .visitItem, item: old.itemID, items: v)); var d = all.last!.items; let seen = d[index]; d[index] = try .init(itemID: seen.itemID, order: seen.order, selection: seen.selection, requirement: seen.requirement, disposition: .completed, visit: seen.visit, completion: .init(completionID: id(933_000 + index), revision: 1, completionSHA256: String(repeating: "c", count: 64))); all.append(try make(w, previous: all.last, state: .active, transition: .completeItem, item: seen.itemID, items: d)) }
        all.append(try make(w, previous: all.last, state: .completed, transition: .close, items: all.last!.items)); return all
    }
    static func inaccessibleHistory(_ w: WorkspaceID) throws -> [RoundSessionV1] {
        var all = try history(w); all = Array(all.prefix(4)); let active = all.last!; var items = active.items
        let inaccessible = items[1]; items[1] = try .init(itemID: inaccessible.itemID, order: inaccessible.order, selection: inaccessible.selection, requirement: inaccessible.requirement, disposition: .inaccessible, reason: .physicalAccessUnavailable)
        let terminal = try make(w, previous: active, state: .active, transition: .markInaccessible, item: inaccessible.itemID, items: items)
        all.append(terminal); all.append(try make(w, previous: terminal, state: .completed, transition: .close, items: terminal.items)); return all
    }
    static func permissions(_ session: RoundSessionV1, permitted: Set<UUID> = []) throws -> [FieldSectionIndexOutOfOrderPermissionV1] { try session.items.map { item in let package = item.requirement.packageRelease; return try .init(itemID:item.itemID,packageReleaseID:package.packageReleaseID,packageSHA256:package.packageSHA256,workflowSHA256:package.workflowSHA256,permitsOutOfOrderNavigation:permitted.contains(item.itemID)) } }
}
@MainActor private final class Reader: RoundSessionCurrentReadingV1 { let h: [RoundSessionV1]; init(_ h: [RoundSessionV1]) { self.h = h }; func roundSessionHistory(workspaceID: WorkspaceID, sessionID: UUID) throws -> [RoundSessionV1] { h } }
@MainActor private final class Writer: RoundSessionCanonicalWritingV1 { func commitRoundSession(_ mutation: RoundSessionMutationV1) throws -> RoundSessionMutationReceiptV1 { throw RoundSessionFailureV1.staleRevision } }
@MainActor private final class Authority: RoundSessionLiveAuthorityReadingV1 { func publishedPackageRelease(for reference: RoundPackageReleaseReferenceV1) throws -> InspectionPackageReleaseV1? { nil }; func contentReference(workspaceID: WorkspaceID, contentID: String) throws -> ContentReferenceV1? { nil }; func assetExists(workspaceID: WorkspaceID, assetID: UUID) throws -> Bool { true }; func completionMatches(workspaceID: WorkspaceID, reference: RoundItemCompletionReferenceV1) throws -> Bool { true } }
@MainActor private final class ReceiptWriter: RoundSessionCanonicalWritingV1 { let receipt: RoundSessionMutationReceiptV1; private(set) var commits = 0; init(_ receipt: RoundSessionMutationReceiptV1) { self.receipt = receipt }; func commitRoundSession(_ mutation: RoundSessionMutationV1) throws -> RoundSessionMutationReceiptV1 { guard mutation.mutationID == receipt.mutation.mutationID else { throw RoundSessionFailureV1.staleRevision }; if commits == 0 { commits = 1 }; return receipt } }
private struct FailingSearch: SearchIndexLifecyclePortV1 { func invalidateAfterCanonicalCommit(source: SearchSourceRevisionV1) async throws { throw RoundSessionFailureV1.staleRevision }; func dropProjection(workspaceID: UUID) async throws {}; func purgeWorkspace(_ workspaceID: UUID) async throws {}; func eraseAll() async throws {} }

@MainActor final class V9_26RoundSessionIntegrationTests: XCTestCase {
    func testV23P04C07G01MultiAssetSelectionOrderParityJumpAndCloseoutHandoff() throws { let c = try corpus(); check(c,"G01","GOLDEN"); let h = try C07.history(C07.workspace(1)), a = adapter(h), s = h.last!; let b = try s.items.map { try FieldSectionIndexRequirementBindingV1(itemID: $0.itemID, requirementSHA256: $0.requirement.requirementSHA256) }; let i = try a.fieldSectionIndex(at: s.reference, requirementBindings: b, packagePermissions: C07.permissions(s)); try i.validate(session:s); let p = try a.progress(at: s.reference), x = try a.closeout(at: s.reference), q = try a.searchProjection(at: s.reference), m = try a.handoffManifest(at: s.reference); XCTAssertEqual(i.completeCount, p.counts.completed); XCTAssertNil(i.nextIncomplete); XCTAssertNil(i.nextFlagged); XCTAssertEqual(x.progress,p); XCTAssertEqual(m.session,s.reference); XCTAssertEqual(m.closeoutSHA256,x.closeoutSHA256); XCTAssertEqual(m.searchProjectionSHA256,q.projectionSHA256) }
    func testV23P04C07A01PoseAnchorPositionResumeAndOutOfOrderRemainExplicit() throws { let c = try corpus(); check(c,"A01","ALTERNATE"); let h = try C07.history(C07.workspace(2)), a = adapter(h), s = h.last!; let d = try DraftResumeAnchorV1(sectionID:"round-item",fieldID:"pose-axis",selectedStableID:"pose.c36.anchor",boundedPosition:7); let b = try s.items.map { try FieldSectionIndexRequirementBindingV1(itemID:$0.itemID,requirementSHA256:$0.requirement.requirementSHA256) }; let draft = try FieldSectionIndexDraftAnchorV1(itemID:s.items[0].itemID,draftID:C07.id(940_001),anchor:d), permissions = try C07.permissions(s,permitted:[s.items[1].itemID]); let i = try a.fieldSectionIndex(at:s.reference,requirementBindings:b,draftAnchors:[draft],packagePermissions:permissions), repeatProjection = try a.fieldSectionIndex(at:s.reference,requirementBindings:b,draftAnchors:[draft],packagePermissions:permissions); try i.validate(session:s); try repeatProjection.validate(session:s); XCTAssertEqual(i.projectionSHA256,repeatProjection.projectionSHA256); XCTAssertEqual(i.sections[0].fields[0].draftAnchor,d); XCTAssertTrue(i.sections[1].fields[0].packagePermitsOutOfOrderNavigation); let changedPermissions = try C07.permissions(s); let permissionVariant = try a.fieldSectionIndex(at:s.reference,requirementBindings:b,draftAnchors:[draft],packagePermissions:changedPermissions); try permissionVariant.validate(session:s); XCTAssertNotEqual(i.projectionSHA256,permissionVariant.projectionSHA256); let changedDraft = try FieldSectionIndexDraftAnchorV1(itemID:s.items[0].itemID,draftID:C07.id(940_001),anchor:.init(sectionID:"round-item",fieldID:"pose-axis",selectedStableID:"pose.c36.anchor",boundedPosition:8)); let draftVariant = try a.fieldSectionIndex(at:s.reference,requirementBindings:b,draftAnchors:[changedDraft],packagePermissions:permissions); try draftVariant.validate(session:s); XCTAssertNotEqual(i.projectionSHA256,draftVariant.projectionSHA256); let stale = try a.fieldSectionIndex(at:s.reference,requirementBindings:[try .init(itemID:s.items[0].itemID,requirementSHA256:String(repeating:"d",count:64)),b[1]],packagePermissions:permissions); XCTAssertEqual(stale.sections[0].fields[0].anchorState,.staleRequirementFallback); XCTAssertNil(stale.sections[0].fields[0].anchor.fieldID) }
    func testV23P04C07H01DisagreementInaccessibleAndResourceFailuresRemainFailClosed() throws { let c = try corpus(); check(c,"H01","HOSTILE"); let h = try C07.inaccessibleHistory(C07.workspace(3)), a = adapter(h), s = h.last!; let stale = try RoundSessionReferenceV1(workspaceID:s.workspaceID,sessionID:s.sessionID,revision:s.revision,sessionSHA256:String(repeating:"e",count:64)); XCTAssertThrowsError(try a.progress(at:stale)); XCTAssertThrowsError(try FieldSectionIndexProjectionV1(session:s,requirementBindings:[],packagePermissions:[])); let b = try s.items.map { try FieldSectionIndexRequirementBindingV1(itemID:$0.itemID,requirementSHA256:$0.requirement.requirementSHA256) }; var foreign = try C07.permissions(s); foreign[0] = try .init(itemID:s.items[0].itemID,packageReleaseID:s.items[0].requirement.packageRelease.packageReleaseID,packageSHA256:String(repeating:"f",count:64),workflowSHA256:s.items[0].requirement.packageRelease.workflowSHA256,permitsOutOfOrderNavigation:false); XCTAssertThrowsError(try FieldSectionIndexProjectionV1(session:s,requirementBindings:b,packagePermissions:foreign)); XCTAssertEqual(s.state,.completed); XCTAssertEqual(s.counts.inaccessible,1); XCTAssertEqual(s.items[1].reason,.physicalAccessUnavailable); XCTAssertNil(s.items[1].visit); XCTAssertEqual(s.predecessor?.revision,s.revision-1); XCTAssertThrowsError(try a.closeout(at:s.reference)); XCTAssertThrowsError(try a.handoffManifest(at:s.reference)) }
    func testV23P04C07I01InterruptionJournalReplaySearchExportAndReceiptsAreBounded() async throws { let c = try corpus(); check(c,"I01","INTERRUPTION"); let h = try C07.history(C07.workspace(4)), base = h[1], successor = try C07.make(base.workspaceID,previous:base,state:.paused,transition:.pause,items:base.items), mutation = try RoundSessionMutationV1(workspaceID:base.workspaceID,expectedRevision:base.revision,mutationID:successor.mutationID,session:successor), receipt = try makeReceipt(mutation); let writer = ReceiptWriter(receipt), a = RoundSessionLifecycleAdapterV1(roundCoordinator:.init(workspaceID:base.workspaceID,reader:Reader([h[0],base]),writer:writer,authority:Authority())); let source = try SearchSourceRevisionV1(workspaceID:base.workspaceID.rawValue,generationID:C07.id(941_001),commitRevision:1); let result = try await a.save(mutation,postCommitSearchSource:source,searchLifecycle:FailingSearch()); XCTAssertEqual(result.searchDisposition,.rebuildRequired); XCTAssertEqual(result.receipt,receipt); XCTAssertEqual(result.receipt.sessionFrontier,successor.reference); XCTAssertEqual(writer.commits,1); XCTAssertEqual(try await a.save(mutation,postCommitSearchSource:source,searchLifecycle:FailingSearch()).receipt,receipt); XCTAssertEqual(writer.commits,1); XCTAssertTrue(C05RoundSessionLifecycleBoundaryV1.searchInvalidationOccursAfterCanonicalCommitOnly); XCTAssertTrue(Set(c.coverage["I01"] ?? []).contains("effect-before-receipt")) }
    func testV23P04C07R01RecoveryLifecycleDeleteEraseCompatibilityAndForwardFixStayCanonical() throws { let c = try corpus(); check(c,"R01","RECOVERY"); let h = try C07.history(C07.workspace(5)), a = adapter(h), s = h.last!; let p = try a.progress(at:s.reference), x = try a.closeout(at:s.reference), q = try a.searchProjection(at:s.reference), m = try a.handoffManifest(at:s.reference), d = try a.deletePreview(at:s.reference), e = try a.lifecycleEvidence(at:s.reference); XCTAssertEqual(try a.recoverProgress(p),p); XCTAssertEqual(try a.recoverCloseout(x),x); XCTAssertEqual(try a.recoverSearch(q),q); XCTAssertEqual(try a.recoverHandoff(m),m); XCTAssertEqual(d.ordinaryDisposition,.preserveCanonicalHistory); XCTAssertEqual(d.eraseDisposition,.workspaceEraseOnly); XCTAssertEqual(e.dimensions,C07RoundSessionLifecycleDimensionV1.allCases.sorted{$0.rawValue<$1.rawValue}); XCTAssertTrue(e.canonicalHistoryReused && e.derivedOnly); let archived = try C07.make(s.workspaceID,previous:s,state:.archived,transition:.archive,items:s.items), staleAdapter = adapter(h + [archived]); XCTAssertThrowsError(try staleAdapter.recoverProgress(p)); XCTAssertThrowsError(try staleAdapter.recoverCloseout(x)); XCTAssertThrowsError(try staleAdapter.recoverSearch(q)); XCTAssertThrowsError(try staleAdapter.recoverHandoff(m)); XCTAssertTrue(Set(c.lifecycle).isSuperset(of:Set(["BACKUP","REPLACE_RESTORE","CLONE","FORK","IMPORT","EXPORT","REPORT","DELETE","ERASE","RETENTION","COMPATIBILITY","FORWARD_FIX"]))) }
    private func adapter(_ h:[RoundSessionV1])->RoundSessionLifecycleAdapterV1 { .init(roundCoordinator:.init(workspaceID:h.last!.workspaceID,reader:Reader(h),writer:Writer(),authority:Authority())) }
    private func makeReceipt(_ mutation: RoundSessionMutationV1) throws -> RoundSessionMutationReceiptV1 { let replica = ReplicaID(rawValue:C07.id(942_001)), identity = try WorkspaceReplicaIdentityV1(workspaceID:mutation.workspaceID,replicaID:replica), concurrency = try mutation.concurrencyIdentity, expected = try WorkspaceExpectedRevisionV1(workspaceID:mutation.workspaceID,generationID:C07.id(943_001),writerInstanceID:C07.id(944_001),workspaceRevision:0,entityRevisions:[.init(identity:concurrency,revision:mutation.expectedRevision)]), envelope = try MutationEnvelopeV1(request:.init(mutationID:mutation.mutationID,expectedRevision:expected,command:.applyRoundSession(mutation)),identity:identity), resulting = try WorkspaceExpectedRevisionV1(workspaceID:mutation.workspaceID,generationID:expected.generationID,writerInstanceID:expected.writerInstanceID,workspaceRevision:1,entityRevisions:[.init(identity:concurrency,revision:mutation.session.revision)]), raw = try MutationReceiptV1(identity:.init(workspaceID:mutation.workspaceID,replicaID:replica,localSequence:1),envelope:envelope,resultingRevision:try .init(resulting),postImages:[try mutation.mutationPostImage],committedAt:C07.date); return try .init(mutation:mutation,mutationReceipt:raw) }
    private func corpus() throws -> C07Corpus { let root=URL(fileURLWithPath:#filePath).deletingLastPathComponent().deletingLastPathComponent(); return try JSONDecoder().decode(C07Corpus.self,from:Data(contentsOf:root.appendingPathComponent("FieldEvidenceAppTests/Fixtures/V22/Rounds/V22P04C07RoundSessionFieldFlowCorpusV1.json"))) }
    private func check(_ c:C07Corpus,_ id:String,_ tier:String) { XCTAssertEqual(c.schema,"V22P04C07RoundSessionFieldFlowCorpusV1"); XCTAssertEqual(c.schemaVersion,1); XCTAssertEqual(c.cardID,"V23-P04-C07"); XCTAssertEqual(c.ordinal,95); XCTAssertEqual(c.selectors.map(\.id),["G01","A01","H01","I01","R01"]); XCTAssertEqual(c.selectors.first{$0.id==id}?.selector,"V23-P04-C07-\(id)"); XCTAssertEqual(c.selectors.first{$0.id==id}?.tier,tier); XCTAssertTrue(c.statusFlags.values.allSatisfy{!$0}) }
}
