import Foundation

struct FieldReferenceImportItemV1:Equatable,Sendable{let reference:ContentReferenceV1;let locator:ContentLocatorV1;let bytes:Data;init(reference:ContentReferenceV1,locator:ContentLocatorV1,bytes:Data)throws{try ContentIntegrityV1.verify(reference:reference,locator:locator,observed:.init(byteLength:Int64(bytes.count),sha256:KernelCanonicalHashV1.sha256(bytes)));self.reference=reference;self.locator=locator;self.bytes=bytes}}
struct FieldReferenceImportPlanV1:Equatable,Sendable{let release:FieldReferenceReleaseV1;let items:[FieldReferenceImportItemV1];init(release:FieldReferenceReleaseV1,items:[FieldReferenceImportItemV1])throws{try release.validateContent(references:items.map(\.reference),locators:items.map(\.locator));guard items.count==release.manifest.entries.count,items.reduce(0,{$0+$1.bytes.count})<=64*1_048_576 else{throw FieldReferencePackFailureV1.invalidValue};self.release=release;self.items=items}}
struct FieldReferenceWriteReceiptV1:Codable,Equatable,Sendable{let mutationID:MutationIDV1;let postImageSHA256:String;let canonicalMutationReceiptSHA256:String;init(mutationID:MutationIDV1,postImageSHA256:String,canonicalMutationReceiptSHA256:String)throws{try FieldReferenceValidationV1.digest(postImageSHA256);try FieldReferenceValidationV1.digest(canonicalMutationReceiptSHA256);self.mutationID=mutationID;self.postImageSHA256=postImageSHA256;self.canonicalMutationReceiptSHA256=canonicalMutationReceiptSHA256}}
protocol FieldReferenceContentAuthorityV1:Sendable{func persist(_ plan:FieldReferenceImportPlanV1)async throws;func validateReadback(_ plan:FieldReferenceImportPlanV1)async throws;func readinessInputs(release:FieldReferenceReleaseV1,binding:FieldReferenceBindingV1,evaluatedAt:Date)async throws->FieldReferenceReadinessInputsV1;func discardIfUnbound(_ plan:FieldReferenceImportPlanV1)async throws}
protocol FieldReferencePackWritingV1:Sendable{func acceptedReleaseReceipt(for release:FieldReferenceReleaseV1)async throws->FieldReferenceWriteReceiptV1?;func appendRelease(_ release:FieldReferenceReleaseV1)async throws->FieldReferenceWriteReceiptV1;func acceptedBindingReceipt(for binding:FieldReferenceBindingV1,release:FieldReferenceReleaseV1)async throws->FieldReferenceWriteReceiptV1?;func appendBinding(_ binding:FieldReferenceBindingV1,release:FieldReferenceReleaseV1)async throws->FieldReferenceWriteReceiptV1}

actor FieldReferencePackCoordinatorV1{
    private let content:any FieldReferenceContentAuthorityV1;private let writer:any FieldReferencePackWritingV1
    init(content:any FieldReferenceContentAuthorityV1,writer:any FieldReferencePackWritingV1){self.content=content;self.writer=writer}
    func importRelease(_ plan:FieldReferenceImportPlanV1)async throws->FieldReferenceWriteReceiptV1{try plan.release.validate();if let r=try await writer.acceptedReleaseReceipt(for:plan.release){try validate(r,mutationID:plan.release.mutationID,digest:plan.release.releaseSHA256);try await content.validateReadback(plan);return r};do{try await content.persist(plan);try await content.validateReadback(plan);let r=try await writer.appendRelease(plan.release);try validate(r,mutationID:plan.release.mutationID,digest:plan.release.releaseSHA256);return r}catch{try? await content.discardIfUnbound(plan);throw error}}
    func bind(_ binding:FieldReferenceBindingV1,to release:FieldReferenceReleaseV1)async throws->FieldReferenceWriteReceiptV1{try binding.validate(release:release);let inputs=try await content.readinessInputs(release:release,binding:binding,evaluatedAt:binding.boundAt);guard inputs.evaluatedAt==binding.boundAt,inputs.policy == .exactLocalContentV1 else{throw FieldReferencePackFailureV1.staleBinding};let readiness=try FieldReferenceOfflineReadinessV1(release:release,binding:binding,inputs:inputs);try readiness.validate(recomputedFrom:inputs,release:release,binding:binding);guard readiness.availability == .readyOffline,readiness.missingContentIDs.isEmpty else{throw FieldReferencePackFailureV1.missingContent};if let r=try await writer.acceptedBindingReceipt(for:binding,release:release){try validate(r,mutationID:binding.mutationID,digest:binding.bindingSHA256);return r};let r=try await writer.appendBinding(binding,release:release);try validate(r,mutationID:binding.mutationID,digest:binding.bindingSHA256);return r}
    private func validate(_ r:FieldReferenceWriteReceiptV1,mutationID:MutationIDV1,digest:String)throws{guard r.mutationID==mutationID,r.postImageSHA256==digest else{throw FieldReferencePackFailureV1.divergentRetry}}
}
