#!/usr/bin/env python3
"""Check the exact completed-report app release; optionally regenerate reviewed pins.

Default checks do not write repository files. --output writes a report only after
success. --materialize regenerates the three resources and the marked Swift/test
pin sections after all input, compiler, validator and candidate checks pass.
Rebind the explicit source pins/counts here only with the corresponding reviewed
wire/catalog change. --self-test exercises this real CLI in an isolated normal
repository-layout fixture, including read-only and failed-command guarantees.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
SCRIPT_PATH = "Scripts/test-v23-activity-completed-release.py"
COMPILER_PATH = "Scripts/v23/activity_completed_contracts.py"
MANIFEST_PATH = "docs/design/v23/tooling/ActivityCompletedContractManifestV1.json"
TYPE_PATH = "FieldEvidenceApp/Domain/Activities/ActivityCompletedFileContractsV1.swift"
SWIFT_PATH = "FieldEvidenceApp/Domain/Reporting/ActivityCompletedReportReleaseV1.swift"
TEST_PATH = "FieldEvidenceAppTests/V23ActivityCompletedReportReleaseTests.swift"
PUBLISHED_PATH = "docs/design/v23/tooling/V23P03C06ContractManifestV1.json"
VALIDATOR_PATH = "Scripts/v21-contracts/portable_contract_validator_v1.py"
LOCK_PATH = "Scripts/v21-contracts/portable-contract-validator.lock.json"
RESOURCE_DIRECTORY = "FieldEvidenceApp/Resources/Contracts"
ROOTS = ("activity-completed-file-v1", "activity-completed-report-v1")
MANIFEST_CANONICAL_SHA = "7ed5d023b813d3c4363e346e393bb0aec2d9ef87b78a9aef8a79405d5ae1b2ac"
SOURCE_OBJECTS = 249
SOURCE_ENUMS = 139
SOURCE_PINS = {
    COMPILER_PATH: "6b15883c1ca0291bd3662d433f12050d851ad503573c95bd6dbc8cebbad93447",
    MANIFEST_PATH: "135cb528eb0eb7748887b43e98f4c723182d2663c9fe6dbe61f6f1f8e0ce57b2",
    TYPE_PATH: "cb1ce4b63c954cbb1b38c2a52362c10c886700995904b7b38939b5bca2c31fd4",
    PUBLISHED_PATH: "b142747430f74fc3b2d0b403f9e60bcf08d3ba49f5e1249a2790d95eb0a3643c",
    "Scripts/v23/p03_c06_contracts.py": "2938e0c203fafb17115ccbaedc8c76d30f066c4a2a621f86a308857658c273ce",
    VALIDATOR_PATH: "7a6ce17a71e55933a121e60ee11c373b77720f33eddc9d55d4597c19452f0173",
    LOCK_PATH: "69e23865c4114792f9f62d2eab73a06ed85623e01e68c96fcccb79dfdb913862",
}


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def canonical(value: object) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()


def require(value: bool, message: str) -> None:
    if not value:
        raise RuntimeError(message)


def run(*arguments: object, expected: int = 0) -> dict:
    result = subprocess.run([sys.executable, "-B", *map(str, arguments)], capture_output=True, text=True)
    require(result.returncode == expected,
            f"command failed ({result.returncode}): {arguments!r}: {result.stdout[:1500]} {result.stderr[:1500]}")
    return json.loads(result.stdout)


def metadata(relative: str, data: bytes) -> dict:
    require(data == canonical(json.loads(data)) + b"\n", f"not canonical with one LF: {relative}")
    return {"path": relative, "byteCount": len(data), "rawSHA256": sha(data), "canonicalSHA256": sha(data[:-1])}


def section_bytes(original: bytes, marker: str, generated: str) -> bytes:
    text = original.decode("utf-8")
    require("\r" not in text, f"non-LF Swift section source: {marker}")
    pattern = rf"(?m)^([ \t]*)// BEGIN GENERATED {marker}\n.*?^\1// END GENERATED {marker}$"
    matches = list(re.finditer(pattern, text, re.DOTALL))
    require(len(matches) == 1, f"missing or duplicate generated section: {marker}")
    match = matches[0]
    indent = match[1]
    block = indent + f"// BEGIN GENERATED {marker}\n"
    block += "\n".join(indent + line if line else "" for line in generated.splitlines())
    block += "\n" + indent + f"// END GENERATED {marker}"
    return (text[:match.start()] + block + text[match.end():]).encode("utf-8")


def swift_sections(outputs: list[dict], registry_sha: str, source: bytes, tests: bytes) -> dict[str, bytes]:
    lines = ['static let manifestID = "activity-completed-contract-manifest-v1"',
             'static let manifestVersion = 1', f'static let objectDefinitionCount = {SOURCE_OBJECTS}',
             f'static let enumDefinitionCount = {SOURCE_ENUMS}',
             f'static let fileRootTypeID = "{ROOTS[0]}"', f'static let reportRootTypeID = "{ROOTS[1]}"',
             f'static let registryCanonicalSHA256 = "{registry_sha}"', '',
             '// Generated by the pinned actual-manifest compiler. Raw bytes have one final',
             '// LF; canonical hashes exclude it. Published V1 resources remain unchanged.']
    for name, output in zip(("manifestResource", "fileSchemaResource", "reportSchemaResource"), outputs):
        lines.extend([f'static let {name} = ActivityCompletedReportResourceV1(',
            f'    fileName: "{Path(output["path"]).name}", byteCount: {output["byteCount"]:_},',
            f'    rawSHA256: "{output["rawSHA256"]}",',
            f'    canonicalSHA256: "{output["canonicalSHA256"]}"', ')'])
    expectations = [
        'XCTAssertEqual(manifest.manifestID, "activity-completed-contract-manifest-v1")',
        'XCTAssertEqual(manifest.schemaVersion, 2)', 'XCTAssertEqual(manifest.codec.codecVersion, 2)',
        f'XCTAssertEqual(manifest.objects.count, {SOURCE_OBJECTS})',
        f'XCTAssertEqual(manifest.enums.count, {SOURCE_ENUMS})',
        'XCTAssertEqual(try WorkspaceMutationCanonicalV1.sha256(manifest),',
        f'               "{MANIFEST_CANONICAL_SHA}")']
    return {
        SWIFT_PATH: section_bytes(source, "COMPLETED RELEASE PINS", "\n".join(lines)),
        TEST_PATH: section_bytes(tests, "COMPLETED RELEASE EXPECTATIONS", "\n".join(expectations)),
    }


def resource_paths() -> list[str]:
    return [f"{RESOURCE_DIRECTORY}/ActivityCompletedContractManifestV1.json"] + [
        f"{RESOURCE_DIRECTORY}/OpenJSON/{root}.schema.json" for root in ROOTS]


def dependencies(root: Path) -> list[str]:
    for relative, digest in SOURCE_PINS.items():
        require(sha((root / relative).read_bytes()) == digest, f"input drift: {relative}")
    lock = json.loads((root / LOCK_PATH).read_bytes())
    locked_paths = []
    for row in lock["files"]:
        relative = row["path"]
        require(not Path(relative).is_absolute() and ".." not in Path(relative).parts, "invalid locked path")
        data = (root / relative).read_bytes()
        require(len(data) == row["byteCount"] and sha(data) == row["sha256"], f"locked dependency drift: {relative}")
        locked_paths.append(relative)
    return sorted(set(SOURCE_PINS) | set(locked_paths) | {SWIFT_PATH, TEST_PATH, SCRIPT_PATH})


def check(root: Path, materialize: bool, output: Path | None) -> tuple[dict, dict[str, bytes], list[str]]:
    dependent_paths = dependencies(root)
    require((root / SCRIPT_PATH).read_bytes() == Path(__file__).resolve().read_bytes(),
            "repository checker differs from the actual command entry point")
    owned_paths = resource_paths() + [SWIFT_PATH, TEST_PATH]
    if output is not None:
        protected = {(root / value).resolve() for value in dependent_paths + owned_paths}
        require(output.resolve() not in protected, "report output overlaps a release input or generated source")
        require(output.parent.is_dir(), "report output parent must already exist")
        require(not output.exists() or output.is_file(), "report output must be a file")
    source = (root / SWIFT_PATH).read_bytes()
    tests = (root / TEST_PATH).read_bytes()
    manifest_bytes = (root / MANIFEST_PATH).read_bytes()
    manifest = json.loads(manifest_bytes)
    require(sha(canonical(manifest)) == MANIFEST_CANONICAL_SHA, "manifest canonical drift")
    require(len(manifest["objects"]) == SOURCE_OBJECTS and len(manifest["enums"]) == SOURCE_ENUMS,
            "catalog count drift")
    published = json.loads((root / PUBLISHED_PATH).read_bytes())
    for key in ("objects", "enums"):
        current = {value["typeID"]: value for value in manifest[key]}
        require(all(current[value["typeID"]] == value for value in published[key]), f"published {key} changed")
    require(manifest["reportSectionRegistry"] == published["reportSectionRegistry"], "registry changed")

    candidates = {resource_paths()[0]: manifest_bytes}
    outputs = [metadata(resource_paths()[0], manifest_bytes)]
    compiler = root / COMPILER_PATH
    validator = root / VALIDATOR_PATH
    with tempfile.TemporaryDirectory(prefix="activity-completed-release-") as temporary:
        temp = Path(temporary)
        for index, root_type in enumerate(ROOTS, start=1):
            schema_path = temp / f"{root_type}.schema.json"
            run(compiler, "--manifest", root / MANIFEST_PATH, "--root-type-id", root_type, "--schema-id",
                f"https://schemas.assetrounds.local/v23/p03/c06/{root_type}/schema", "--output", schema_path)
            schema_bytes = schema_path.read_bytes()
            require(run(validator, "--schema", schema_path, "--meta-only")["valid"],
                    "metaschema/reference audit failed")
            schema = json.loads(schema_bytes)
            require(schema["$ref"] == f"#/$defs/{root_type}" and schema["x_assetrounds_rootTypeID"] == root_type,
                    "root binding differs")
            require(schema["x_assetrounds_manifestCanonicalSHA256"] == MANIFEST_CANONICAL_SHA,
                    "schema manifest digest differs")
            require(len(schema["$defs"]) == SOURCE_OBJECTS + SOURCE_ENUMS, "definition coverage differs")
            relative = resource_paths()[index]
            candidates[relative] = schema_bytes
            outputs.append(metadata(relative, schema_bytes))
        report = {"schemaVersion": 1, "projectionVersion": "activity-completed-report-v1",
                  "snapshotID": "snapshot", "snapshotSHA256": "a" * 64,
                  "manifestSHA256": "b" * 64, "profileBindingSHA256": "c" * 64,
                  "nodes": [{"semanticID": "node", "sectionID": "identity", "role": "fact",
                             "label": "Label", "value": "Value"}], "semanticSHA256": "d" * 64}
        instance_path = temp / "report.json"
        instance_path.write_bytes(canonical(report))
        schema_path = temp / "activity-completed-report-v1.schema.json"
        require(run(validator, "--schema", schema_path, "--instance", instance_path)["valid"], "report shape rejected")
        report["unknown"] = True
        instance_path.write_bytes(canonical(report))
        require(not run(validator, "--schema", schema_path, "--instance", instance_path, expected=1)["valid"],
                "unknown report field admitted")

    registry_sha = sha(canonical(manifest["reportSectionRegistry"]))
    candidates.update(swift_sections(outputs, registry_sha, source, tests))
    if not materialize:
        for relative, expected in candidates.items():
            require((root / relative).read_bytes() == expected, f"generated release differs: {relative}")
    methods = re.findall(r"^    func (test[A-Za-z0-9_]+)\(", candidates[TEST_PATH].decode(), re.MULTILINE)
    require(len(methods) == 9 and len(set(methods)) == 9, "release test census differs")
    authored_pins = []
    for relative in (SWIFT_PATH, TEST_PATH, SCRIPT_PATH):
        data = candidates[relative] if relative in candidates else (root / relative).read_bytes()
        require(b"\r" not in data and data.endswith(b"\n"), f"non-LF source: {relative}")
        require(all(line.rstrip() == line for line in data.splitlines()), f"trailing whitespace: {relative}")
        authored_pins.append({"path": relative, "byteCount": len(data),
                              "rawSHA256": sha(data), "normalizedLFSHA256": sha(data)})
    result = {"mode": "SOURCE_CLI_ONLY", "outputs": outputs, "authoredSourcePins": authored_pins,
              "inputPins": SOURCE_PINS, "manifestCanonicalSHA256": MANIFEST_CANONICAL_SHA,
              "registryCanonicalSHA256": registry_sha,
              "checks": ["source and every locked validator/metaschema dependency pin",
                         "published29objects15enums7sections unchanged", "actual CLI byte replay",
                         "both actual roots official metaschema and complete reference audit",
                         "actual report schema positive/closed hostile shape", "Swift resource pins and test expectations exact",
                         "nine XCTest method census and LF/whitespace checks"],
              "testClass": "V23ActivityCompletedReportReleaseTests", "testMethods": methods,
              "nativeCompilation": False, "bundledRuntimeTests": "NOT_RUN", "acceptance": False}
    return result, candidates, dependent_paths


def tree_snapshot(root: Path) -> dict[str, tuple[str, int]]:
    return {path.relative_to(root).as_posix(): (sha(path.read_bytes()), path.stat().st_mtime_ns)
            for path in root.rglob("*") if path.is_file()}


def self_test(root: Path, inputs: list[str]) -> list[str]:
    checks = []
    # Keep fixture prefixes short for deeply nested Windows worktrees.
    with tempfile.TemporaryDirectory(prefix="ar-") as temporary:
        parent = Path(temporary)
        fixture = parent / "r"
        for relative in sorted(set(inputs + resource_paths())):
            target = fixture / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(root / relative, target)
        script = fixture / SCRIPT_PATH
        original = tree_snapshot(fixture)
        result = run(script)
        require(result["nativeCompilation"] is False and tree_snapshot(fixture) == original,
                "default command modified fixture")
        checks.append("real CLI default root and no repository mutation")
        report_path = parent / "report.json"
        run(script, "--root", fixture, "--output", report_path)
        require(json.loads(report_path.read_bytes())["outputs"] == result["outputs"] and
                tree_snapshot(fixture) == original, "explicit output modified repository")
        checks.append("explicit root and report-only output")
        run(script, "--materialize")
        require(tree_snapshot(fixture) == original, "unchanged materialize rewrote files")
        checks.append("unchanged materialize has no file effects")

        (fixture / resource_paths()[0]).unlink()
        (fixture / resource_paths()[1]).write_bytes(b"stale schema\n")
        swift_path = fixture / SWIFT_PATH
        source_bytes = swift_path.read_bytes()
        changed_source = source_bytes.replace(f"static let objectDefinitionCount = {SOURCE_OBJECTS}".encode(),
                                              b"static let objectDefinitionCount = 1")
        require(changed_source != source_bytes, "source mutation did not apply")
        swift_path.write_bytes(changed_source)
        test_path = fixture / TEST_PATH
        test_bytes = test_path.read_bytes()
        changed_tests = test_bytes.replace(f"manifest.objects.count, {SOURCE_OBJECTS}".encode(),
                                          b"manifest.objects.count, 1")
        require(changed_tests != test_bytes, "test mutation did not apply")
        test_path.write_bytes(changed_tests)
        run(script, "--materialize")
        require({path: value[0] for path, value in tree_snapshot(fixture).items()} ==
                {path: value[0] for path, value in original.items()}, "materialize did not restore exact bytes")
        checks.append("materialize restores resource bytes and both generated Swift sections together")

        def reject(relative: str, missing: bool, materialize: bool) -> None:
            target = fixture / relative
            saved = target.read_bytes()
            if missing:
                target.unlink()
            else:
                target.write_bytes(saved + b" ")
            sentinel = b"preserve existing report"
            report_path.write_bytes(sentinel)
            before = tree_snapshot(fixture)
            arguments = [script, "--output", report_path]
            if materialize:
                arguments.append("--materialize")
            failure = run(*arguments, expected=1)
            require(failure.get("valid") is False and tree_snapshot(fixture) == before and
                    report_path.read_bytes() == sentinel, f"failed command changed output: {relative}")
            target.write_bytes(saved)

        for relative in (COMPILER_PATH, MANIFEST_PATH, TYPE_PATH, SWIFT_PATH, TEST_PATH, VALIDATOR_PATH, LOCK_PATH):
            reject(relative, missing=True, materialize=True)
        checks.append("missing dependencies fail before materialize/report output (7 cases)")
        compiler_path = fixture / COMPILER_PATH
        compiler_bytes = compiler_path.read_bytes()
        compiler_path.unlink()
        absent_report = parent / "must-not-be-created.json"
        before = tree_snapshot(fixture)
        run(script, "--materialize", "--output", absent_report, expected=1)
        require(not absent_report.exists() and tree_snapshot(fixture) == before,
                "failed materialize created report or changed source")
        compiler_path.write_bytes(compiler_bytes)
        checks.append("failure does not create an absent report")
        for relative in (COMPILER_PATH, MANIFEST_PATH, TYPE_PATH, VALIDATOR_PATH, LOCK_PATH,
                         "TestSupport/PortableContracts/JSONSchemaDraft202012/schema.json"):
            reject(relative, missing=False, materialize=True)
        checks.append("source/validator/metaschema drift fails without output (6 cases)")
        reject(resource_paths()[0], missing=True, materialize=False)
        reject(resource_paths()[1], missing=False, materialize=False)
        reject(SWIFT_PATH, missing=False, materialize=False)
        checks.append("missing/stale generated resources and Swift fail read-only (3 cases)")
        before = tree_snapshot(fixture)
        run(script, "--output", fixture / TYPE_PATH, expected=1)
        require(tree_snapshot(fixture) == before, "report overwrote a release input")
        checks.append("report cannot overwrite input/generated source")
    return checks


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1],
                        help="normal repository root (defaults to this script's parent repository)")
    parser.add_argument("--output", type=Path, help="optional report file; parent must exist; written only on success")
    parser.add_argument("--materialize", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    try:
        root = args.root.resolve()
        require(not (args.materialize and args.self_test), "run self-test separately from materialize")
        result, candidates, inputs = check(root, args.materialize, args.output)
        if args.self_test:
            result["cliRegressionChecks"] = self_test(root, inputs)
        # Validation failures above leave every source/resource/report untouched.
        # Filesystem write failures are reported; this is not a multi-file transaction.
        if args.materialize:
            for relative, data in candidates.items():
                target = root / relative
                if not target.is_file() or target.read_bytes() != data:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_bytes(data)
        encoded = json.dumps(result, indent=2) + "\n"
        if args.output is not None:
            args.output.write_text(encoded, encoding="utf-8", newline="\n")
        print(encoded, end="")
        return 0
    except (OSError, RuntimeError, ValueError, KeyError) as error:
        print(json.dumps({"valid": False, "error": str(error)}, sort_keys=True))
        return 1


if __name__ == "__main__":
    sys.exit(main())
