#!/usr/bin/env python3
"""Generate the deterministic V23-P04-C08 tooling artifacts.

Only the five generated paths declared by :mod:`p04_c08_contracts` are
written.  ``--check`` performs a byte-for-byte comparison and never writes.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

os.environ["PYTHONDONTWRITEBYTECODE"] = "1"
sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import p04_c08_contracts as contracts  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, help=argparse.SUPPRESS)
    parser.add_argument("--apply", action="store_true", help="write generated bytes")
    parser.add_argument("--check", action="store_true", help="check generated bytes without writing")
    args = parser.parse_args()
    if args.apply == args.check:
        parser.error("choose exactly one of --apply or --check")
    root = args.root.resolve() if args.root else ROOT
    try:
        rendered = contracts.outputs(root)
    except Exception as error:  # pragma: no cover - CLI diagnostic path
        print("C08 generator FAIL_STATIC:" + str(error), file=sys.stderr)
        return 1
    stale = [path for path, expected in rendered.items() if not (root / path).is_file() or (root / path).read_bytes() != expected]
    if args.check:
        if stale:
            print("C08 generator check FAIL_STATIC_STALE")
            print("stale=" + ",".join(stale))
            return 1
        result = "PASS_STATIC_SEALED" if contracts.FINAL_HASHES_SEALED else "PASS_STATIC_PROVISIONAL"
        print("C08 generator check " + result)
        return 0
    for path, data in rendered.items():
        destination = root / path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
    result = "SEALED" if contracts.FINAL_HASHES_SEALED else "PROVISIONAL"
    print(f"C08 generator apply PASS_STATIC_{result} generated={len(rendered)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
