#!/usr/bin/env python3
"""Generate the deterministic C07 tooling artifacts.

The generator owns exactly the schema, contract, evidence, brand, and tooling
manifest paths declared by :mod:`p04_c07_contracts`.  It never edits product
source lanes or coordination state.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

os.environ["PYTHONDONTWRITEBYTECODE"] = "1"
sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import p04_c07_contracts as contracts  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="write generated artifact bytes")
    parser.add_argument("--check", action="store_true", help="check generated bytes without writing")
    args = parser.parse_args()
    if args.apply == args.check:
        parser.error("choose exactly one of --apply or --check")

    try:
        rendered = contracts.outputs(ROOT)
    except Exception as error:  # pragma: no cover - CLI diagnostic path
        print("C07 generator FAIL_STATIC:" + str(error), file=sys.stderr)
        return 1

    stale = [
        path for path, expected in rendered.items()
        if not (ROOT / path).is_file() or (ROOT / path).read_bytes() != expected
    ]
    if args.check:
        result = "PASS_STATIC_SEALED" if contracts.FINAL_HASHES_SEALED else "PASS_STATIC_PROVISIONAL"
        if stale:
            print("C07 generator check FAIL_STATIC_STALE")
            print("stale=" + ",".join(stale))
            return 1
        print("C07 generator check " + result)
        return 0

    for path, data in rendered.items():
        destination = ROOT / path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
    result = "SEALED" if contracts.FINAL_HASHES_SEALED else "PROVISIONAL"
    print(f"C07 generator apply PASS_STATIC_{result}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
