# Exact retained source ABI, source-only

Root direction349fbc and independent minimumcfd77 apply. Loan fields: generationID, workspaceIdentity, storeSchemaRelease, operationID, originBinding. Methods requireCurrentBinding(), requireMatchesContext(_ actualContext:ModelContext), observeRegisteredGraph(frame:EraseAllService.EraseTargetGraphQueryFrameV4)->EraseSchema2CompleteTargetGraphObservationV4, observeRegisteredJournal(frame:MutationJournalStoreV1.EraseTargetZeroJournalQueryFrameV4)->EraseTargetZeroJournalObservationV4, requireRegisteredGraphObservation(_ actual:EraseSchema2CompleteTargetGraphObservationV4). Actual Factory private constructor holds the SAME retained Session private container/context/config/model.sqlite/real reader/EX source, and its exact graph result object is retained BEFORE Journal can consume it. Frame observe(producer:context:) is internal but frame constructors are fileprivate in their owner modules; no general context getter/body is added. All callers retain actual IO/loan before open; permanent revocation at lexical exit.

The Service frame executes all registered published-empty content/schema predicates; Journal is its separate fixed component. It positively fetches ALL WorkspaceMutationStateRow records and requires one actual target/workspace/replica zero state, exact empty deletion ledger and clean context. It never substitutes expected zero checkpoint bytes for actual stored history. Journal must freshly query its complete mutableSemanticBasis/rowInventory on the SAME loan/context and validate actual stored checkpoint/global state/zero history; export/private semantic basis reuse can be factored without ordinary maintenance mode or new context.

Service graph DATA is not a bridge/capability; Factory privately couples it and the genuine Journal result to complete full11/kind/SHA image-before/image-after and checked IO. Consumer-complete final seal additionally requires actual alias drain/target-affecting close, final complete equal image, P/preparation/final Sources/Progress/C and all actual consumer receipts. No actual seal is issued yet. Full legacy B remains required on missing/changed lawful origins.

Fixed durable tuple stores versions, route UInt8, five UUIDs, PersistentSchemaRelease closed UInt16 code, ten UInt64 counts and twenty-three raw SHA256 values. No image rows/DB/freeform family strings/ID normalization are embedded; actual full11 root/pointer/manifest facts remain bound by subject and actual final physical image. Conservative fixed tuple budget4096 bytes includes framing; exact codec arithmetic and byte grammar remain Store-owned. This estimate is not capacity/runtime approval. Current compatibility freshly runs current schema/enrollment/Journal grammar checks; a supported matching semantic interpretation may use A only after actual full image equality. Differing/unproven interpretation routes to genuine complete B, never metadata-only success or permanent valid-state exclusion.
