# Physical generic successor v5 interfaces

GPT-6.1 Sol xhigh; candidate-only source, no installation or authority claim. V4 is immutable and superseded for two concrete coupling refusals: capturedScope.operationID compares to actual operation.operationID (Router ticket), and generic metadata parent is ScratchDataV1/ plus its actual relativeDirectory. Intent.eraseID remains separately bound by genuine publication lineage.

Factory's EraseSchema2ColdOriginalPairAccountingRosterV1.Pair now contains PURE immutable member paths/full11/observed9/SHA/count/device/inode/generic metadata. No restarted DATA reconstructs prior runtime policy objects. The live makeOriginalPairAccountingRoster(originalP:capturedOperationsTree:capturedScope:publication:store:operation:) retains complete real typed scanner observations and actual original Store publication checks. A cold source mint still needs the actual authenticated Store source observation/header/complete row iterator/current token.

schema2ColdCurrentOwnedTree gains genericScope: OriginalEraseSealedGenericObservationScopeV1? alongside the exact canonical Current/Initial or separate FirstCapture routes. It consumes sealed PFP fb302 with Router V9 scope16941. Generic scope roles must be positive intact pair or genuine strict single survivor; C16 role must be ordinary for a generic role, FirstCapture and sealed generic cannot overlap. Old strict default and ordinary postRetiredTree onward bytes are unchanged. Both pair names/current11/9/SHA/policies count and are independently checked; unique physical payload charge uses only privately proved typed membership.

Observer gains lexical withSealedGenericScope and captureFirstWithSealedGenericScope. Original Initial capture can receive actual genericScope too. Neither wrapper keeps a G scope across await nor rebases its immutable first snapshot.

Physical observeInitialComplete / observeComplete / requireComplete / visitCompleteProjection accept the actual lexical genericScope. performOneTarget(...genericScopeProvider:) obtains genuine current scope before and AFTER its ONE assigned unlink; the central provider revokes the preimage and reissues an actual PREPARING loss observation before postimage IO. Nil preserves strict ordinary predicates. Physical code constructs no scope, record token, source permission or nlink2 effect authority.

GenericPairLoss distinguishes actual ownedUnlink from preparingAbsenceReadback and records immutable original Row/accountingSHA, exact consumed original/actual path, survivor actual path, actual before/after full11 and SHA. GenericPairFinalLoss distinguishes the actual last unlink from positive last-name absence replay. Replay actualBeforeFullFact is nil; no invented pre-loss observation is supplied. The required private V9 requireOwnedGenericEvolutionForOriginalPath(path:) begins from the immutable fixed path and proves complete authenticated source-table membership/absence, including when both names are gone. A first-loss replay with genuine surviving Single keeps GenericPairLoss and does not incorrectly enter last-loss replay.

visitFixedNonC16Targets(originalP:c16Plan:targetGenerationID:originalPairAccounting:body:) emits immutable source-derived unique qualified postorder targets. fixedNonC16Targets is compatibility array collection. All original generation-leases descendants NOW remain in fixed postorder; actual drain consumed subset/replacement/new guard births require real external receipts and a genuine prefix owner. No current scan removes a target. visitCompleteProjection emits actual checked complete projection rows with fresh binding per callback. Logical Store stream hashes remain a distinct pending actual codec interface; existing canonical JSON commitments are not renamed as logical hashes.

Full11: dev|ino|mode|uid|gid|nlink|size|mtime_s|mtime_ns|ctime_s|ctime_ns. Persisted9: indices0,1,2,5,6,7,8,9,10. Nine root keys and three parents are unchanged; no global mixed100k ceiling is invented. Typed current-overlay capacity is awaiting root's frozen versioned recipe decision, and old bounds remain exact.
