# Minimum prospective A tuple and producer cuts

Independent read-only GPT-6.1 Sol xhigh. Supplemental prerequisite contract direction only, bound to immutable REVIEWb37729b0/INPUTS6633575c/V9BINDING6674f525. Root has indicated an intent to select A under14/20 after this review; this document does not itself author that decision, an API or a product implementation. Prior report and all historical direction artifacts remain unchanged.

## Minimum logical tuple to freeze

These are required semantic bindings, not new declarations/methods. Authors may combine fixed fields into one unambiguous versioned canonical commitment, but cannot omit a binding or substitute an unproduced hash.

| Binding | Minimum authentic value/commitment and current consumer |
|---|---|
| Subject/version | Prospective compact schema and semantic-DATA contract version; exact eraseID and target generationID; original-P/preparation, real final Sources/Progress/phase-C and consumer-complete transition binding. Real producer frame binds all of these before loss. |
| Target identity | Actual released persistent schema/migration/replica/workspace/generation identity; exact canonical current-pointer bytes/SHA and actual preserved-manifest bytes/SHA plus actual full named-held facts; known-replica/installed/retired/singleton disposition is included in those actual values and the final physical namespace proof. A digest may bind the entire actual pointer/list without embedding an unbounded duplicate array, provided fresh reads parse/check its complete incumbent grammar and compare canonical equality. |
| Complete semantic fact | Actual successful invocation of the full graph core, exact empty deletion ledger, complete Journal validation/checkpoint, zero revision/sequence/receipt/quarantine/entity histories and clean context; canonical result binding for the complete fixed predicate vocabulary. It is produced by genuine context/identity source, not a stage/Boolean/caller ModelContext or two zero counts. Include original-vs-new semantic route/schema disposition; do not transfer the new schema2 result into old schema1 by assumption. |
| Complete persistent image | Versioned closed canonical qualified-path/kind/full-actual-fact/byteCount/regular-byte-SHA stream; exact root/parent roles and absence/presence grammar; actual SQL/WAL/SHM/all supported sibling and content input bytes. Bind the exact target image, actual pointer and preserved manifest as one image-input commitment with checked row/count/byte bounds. A generic generation semantic digest or main SQL hash alone is not this stream. |
| Production bridge | Genuine graph/context-source/copy-image observation and its exact initial original byte-image, before/after source equality, actual alias drain and checked resource close/disposal. Distinct original-source facts and private-copy birth facts never compare as if their inode/ctime were identical. The real typed producer attests how its context denotes the committed original image; fresh DATA cannot infer this bridge from a copy path. |
| Final-image seal | Real consumer-complete frame reobserves the target image after every target-affecting save/checkpoint/reader-close/producer is complete; it binds that equal image to the previously produced graph facts and captures actual final pointer/manifest/root full facts. No future inode/time or manufactured post-close image is predicted. Fixed namespace outcomes and permitted parent metadata changes are separately authenticated by the actual final cut. |
| Semantic currentness | Frozen semantic-predicate/reader-image interpretation contract and actual source-backed compatibility disposition with current registered families/schema/enrollments/Journal grammar. Current pure C47/C08 and applicable Journal/active-release contract checks run freshly. A stored version/hash does not waive a newly required predicate. Source provenance may be recorded, but no arbitrary exact-source pin or blanket upgrade refusal is authorized. |
| Durable lineage | Actual sole-Store typed consumer-complete transition, canonical publication/readback, complete reserved-temp/prefix and current first-held capsule/manifest/catalog source binding. DATA is durable result lineage only. The private consumer receipt itself is not decoded/recreated. |
| Fresh actual rebind | New actual EX and first-held current capsule/control/finite suffix, current protection/UID/GID/link/ancestry/bounds, complete named-held image reads plus before/after stability and all checked closes, exact pointer/manifest/identity equality and independently current namespace/OS facts. This fresh completed observation, not the decoded tuple, supports subsequent current semantic/terminal admission. |

The persistent-image algorithm must explicitly define which full directory facts can change due to declared parent/catalog effects and how those changes are proved. Do not ignore them, predict them or require a pre-effect parent ctime forever. Original target source file/node bytes/facts remain exact where no legitimate target effect occurred. Historical nine-field facts still project only from genuine actual eleven-field observation plus authentic role-policy UID/GID checks, as c2aff requires; no missing historical fields are invented.

## Producer timeline and refusal boundaries

1. Obtain the real original/retained/cold full-context source while full semantic controls and actual reader/EX/retirement authority survive. Retain a concrete checked attempt before any source/copy acquisition. Use existing legitimately authorized complete semantic-validation mechanisms; this does not create a fresh observer write permission.
2. Establish the complete original target input image and genuine context bridge. If using a private copy, capture/verify exact original bytes and controlled copy source before constructing its context; own any real copy/sidecar effects under the already authentic producer authority. Run ALL complete predicates and identity/checkpoint checks on that actual context, with no bootstrap/save/migration/dirty state. Reprove source image before/after reads. Checked alias drain/disposal/close must finish before this producer is complete. No bare context success return creates durable graph DATA.
3. Finish all remaining actual semantic/physical/Notification-control close/namespace/preferences/rating/diagnostics consumers. Any operation that can change target DB/WAL/SHM bytes—including normal checkpoint or close—must be completed and accounted. Reobserve the final target input image and prove it is the same image as the genuine graph DATA. If a legitimate target-changing effect breaks that equality, re-establish the complete semantic predicate with a genuinely authorized reader BEFORE capsule production. Do not accept changed bytes by appealing to probable emptiness or by replacing the original commitment. This is a producer sequencing obligation, not a permanent valid-state refusal.
4. Perform authentic final R→C and final progress publication/readback as required by the actual control timeline. Recheck complete current consumer facts and target equality, then privately issue the consumer-complete transition while full old inputs still survive. Capture actual final full facts only after their effects; no future or self facts. The precise order of final progress/C and capsule must be frozen with Store/central and cannot be inferred from a stage name.
5. Sole Store positively publishes/readbacks the real DATA tuple/transition/capsule under exact real authority. It records the graph/image semantic bindings as part of its bounded canonical commitment. Only afterward may source/progress/old controls begin their finite deletion. Capsule publication failure, prefix ambiguity or close uncertainty permits no dependency loss or completion.
6. Each fresh compact origin independently authenticates the current first-held capsule/suffix/control cut and real EX, observes the complete current target/Data physical inputs with checked closes and canonical equality, and checks current semantic compatibility/enrollments. No fresh SwiftData context or copy is necessary on the successful A path; no existing context constructor is claimed no-effects. Decode gives DATA, while current physical/authority producers issue the real lexical proof. Preserve nonrecursive admission: control/EX requireActualCut does not invoke the inspector that is proving its own graph/image result.
7. Obtain actual current selected-ID pending+delivered OS absence with before/after-await revalidation. Keep all namespace/protection/finite-prefix/root/last capsule/checked Store-close rules. Old semantic facts confer no cached EX/G/drain/OS/deletion/ready capability. Close and authority release ordering remain unchanged.

A is therefore prospective only for genuinely produced, durably transferred matching-image graph DATA. An old capsule/control that never received this producer cannot be upgraded by setting hashes or computing the expected empty result. Legacy valid states use actual full original/retained validation and the existing supported compatibility disposition. If a cut lacks that route, complete it under authentic B/other proven producer authority rather than silently exclude it. Lost historical IDs remain separate c2aff due; A cannot recover missing bits.

## Capacity and exact-source obligations

- The tuple uses fixed UUID/schema/version/role/outcome values and fixed cryptographic commitments/full-root facts. Complete physical rows/images remain streamed/authenticated from the actual surviving target and pointer/manifest; this does not copy the entire DB or all node rows into the compact capsule. Do not add arbitrary free-form paths, unbounded family strings/lists, duplicated source tables or scalar truncation. Freeze its actual canonical field vocabulary/codec/size and compare it against the real16MiB capsule budget, retaining the lossless selected raw ID-origin bounds from d389. No exact capsule-capacity approval is issued here. Raw Data Base64 expansion and catalog/root descriptors must be counted by actual encoded representation, not raw-byte addition.
- All incumbent schema/format96MiB metadata, original C16 step100000, per-role source limits, per-file/per-recorded-tree1GiB, node/depth and checked IO budgets remain unchanged. Current actual pointer/preserved manifest readers use their actual role ceilings; any optional retired data/list must remain completely checked. A new image stream is derived from those complete existing inputs, with overflow-checked row/byte counts, bounded traversal/materialization and actual complete source-change checks; no target9-field fact shorthand becomes a guessed nine-node capacity.
- Real copy effects used at the original producer still need the full existing resource/capacity/sidecar/checked-close lifecycle. Successful A removes the need for a NEW fresh copy effect; it does not retroactively authorize the old or seed-copy effect with observer86825.
- Before source implementation can be approved, freeze the actual graph DATA/image interpretation and current-compatibility table; private producer/frame→Store transition; final-image sequencing; bounded codec and canonical commitments; fresh checked physical observation→semantic DATA rebind; actual current scope/namespace/OS consumers and every interrupted terminal prefix. Implemented source must prove each exact route and cannot contain a default success/refusal-for-all-valid-populations substitute.
- DEBUG/nonDEBUG coupled semantic compilation and affected build/native/capacity/fault verification remain required. Exercise complete-family/nonempty/foreign Journal, dirty/unsaved context, original vs private image mismatch, WAL/SHM checkpoint/close changes, missing/corrupt checkpoint, pointer/manifest/replica/root replacement, changed validator/enrollment, absent old DATA, partial durable transfer, IO/close uncertainty and same/fresh last-name replay. No stale authorization or gate result is cached for speed.

No new owner-only ambiguity is identified for this prospective mechanism if every frozen semantic/currentness/safety/capacity obligation is preserved. Root can record its concrete reversible A direction under14/20 using REVIEWb377 and this addendum; only genuinely silent/contradictory supported compatibility policy goes to the owner. No implementation/runtime/gate approval follows that selection.
